In [2]:
import pandas as pd
from pandas import json_normalize
from pathlib import Path
from sqlalchemy import create_engine, text
from Credentials import engine_DEV_Test as engine
import os
import json
from concurrent.futures import ThreadPoolExecutor
import polars as pl

In [ ]:

query = """
    Select top 1 watermark
    from BCDA_data.dbo.watermark
    order by id desc
"""

timestamp = pd.read_sql(query,
    engine
)

def truncate_stging_tables(table_name):
    print("TRUNCATING:", table_name)
    with engine.begin() as conn:
        conn.execute(text(f"""
            IF OBJECT_ID('BCDA_Data.dbo.{table_name}', 'U') IS NOT NULL
            truncate table BCDA_Data.dbo.{table_name}
        """))

query = """
    SELECT watermark
    FROM BCDA_data.dbo.watermark
    ORDER BY ID DESC
    OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
"""

timestamp_2 = pd.read_sql(query,
    engine
)
print(timestamp['watermark'].iloc[0])
print(timestamp_2['watermark'])

2026-03-05T20:13:24.953+00:00
2026-03-05T20:04:39.430+00:00

In [ ]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=Dev-Test;"
    "DATABASE=BCDA_Staging;"
    "UID=sa;"
    "PWD=Jesus&411;"
)

cursor = conn.cursor()

filepath = Path(r"C:\BCDA\ExplanationOfBenefit_0020_20260419230529.ndjson")

batch = []
batch_size = 5000

with open(filepath, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue

        batch.append((line,filepath.name))

        if len(batch) >= batch_size:
            cursor.executemany(
                "INSERT INTO staging_bcda_raw (json_line, file_name) VALUES (?, ?)",
                batch
            )
            conn.commit()
            batch.clear()

if batch:
    cursor.executemany(
        "INSERT INTO staging_bcda_raw (json_line, file_name) VALUES (?, ?)",
        batch
    )
    conn.commit()

cursor.close()
conn.close()

KeyboardInterrupt:

In [12]:
from datetime import datetime
datetime.now().strftime("%Y-%m-%d %H:%M:%S")

'2026-04-21 14:17:48'

In [ ]:
engine_DEV_Test = create_engine(
    "mssql+pyodbc://sa:Jesus&411@Dev-Test/BCDA_Data?driver=ODBC+Driver+17+for+SQL+Server"
)
data_dir = r"C:\BCDA"

filepath = Path(r"C:\BCDA\ExplanationOfBenefit_0020_20260419230529.ndjson")

records = []

with open(filepath, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            print(f"Skipping bad line in {filepath}")
eob_df = pd.json_normalize(records)
eob_df.rename(columns = {
    'id': 'Claim_ID',
    'patient.reference': 'Patient_ID'
}, inplace = True)
eob_df.columns = eob_df.columns.str.replace('.', '_')
eob_df['Patient_ID'] = eob_df['Patient_ID'].str.split('/').str[-1]
pd.set_option('display.max_columns', None)
eob_df

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,payment_date
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-04-19T23:02:41+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-22835075708,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2016-03-02,2016-03-02,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,347830662,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-04-19T23:02:41+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-22938286821,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2016-03-02,2016-03-02,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,347830662,USD,87.34,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. JAMES W SAWYER ...,2026-04-19T23:02:41+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-23006644580,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2016-05-02,2016-05-02,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,347830662,USD,251.19,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",DR. JAMES W SAWYER M.D.,"[{'code': 'npi', 'display': 'National Provider...",1225005747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. JAMES W SAWYER ...,2026-04-19T23:02:41+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-23023756376,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2016-05-02,2016-05-02,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,347830662,USD,8.48,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",DR. JAMES W SAWYER M.D.,"[{'code': 'npi', 'display': 'National Provider...",1225005747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. JAMES W SAWYER ...,2026-04-19T23:02:41+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,dme-23026737822,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-a-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2016-08-07,2016-05-09,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,347830662,USD,291.04,http://hl7.org/fhir/sid/us-npi,1356334577,"[{'code': '82', 'display': 'DMERC; DMEPOS clai...",DR. JAMES W SAWYER M.D.,"[{'code': 'npi', 'display': 'National Provider...",1225005747,MINIMED DISTRIBUTION CORP.,Practitioner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35810,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. KEVIN RANDALL H...,2026-04-19T23:03:38+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9195429354,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 557},...",claim,2025-05-16,2025-05-16,CMS,2025-10-17T19:25:22.158+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,386054540,USD,106.22,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,NaN
35811,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. KEVIN RANDALL H...,2026-04-19T23:03:38+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9195429356,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 968},...",claim,2025-06-17,2025-06-17,CMS,2025-10-17T19:25:22.158+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,386054540,USD,106.25,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,NaN
35812,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'BRENT WILLIAM ROBIN...,2026-04-19T23:03:38+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9209340867,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 1053}...",claim,2025-10-15,2025-10-15,CMS,2025-10-31T16:39:56.676+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,386054540,USD,106.22,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,NaN
35813,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'BRENT WILLIAM ROBIN...,2026-04-19T23:03:38+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9476570257,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 14892...",claim,2025-11-25,2025-11-25,CMS,2025-12-19T17:22:46.001+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,386054540,USD,1076.10,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,NaN
35814,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'BRENT WILLIAM ROBIN...,2026-04-19T23:03:38+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9618452853,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-3...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 5419}...",claim,2025-12-30,2025-12-30,CMS,2026-01-23T16:52:33.546+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,386054540,USD,199.24,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,NaN

In [5]:
eob_df.columns

Index(['benefitBalance', 'careTeam', 'created', 'diagnosis', 'disposition',
       'extension', 'Claim_ID', 'identifier', 'insurance', 'item', 'outcome',
       'resourceType', 'status', 'supportingInfo', 'total', 'use',
       'billablePeriod_end', 'billablePeriod_start',
       'insurer_identifier_value', 'meta_lastUpdated', 'meta_profile',
       'Patient_ID', 'payment_amount_currency', 'payment_amount_value',
       'provider_identifier_system', 'provider_identifier_value',
       'type_coding', 'referral_display', 'referral_identifier_type_coding',
       'referral_identifier_value', 'provider_display', 'provider_type',
       'facility_display', 'facility_extension',
       'facility_identifier_type_coding', 'facility_identifier_value',
       'contained', 'billablePeriod_extension', 'provider_reference',
       'subType_coding', 'subType_text', 'procedure', 'payment_date'],
      dtype='object')

In [32]:
if 'contained' in eob_df.columns:        
    eob_df_contained = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='contained',
        meta = 'Claim_ID'
    )
    eob_df_contained = eob_df_contained.explode('identifier')
    
    eob_df_contained = json_normalize(
        eob_df_contained.to_dict(orient='records')
    )
    eob_df_contained = eob_df_contained.explode('identifier.type.coding')
    eob_df_contained = json_normalize(
        eob_df_contained.to_dict(orient='records')
    )
    if 'code.coding' in eob_df_contained.columns:
        eob_df_contained = eob_df_contained.explode('code.coding')
        
        eob_df_contained = json_normalize(
            eob_df_contained.to_dict(orient='records')
        )
        eob_df_contained.rename(columns = {
            'valueQuantity.value': 'results',
            'code.coding.code': 'test_cd',
            'code.coding.display': 'test_display'
        }, inplace=True)
    eob_df_contained.rename(columns = {'identifier.value':'NPI', 'identifier.type.coding.code': 'type_code'}, inplace = True)
eob_df_contained.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3310 entries, 0 to 3309
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   active                         3308 non-null   object
 1   id                             3310 non-null   object
 2   name                           3308 non-null   object
 3   resourceType                   3310 non-null   object
 4   meta.profile                   3308 non-null   object
 5   status                         2 non-null      object
 6   code.coding                    0 non-null      float64
 7   results                        2 non-null      float64
 8   Claim_ID                       3310 non-null   object
 9   NPI                            3308 non-null   object
 10  identifier.system              1654 non-null   object
 11  identifier                     0 non-null      float64
 12  type_code                      3308 non-null   object
 13  identifier.type.coding.system  3308 non-null   object
 14  identifier.type.coding         0 non-null      float64
 15  test_cd                        2 non-null      object
 16  test_display                   2 non-null      object
 17  code.coding.system             2 non-null      object
dtypes: float64(4), object(14)
memory usage: 465.6+ KB

In [ ]:
if 'benefitBalance' in eob_df.columns:
    eob_benefitbalance = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='benefitBalance',
        meta = 'Claim_ID'
    )
    if 'category.coding' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('category.coding')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        eob_benefitbalance.rename(columns = {
            'category.coding.code': 'code',
            'category.coding.display': 'display'
        }, inplace = True)
        #eob_benefitbalance_category_coding = json_normalize(
        #    eob_benefitbalance.to_dict(orient='records'),
        #    record_path='category.coding',
        #    meta = ['Claim_ID', 'financial']
        #)
    if 'financial' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('financial')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        eob_benefitbalance.rename(columns = {
        'financial.usedMoney.currency': 'currency_type',
        'financial.usedMoney.value' : 'amount'
        }, inplace = True)
    
        
        #eob_benefitbalance_financial = json_normalize(
        #    eob_benefitbalance_category_coding.to_dict(orient='records'),
        #    record_path='financial',
        #    meta = [col for col in eob_benefitbalance_category_coding.columns if col != 'financial']
        #)
    eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
    )
    if 'financial.type.coding' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('financial.type.coding')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        eob_benefitbalance.rename(columns = {
        'financial.type.coding.display': 'type',
        }, inplace = True)
    
    #eob_benefitbalance_financial_type_coding = json_normalize(
    #    eob_benefitbalance_financial.to_dict(orient='records'),
    #    record_path='type.coding',
    #    meta = [col for col in eob_benefitbalance_financial.columns if col != 'type.coding'],
    #    record_prefix='type_coding_'
    #)
    
    
    #if 'financial.usedUnsignedInt' not in eob_benefitbalance.columns:
    #    eob_benefitbalance['usedUnsignedInt'] = None
    if 'financial.usedUnsignedInt' in eob_benefitbalance.columns:
        eob_benefitbalance.rename(columns = {'financial.usedUnsignedInt':'usedUnsignedInt'}, inplace = True)
        
eob_benefitbalance

,Claim_ID,category.coding.code,category.coding.display,category.coding.system,currency_type,amount,usedUnsignedInt,financial.type.coding.code,type,financial.type.coding.system
0,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,Carrier Claim Cash Deductible Applied Amount (...,https://bluebutton.cms.gov/resources/codesyste...
1,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,64.42,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
2,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
3,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,69.99,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Submitted Charge Amount (sum...,https://bluebutton.cms.gov/resources/codesyste...
4,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,65.73,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Allowed Charge Amount (sum o...,https://bluebutton.cms.gov/resources/codesyste...
...,...,...,...,...,...,...,...,...,...,...
55079,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,26.62,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Part B Coinsurance Amount,https://bluebutton.cms.gov/resources/codesyste...
55080,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,104.33,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
55081,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
55082,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Blood Deductible Liability Amount,https://bluebutton.cms.gov/resources/codesyste...
55083,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Primary Payer (if not Medicare) Claim Paid...,https://bluebutton.cms.gov/resources/codesyste...

In [ ]:
from collections import Counter

c = Counter(eob_benefitbalance['category.coding.display'])

In [33]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = ['Claim_ID', 'sequence']
)
if 'reason.coding' in eob_df_item_adjudication.columns:
    eob_df_item_adjudication = eob_df_item_adjudication.explode('reason.coding')
    
    eob_df_item_adjudication = json_normalize(
        eob_df_item_adjudication.to_dict(orient='records')
    )
    
    eob_df_item_adjudication.rename(columns = {
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display'
    }, inplace = True)
if 'category.coding' in eob_df_item_adjudication.columns:
    eob_df_item_adjudication = eob_df_item_adjudication.explode('category.coding')
    
    eob_df_item_adjudication = json_normalize(
        eob_df_item_adjudication.to_dict(orient='records')
    )
    
    eob_df_item_adjudication.rename(columns = {
    'category.coding.display': 'display',
    'category.coding.code': 'cat_code'
    }, inplace = True)
    
if 'extension' in eob_df_item_adjudication.columns:
    eob_df_item_adjudication = eob_df_item_adjudication.explode('extension')
    
    eob_df_item_adjudication = json_normalize(
        eob_df_item_adjudication.to_dict(orient='records')
    )
    
    eob_df_item_adjudication.rename(columns = {
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display'
    }, inplace = True)
eob_df_item_adjudication

,extension,amount.currency,amount.value,Claim_ID,sequence,reason_code,reason_display,reason.coding.system,reason.coding,cat_code,display,category.coding.system,extension.url,LINE_PMT_80_100_CD,LINE_PMT_80_100_display,extension.valueCoding.system
0,NaN,NaN,NaN,carrier-27286904395,1,0,N/A,https://bluebutton.cms.gov/resources/variables...,NaN,denialreason,Denial Reason,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
1,NaN,USD,48.01,carrier-27286904395,1,NaN,NaN,NaN,NaN,benefit,Benefit Amount,http://terminology.hl7.org/CodeSystem/adjudica...,https://bluebutton.cms.gov/resources/variables...,1,100%,https://bluebutton.cms.gov/resources/variables...
2,NaN,USD,48.01,carrier-27286904395,1,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,Line NCH Medicare Payment Amount,https://bluebutton.cms.gov/resources/codesyste...,https://bluebutton.cms.gov/resources/variables...,1,100%,https://bluebutton.cms.gov/resources/variables...
3,NaN,USD,0.00,carrier-27286904395,1,NaN,NaN,NaN,NaN,paidtopatient,Paid to patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
4,NaN,USD,0.00,carrier-27286904395,1,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,Line Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688751,NaN,USD,0.00,outpatient-9623755765,2,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,Revenue Center Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN
688752,NaN,USD,0.00,outpatient-9623755765,2,NaN,NaN,NaN,NaN,paidbypatient,Paid by patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
688753,NaN,USD,0.00,outpatient-9623755765,2,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,Revenue Center Patient Responsibility Payment ...,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN
688754,NaN,USD,0.00,outpatient-9623755765,2,NaN,NaN,NaN,NaN,submitted,Submitted Amount,http://terminology.hl7.org/CodeSystem/adjudica...,NaN,NaN,NaN,NaN
688755,NaN,USD,0.00,outpatient-9623755765,2,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,Revenue Center (Medicare) Payment Amount,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN

In [37]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item

,adjudication,careTeamSequence,extension,sequence,category.coding,locationCodeableConcept.coding,locationCodeableConcept.extension,productOrService.coding,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,diagnosisSequence,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID
0,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': 'V', 'display': 'Pneumococcal/flu va...","[{'code': '60', 'display': 'Mass Immunization ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '90653', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
1,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,2,"[{'code': 'V', 'display': 'Pneumococcal/flu va...","[{'code': '60', 'display': 'Mass Immunization ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': 'G0008', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
2,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': '1', 'display': 'Medical care', 'sys...","[{'code': '11', 'display': 'Office. Location, ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '99214', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-10,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890
3,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': '2', 'display': 'Surgery', 'system':...","[{'code': '22', 'display': 'Outpatient Hospita...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '64493', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,"[{'coding': [{'code': '50', 'system': 'https:/...",NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
4,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,2,"[{'code': '2', 'display': 'Surgery', 'system':...","[{'code': '22', 'display': 'Outpatient Hospita...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '64494', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,"[{'coding': [{'code': '50', 'system': 'https:/...",NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36113,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,NaN,NaN,"[{'code': '36415', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,"[{'code': '0300', 'display': 'Laboratory-gener...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36114,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,2,NaN,NaN,NaN,"[{'code': 'G0463', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,"[{'code': '0510', 'display': 'Clinic-general c...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36115,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,3,NaN,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fh...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,"[{'code': '0001', 'display': 'Total charge', '...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36116,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,NaN,NaN,"[{'code': 'G0463', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2026-01-12,TX,"[{'code': '0510', 'display': 'Clinic-general c...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9623755765
36117,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,2,NaN,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fh...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,"[{'code': '0001', 'display': 'Total charge', '...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9623755765

In [ ]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
if 'category.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('category.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
    'category.coding.code': 'category_code',
    'category.coding.display': 'category_display'
    }, inplace = True) 
if 'locationCodeableConcept.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('locationCodeableConcept.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
    'locationCodeableConcept.coding.code': 'location_code',
    'locationCodeableConcept.coding.display': 'location_display'
    }, inplace = True)     

if 'productOrService.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('productOrService.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
    'productOrService.coding.code': 'product_code',
    'productOrService.coding.display': 'product_display'
    }, inplace = True)     
    
if 'productOrService.extension' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('productOrService.extension')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
    'productOrService.extension.valueCoding.code': 'product_ext_cd',
    'productOrService.extension.valueCoding.display': 'product_ext_display'
    }, inplace = True) 
    
if 'modifier' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('modifier')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    eob_df_item = eob_df_item.explode('modifier.coding')
    eob_df_item = json_normalize(
    eob_df_item.to_dict(orient='records')
    )
    eob_df_item.rename(columns = {
    'modifier.coding.code': 'modifier_code',
    'modifier.coding.version': 'modifier_version'
    }, inplace = True) 
    
if 'revenue.extension' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('revenue.extension')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
    'revenue.extension.valueCoding.display': 'revenue_ext_display',
    'revenue.extension.valueCoding.code': 'revenue_ext_code'
    }, inplace = True)    
if 'revenue.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('revenue.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
        'revenue.coding.code': 'revenue_code',
        'revenue.coding.display': 'revenue_display'
    }, inplace = True)
eob_df_item.rename(columns = {
    'sequence': 'item_sequence'
}, inplace = True)
eob_df_item

KeyError: "Key 'diagnosisSequence' not found. To replace missing values of 'diagnosisSequence' with np.nan, pass in errors='ignore'"

In [34]:
eob_df_insurance = eob_df.explode('insurance')
eob_df_insurance = json_normalize(
    eob_df_insurance.to_dict(orient='records')
)
eob_df_insurance['insurance.coverage.reference'] = eob_df_insurance['insurance.coverage.reference'].str.split('/').str[-1]
eob_df_insurance

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,insurance.coverage.reference,insurance.focal,insurance.coverage.extension
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,part-b-431397073,True,NaN
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,part-b-431397073,True,NaN
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545891,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2020-01-09,2020-01-09,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,164.60,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,part-b-431397073,True,NaN
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27396860372,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 390.2...",claim,2020-01-23,2020-01-23,CMS,2020-03-01T04:45:59.805+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,96.30,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,part-b-431397073,True,NaN
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'TROY DALE FOSTER D....,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27548148011,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 662.9...",claim,2020-01-30,2020-01-30,CMS,2020-04-12T22:53:20.402+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,111.94,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",TROY DALE FOSTER D.O.,"[{'code': 'npi', 'display': 'National Provider...",1134415169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,part-b-431397073,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9174161667,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 703},...",claim,2025-09-08,2025-09-08,CMS,2025-09-26T16:54:02.790+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,part-b-73564997,True,NaN
16847,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. PAUL R BRADLEY ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710749,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 375},...",claim,2025-10-01,2025-10-01,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,part-b-73564997,True,NaN
16848,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'SNEHAL SHRIVASTAVA ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710750,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 8}, '...",claim,2025-10-13,2025-10-13,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,7.84,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,part-b-73564997,True,NaN
16849,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,part-b-73564997,True,NaN
16850,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,part-b-73564997,True,NaN

In [21]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item = eob_df_item.explode('category.coding')
eob_df_item = eob_df_item.explode('locationCodeableConcept.coding')
eob_df_item = eob_df_item.explode('productOrService.coding')
eob_df_item = eob_df_item.explode('modifier')
eob_df_item = json_normalize(
    eob_df_item.to_dict(orient='records')
)
eob_df_item = eob_df_item.explode('modifier.coding')
eob_df_item = json_normalize(
eob_df_item.to_dict(orient='records')
)
if 'revenue.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('revenue.extension')
    eob_df_item = eob_df_item.explode('revenue.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename({
        'revenue.coding.code': 'revenue_code',
        'revenue.coding.display': 'revenue_display',
        'revenue.extension.valueCoding.display': 'revenue_ext_display',
        'revenue.extension.valueCoding.code': 'revenue_ext_code',
    }, inplace = True)
eob_df_item.rename(columns = {
    'sequence': 'item_sequence',
    'quantity.value': 'quantity',
    'category.coding.code': 'category_code',
    'category.coding.display': 'category_display',
    'locationCodeableConcept.coding.code': 'location_code',
    'locationCodeableConcept.coding.display': 'location_display',
    'productOrService.coding.code': 'product_code',
    'productOrService.coding.display': 'product_display',
    'servicedPeriod.end': 'serviceperiod_end',
    'servicedPeriod.start': 'serviceperiod_start',
    'modifier.coding.code': 'modifier_code',
    'modifier.coding.version': 'modifier_version'
}, inplace = True)
cols = [
    'Claim_ID',
    'item_sequence',
    'careTeamSequence',
    'diagnosisSequence',
    'product_code',
    'product_display',
    'revenue_code',
    'revenue_display',
    'revenue_ext_code',
    'revenue_ext_display',
    'category_code',
    'category_display',
    'modifier_code',
    'modifier_version',
    'location_code',
    'location_display',
    'serviceperiod_start',
    'serviceperiod_end',
    'servicedDate'
]
eob_df_item = eob_df_item.reindex(columns = cols)
eob_df_item['careTeamSequence'] = eob_df_item['careTeamSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)
eob_df_item['diagnosisSequence'] = eob_df_item['diagnosisSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)
eob_df_item = eob_df_item.drop_duplicates()
eob_df_item = eob_df_item.reset_index(drop=True)
eob_df_item

,Claim_ID,item_sequence,careTeamSequence,diagnosisSequence,product_code,product_display,revenue_code,revenue_display,revenue_ext_code,revenue_ext_display,category_code,category_display,modifier_code,modifier_version,location_code,location_display,serviceperiod_start,serviceperiod_end,servicedDate
0,carrier-34884414563,1,3.0,1.0,93297,NaN,NaN,NaN,NaN,NaN,1,Medical care,26,5,11,"Office. Location, other than a hospital, skill...",2026-02-18,2026-02-18,NaN
1,carrier-34893583414,1,3.0,1.0,71046,NaN,NaN,NaN,NaN,NaN,4,Diagnostic radiology,26,5,11,"Office. Location, other than a hospital, skill...",2026-01-16,2026-01-16,NaN
2,pde-55883740300,1,1.0,NaN,31722000490,Venlafaxine Hydrochloride - VENLAFAXINE HYDROC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-23
3,carrier-34864369702,1,3.0,1.0,10005,NaN,NaN,NaN,NaN,NaN,2,Surgery,X5,5,22,Outpatient Hospital. A portion of a hospital w...,2026-01-12,2026-01-12,NaN
4,carrier-34864369702,2,3.0,1.0,10006,NaN,NaN,NaN,NaN,NaN,2,Surgery,X5,5,22,Outpatient Hospital. A portion of a hospital w...,2026-01-12,2026-01-12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,carrier-34899027455,1,3.0,1.0,92014,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,11,"Office. Location, other than a hospital, skill...",2026-02-20,2026-02-20,NaN
170,carrier-34899027455,2,3.0,1.0,92133,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,11,"Office. Location, other than a hospital, skill...",2026-02-20,2026-02-20,NaN
171,carrier-34899027455,3,3.0,3.0,92015,NaN,NaN,NaN,NaN,NaN,Q,Vision items or services,NaN,NaN,11,"Office. Location, other than a hospital, skill...",2026-02-20,2026-02-20,NaN
172,carrier-34894397660,1,3.0,1.0,99232,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,21,"Inpatient Hospital. A facility, other than psy...",2026-02-13,2026-02-13,NaN
173,carrier-34894397660,2,3.0,1.0,99239,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,21,"Inpatient Hospital. A facility, other than psy...",2026-02-14,2026-02-14,NaN

In [ ]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item = eob_df_item.explode('category.coding')
eob_df_item = eob_df_item.explode('locationCodeableConcept.coding')
eob_df_item = eob_df_item.explode('productOrService.coding')
eob_df_item = eob_df_item.explode('modifier')
eob_df_item = eob_df_item.explode('productOrService.extension')
eob_df_item = json_normalize(
    eob_df_item.to_dict(orient='records')
)
eob_df_item = eob_df_item.explode('modifier.coding')
eob_df_item = json_normalize(
eob_df_item.to_dict(orient='records')
)
eob_df_item
if 'revenue.coding' in eob_df_item.columns:
    eob_df_item = eob_df_item.explode('revenue.extension')
    eob_df_item = eob_df_item.explode('revenue.coding')
    
    eob_df_item = json_normalize(
        eob_df_item.to_dict(orient='records')
    )
    
    eob_df_item.rename(columns = {
        'revenue.coding.code': 'revenue_code',
        'revenue.coding.display': 'revenue_display',
        'revenue.extension.valueCoding.display': 'revenue_ext_display',
        'revenue.extension.valueCoding.code': 'revenue_ext_code',
    }, inplace = True)
eob_df_item[eob_df_item['productOrService.extension.valueCoding.code'].notna()]

,adjudication,careTeamSequence,extension,sequence,locationCodeableConcept.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,diagnosisSequence,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,productOrService.coding.code,productOrService.coding.system,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,modifier.coding,category.coding,locationCodeableConcept.coding,productOrService.extension,productOrService.coding.display,modifier.coding.code,modifier.coding.system,modifier.coding.version,modifier.coding.display,revenue_code,revenue_display,revenue.coding.system,revenue.extension.url,revenue_ext_code,revenue_ext_display,revenue.extension.valueCoding.system
0,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,90653,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,G0008,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-10,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,1,Medical care,https://bluebutton.cms.gov/resources/variables...,11,"Office. Location, other than a hospital, skill...",https://bluebutton.cms.gov/resources/variables...,99214,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64493,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64494,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39502,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,36415,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,N,Packaged incidental service (no separate APC p...,https://bluebutton.cms.gov/resources/variables...
39503,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,2,NaN,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...
39504,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,3,NaN,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...
39505,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,0.0,NaN,NaN,NaN,NaN,2026-01-12,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...
39506,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...

In [37]:
eob_df_item[eob_df_item['productOrService.extension.valueCoding.code'].notna()]

,adjudication,careTeamSequence,extension,sequence,locationCodeableConcept.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,diagnosisSequence,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,productOrService.coding.code,productOrService.coding.system,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,modifier.coding,category.coding,locationCodeableConcept.coding,productOrService.extension,productOrService.coding.display,modifier.coding.code,modifier.coding.system,modifier.coding.version,modifier.coding.display,revenue_code,revenue_display,revenue.coding.system,revenue.extension.url,revenue_ext_code,revenue_ext_display,revenue.extension.valueCoding.system
0,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,90653,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,G0008,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-10,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,1,Medical care,https://bluebutton.cms.gov/resources/variables...,11,"Office. Location, other than a hospital, skill...",https://bluebutton.cms.gov/resources/variables...,99214,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64493,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64494,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39502,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,36415,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,N,Packaged incidental service (no separate APC p...,https://bluebutton.cms.gov/resources/variables...
39503,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,2,NaN,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...
39504,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,3,NaN,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...
39505,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,0.0,NaN,NaN,NaN,NaN,2026-01-12,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...
39506,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,2,NaN,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,http://hl7.org/fhir/StructureDefinition/data-a...,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...

In [26]:
eob_df_item.info()

<class 'pandas.core.frame.DataFrame'>
Index: 178 entries, 0 to 177
Data columns (total 39 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   adjudication                            178 non-null    object
 1   careTeamSequence                        128 non-null    object
 2   diagnosisSequence                       107 non-null    object
 3   extension                               151 non-null    object
 4   sequence                                178 non-null    int64
 5   locationCodeableConcept.extension       107 non-null    object
 6   productOrService.extension              137 non-null    object
 7   quantity.value                          178 non-null    int64
 8   servicedPeriod.end                      107 non-null    object
 9   servicedPeriod.start                    107 non-null    object
 10  servicedDate                            65 non-null     object
 11  locationAddress.state                   50 non-null     object
 12  revenue.coding                          0 non-null      float64
 13  revenue.extension                       0 non-null      float64
 14  Claim_ID                                178 non-null    object
 15  category.coding.code                    107 non-null    object
 16  category.coding.display                 107 non-null    object
 17  category.coding.system                  107 non-null    object
 18  locationCodeableConcept.coding.code     107 non-null    object
 19  locationCodeableConcept.coding.display  107 non-null    object
 20  locationCodeableConcept.coding.system   107 non-null    object
 21  productOrService.coding.code            178 non-null    object
 22  productOrService.coding.system          178 non-null    object
 23  modifier                                0 non-null      float64
 24  category.coding                         0 non-null      float64
 25  locationCodeableConcept.coding          0 non-null      float64
 26  productOrService.coding.display         21 non-null     object
 27  modifier.coding.code                    54 non-null     object
 28  modifier.coding.system                  54 non-null     object
 29  modifier.coding.version                 50 non-null     object
 30  modifier.coding                         0 non-null      float64
 31  modifier.coding.display                 2 non-null      object
 32  revenue.coding.code                     50 non-null     object
 33  revenue.coding.display                  48 non-null     object
 34  revenue.coding.system                   50 non-null     object
 35  revenue.extension.url                   50 non-null     object
 36  revenue.extension.valueCoding.code      50 non-null     object
 37  revenue.extension.valueCoding.display   50 non-null     object
 38  revenue.extension.valueCoding.system    50 non-null     object
dtypes: float64(6), int64(2), object(31)
memory usage: 55.6+ KB

In [6]:
eob_dy_type = eob_df.explode('type_coding')

eob_dy_type= json_normalize(
    eob_dy_type.to_dict(orient='records')
)
eob_dy_type

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,type_coding.code,type_coding.display,type_coding.system
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CARRIER,NaN,https://bluebutton.cms.gov/resources/codesyste...
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,professional,Professional,http://terminology.hl7.org/CodeSystem/claim-type
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CARRIER,NaN,https://bluebutton.cms.gov/resources/codesyste...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43905,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,OUTPATIENT,NaN,https://bluebutton.cms.gov/resources/codesyste...
43906,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,institutional,Institutional,http://terminology.hl7.org/CodeSystem/claim-type
43907,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...
43908,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,OUTPATIENT,NaN,https://bluebutton.cms.gov/resources/codesyste...
43909,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,institutional,Institutional,http://terminology.hl7.org/CodeSystem/claim-type

In [11]:
eob_df_item_ext = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta='Claim_ID'
)
eob_df_item_ext = eob_df_item_ext.explode('extension')
#eob_df_item_ext = eob_df_item_ext.explode('locationCodeableConcept.extension')
eob_df_item_ext = json_normalize(
    eob_df_item_ext.to_dict(orient='records')
)
cols = [
        'Claim_ID',
        'sequence',
        'extension.url',
        'extension.valueCoding.code',
        'extension.valueCoding.system',
        #'locationCodeableConcept.extension.url',
        #'locationCodeableConcept.extension.valueCoding.code',
        #'locationCodeableConcept.extension.valueCoding.system',
        'extension.valueQuantity.value',
        'extension.valueCoding.display',
        #'locationCodeableConcept.extension.valueCoding.display',
        #'locationCodeableConcept.extension.valueIdentifier.system',
        #'locationCodeableConcept.extension.valueIdentifier.value',
        'extension.valueIdentifier.system',
        'extension.valueIdentifier.value',
        'extension.valueQuantity.code',
        'extension.valueQuantity.system',
        'extension.valueQuantity.unit'
    ]

eob_df_item_ext = eob_df_item_ext.reindex(columns=cols)
eob_df_item_ext.columns = eob_df_item_ext.columns.str.replace('.', '_')
eob_df_item_ext

,Claim_ID,sequence,extension_url,extension_valueCoding_code,extension_valueCoding_system,extension_valueQuantity_value,extension_valueCoding_display,extension_valueIdentifier_system,extension_valueIdentifier_value,extension_valueQuantity_code,extension_valueQuantity_system,extension_valueQuantity_unit
0,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,361924025,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,3,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,3,https://bluebutton.cms.gov/resources/variables...,NaN,Services,NaN,NaN,NaN,NaN,NaN
4,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,O1G,https://bluebutton.cms.gov/resources/variables...,NaN,Immunizations/Vaccinations,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
145346,outpatient-9519284917,1,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
145347,outpatient-9519284917,2,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
145348,outpatient-9519284917,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145349,outpatient-9623755765,1,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
145350,outpatient-9623755765,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
eob_df_item_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145351 entries, 0 to 145350
Data columns (total 11 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Claim_ID                          145351 non-null  object
 1   extension_url                     137052 non-null  object
 2   extension_valueCoding_code        106076 non-null  object
 3   extension_valueCoding_system      106076 non-null  object
 4   extension_valueQuantity_value     29512 non-null   float64
 5   extension_valueCoding_display     70736 non-null   object
 6   extension_valueIdentifier_system  1464 non-null    object
 7   extension_valueIdentifier_value   1464 non-null    object
 8   extension_valueQuantity_code      1464 non-null    object
 9   extension_valueQuantity_system    1464 non-null    object
 10  extension_valueQuantity_unit      1464 non-null    object
dtypes: float64(1), object(10)
memory usage: 12.2+ MB

In [155]:
from EOB import getwatermarks

w_1, w_2 = getwatermarks()

print(w_1)
print(w_2)

2026-03-20 12:43:48.780000
2026-03-13 10:48:52.957000

In [10]:
eob_df_item_loc_ext = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta='Claim_ID'
)
#eob_df_item_loc_ext = eob_df_item_loc_ext.explode('extension')
eob_df_item_loc_ext = eob_df_item_loc_ext.explode('locationCodeableConcept.extension')
eob_df_item_loc_ext = json_normalize(
    eob_df_item_loc_ext.to_dict(orient='records')
)
cols = [
        'Claim_ID',
        'sequence',
        #'extension.url',
        #'extension.valueCoding.code',
        #'extension.valueCoding.system',
        'locationCodeableConcept.extension.url',
        'locationCodeableConcept.extension.valueCoding.code',
        'locationCodeableConcept.extension.valueCoding.system',
        #'extension.valueQuantity.value',
        #'extension.valueCoding.display',
        'locationCodeableConcept.extension.valueCoding.display',
        'locationCodeableConcept.extension.valueIdentifier.system',
        'locationCodeableConcept.extension.valueIdentifier.value',
        #'extension.valueIdentifier.system',
        #'extension.valueIdentifier.value',
        #'extension.valueQuantity.code',
        #'extension.valueQuantity.system',
        #'extension.valueQuantity.unit'
    ]

eob_df_item_loc_ext = eob_df_item_loc_ext.reindex(columns=cols)
eob_df_item_loc_ext.columns = eob_df_item_loc_ext.columns.str.replace('.', '_')
eob_df_item_loc_ext

,Claim_ID,sequence,locationCodeableConcept_extension_url,locationCodeableConcept_extension_valueCoding_code,locationCodeableConcept_extension_valueCoding_system,locationCodeableConcept_extension_valueCoding_display,locationCodeableConcept_extension_valueIdentifier_system,locationCodeableConcept_extension_valueIdentifier_value
0,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,IL,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN
1,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,618344509,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN
2,carrier-27286904395,1,https://bluebutton.cms.gov/resources/variables...,99,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN
3,carrier-27286904395,2,https://bluebutton.cms.gov/resources/variables...,IL,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN
4,carrier-27286904395,2,https://bluebutton.cms.gov/resources/variables...,618344509,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
76429,outpatient-9519284917,1,NaN,NaN,NaN,NaN,NaN,NaN
76430,outpatient-9519284917,2,NaN,NaN,NaN,NaN,NaN,NaN
76431,outpatient-9519284917,3,NaN,NaN,NaN,NaN,NaN,NaN
76432,outpatient-9623755765,1,NaN,NaN,NaN,NaN,NaN,NaN
76433,outpatient-9623755765,2,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
eob_df_item_loc_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76434 entries, 0 to 76433
Data columns (total 7 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Claim_ID                                                  76434 non-null  object
 1   locationCodeableConcept_extension_url                     57986 non-null  object
 2   locationCodeableConcept_extension_valueCoding_code        50082 non-null  object
 3   locationCodeableConcept_extension_valueCoding_system      50082 non-null  object
 4   locationCodeableConcept_extension_valueCoding_display     1683 non-null   object
 5   locationCodeableConcept_extension_valueIdentifier_system  7904 non-null   object
 6   locationCodeableConcept_extension_valueIdentifier_value   7904 non-null   object
dtypes: object(7)
memory usage: 4.1+ MB

In [ ]:
eob_basetable = eob_df.explode('facility_extension')
eob_basetable = eob_basetable.explode('billablePeriod_extension')
eob_basetable = json_normalize(
    eob_basetable.to_dict(orient='records')
)
eob_basetable = eob_basetable.rename(columns={
    'id': 'Claim_ID',
    'facility_extension.valueCoding.code': 'facility_Code_ext',
    'facility_extension.valueCoding.display': 'facility_Display',
    'billablePeriod_extension.valueCoding.code': 'adjustment_code',
    'billablePeriod_extension.valueCoding.display': 'adjustment_type'
})
eob_basetable.columns = eob_basetable.columns.str.replace('.', '_')
base_columns = [
    'Claim_ID', 
    'Patient_ID',
    'disposition',
    'created',
    'outcome',
    'resourceType',
    'status',
    'use',
    'billablePeriod_start',
    'billablePeriod_end',
    'adjustment_type',
    'adjustment_code',
    'insurer_identifier_value',
    'meta_lastUpdated',
    'payment_amount_currency',
    'payment_amount_value',
    'payment_date',
    'provider_identifier_system',
    'provider_identifier_value',
    'provider_reference',
    'provider_display',
    'referral_display',
    'referral_identifier_value',
    'facility_identifier_value',
    'facility_Code_ext',
    'facility_Display',
    'subType_text',
]
eob_basetable = eob_basetable.reindex(columns=base_columns)
eob_basetable

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,facility_extension_url,facility_Code_ext,facility_Display,facility_extension_valueCoding_system,billablePeriod_extension_url,adjustment_code,adjustment_type,billablePeriod_extension_valueCoding_system
Claim_ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient_ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disposition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
outcome,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resourceType,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
use,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
billablePeriod_start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
billablePeriod_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adjustment_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adjustment_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insurer_identifier_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
meta_lastUpdated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_amount_currency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_amount_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
provider_identifier_system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
provider_identifier_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
provider_reference,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
provider_display,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
referral_display,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
referral_identifier_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
facility_identifier_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
facility_Code_ext,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
facility_Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subType_text,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
eob_df_item_ext= eob_df_item_ext[['Claim_ID', 'extension.url',
       'extension.valueCoding.code', 'extension.valueCoding.system',
       'locationCodeableConcept.extension.url',
       'locationCodeableConcept.extension.valueCoding.code',
       'locationCodeableConcept.extension.valueCoding.system',
       'extension.valueQuantity.value', 'extension.valueCoding.display',
       'locationCodeableConcept.extension.valueCoding.display',
       'locationCodeableConcept.extension.valueIdentifier.system',
       'locationCodeableConcept.extension.valueIdentifier.value',
       'extension.valueIdentifier.system', 'extension.valueIdentifier.value',
       'extension.valueQuantity.code', 'extension.valueQuantity.system',
       'extension.valueQuantity.unit']]
eob_df_item_ext.columns = eob_df_item_ext.columns.str.replace('.', '_')
eob_df_item_ext

,Claim_ID,extension_url,extension_valueCoding_code,extension_valueCoding_system,locationCodeableConcept_extension_url,locationCodeableConcept_extension_valueCoding_code,locationCodeableConcept_extension_valueCoding_system,extension_valueQuantity_value,extension_valueCoding_display,locationCodeableConcept_extension_valueCoding_display,locationCodeableConcept_extension_valueIdentifier_system,locationCodeableConcept_extension_valueIdentifier_value,extension_valueIdentifier_system,extension_valueIdentifier_value,extension_valueQuantity_code,extension_valueQuantity_system,extension_valueQuantity_unit
0,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,361924025,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,IL,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,361924025,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,618344509,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,361924025,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,99,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,IL,https://bluebutton.cms.gov/resources/variables...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,618344509,https://bluebutton.cms.gov/resources/variables...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428166,outpatient-9519284917,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428167,outpatient-9519284917,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428168,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428169,outpatient-9623755765,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428170,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
eob_df_item_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428171 entries, 0 to 428170
Data columns (total 17 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Claim_ID                                                  428171 non-null  object
 1   extension.url                                             419872 non-null  object
 2   extension.valueCoding.code                                348112 non-null  object
 3   extension.valueCoding.system                              348112 non-null  object
 4   locationCodeableConcept.extension.url                     409723 non-null  object
 5   locationCodeableConcept.extension.valueCoding.code        354365 non-null  object
 6   locationCodeableConcept.extension.valueCoding.system      354365 non-null  object
 7   extension.valueQuantity.value                             70296 non-null   float64
 8   extension.valueCoding.display                             232140 non-null  object
 9   locationCodeableConcept.extension.valueCoding.display     11820 non-null   object
 10  locationCodeableConcept.extension.valueIdentifier.system  55358 non-null   object
 11  locationCodeableConcept.extension.valueIdentifier.value   55358 non-null   object
 12  extension.valueIdentifier.system                          1464 non-null    object
 13  extension.valueIdentifier.value                           1464 non-null    object
 14  extension.valueQuantity.code                              1464 non-null    object
 15  extension.valueQuantity.system                            1464 non-null    object
 16  extension.valueQuantity.unit                              1464 non-null    object
dtypes: float64(1), object(16)
memory usage: 55.5+ MB

In [124]:
eob_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16851 entries, 0 to 16850
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   benefitBalance                   10208 non-null  object
 1   careTeam                         16851 non-null  object
 2   created                          16851 non-null  object
 3   diagnosis                        10208 non-null  object
 4   disposition                      8554 non-null   object
 5   extension                        10208 non-null  object
 6   Claim_ID                         16851 non-null  object
 7   identifier                       16851 non-null  object
 8   insurance                        16851 non-null  object
 9   item                             16851 non-null  object
 10  outcome                          16851 non-null  object
 11  resourceType                     16851 non-null  object
 12  status                           16851 non-null  object
 13  supportingInfo                   16851 non-null  object
 14  total                            16851 non-null  object
 15  use                              16851 non-null  object
 16  billablePeriod_end               16851 non-null  object
 17  billablePeriod_start             16851 non-null  object
 18  insurer_identifier_value         16851 non-null  object
 19  meta_lastUpdated                 16851 non-null  object
 20  meta_profile                     16851 non-null  object
 21  Patient_ID                       16851 non-null  object
 22  payment_amount_currency          10208 non-null  object
 23  payment_amount_value             10208 non-null  float64
 24  provider_identifier_system       15197 non-null  object
 25  provider_identifier_value        15197 non-null  object
 26  type_coding                      16851 non-null  object
 27  referral_display                 7432 non-null   object
 28  referral_identifier_type_coding  7480 non-null   object
 29  referral_identifier_value        7480 non-null   object
 30  provider_display                 698 non-null    object
 31  provider_type                    698 non-null    object
 32  facility_display                 6600 non-null   object
 33  facility_extension               8297 non-null   object
 34  facility_identifier_type_coding  6643 non-null   object
 35  facility_identifier_value        6643 non-null   object
 36  payment_date                     984 non-null    object
 37  contained                        1656 non-null   object
 38  billablePeriod_extension         1623 non-null   object
 39  provider_reference               1654 non-null   object
 40  subType_coding                   1654 non-null   object
 41  subType_text                     1654 non-null   object
 42  procedure                        52 non-null     object
dtypes: float64(1), object(42)
memory usage: 5.5+ MB

In [5]:
eob_df_billableperiod_ext = eob_df.explode('billablePeriod_extension')

eob_df_billableperiod_ext = json_normalize(eob_df_billableperiod_ext.to_dict(orient='records'))

eob_df_billableperiod_ext

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,billablePeriod_extension.url,billablePeriod_extension.valueCoding.code,billablePeriod_extension.valueCoding.display,billablePeriod_extension.valueCoding.system
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545891,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2020-01-09,2020-01-09,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,164.60,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27396860372,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 390.2...",claim,2020-01-23,2020-01-23,CMS,2020-03-01T04:45:59.805+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,96.30,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'TROY DALE FOSTER D....,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27548148011,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 662.9...",claim,2020-01-30,2020-01-30,CMS,2020-04-12T22:53:20.402+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,111.94,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",TROY DALE FOSTER D.O.,"[{'code': 'npi', 'display': 'National Provider...",1134415169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9174161667,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 703},...",claim,2025-09-08,2025-09-08,CMS,2025-09-26T16:54:02.790+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
16847,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. PAUL R BRADLEY ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710749,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 375},...",claim,2025-10-01,2025-10-01,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
16848,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'SNEHAL SHRIVASTAVA ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710750,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 8}, '...",claim,2025-10-13,2025-10-13,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,7.84,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
16849,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
16850,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...

In [4]:
eob_df_billableperiod_ext = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='billablePeriod_extension',
    meta= 'Claim_ID'
)

eob_df_billableperiod_ext

,url,valueCoding.code,valueCoding.display,valueCoding.system,Claim_ID
0,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-5684894761
1,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-5697926656
2,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-5708263442
3,https://bluebutton.cms.gov/resources/variables...,5,Debit adjustment,https://bluebutton.cms.gov/resources/variables...,outpatient-5760565014
4,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-5792729936
...,...,...,...,...,...
1618,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-9174161667
1619,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-9212710749
1620,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-9212710750
1621,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-9519284917
1622,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...,outpatient-9623755765

In [7]:
# Safely explode
eob_basetable = eob_df.explode('facility_extension')
eob_basetable = eob_basetable.explode('billablePeriod_extension')
# Normalize
eob_basetable = json_normalize(
    eob_basetable.to_dict(orient='records')
)
# Rename correctly
eob_basetable = eob_basetable.rename(columns={
    'id': 'Claim_ID',
    'facility_extension.valueCoding.code': 'facility_Code_ext',
    'facility_extension.valueCoding.display': 'facility_Display',
    'billablePeriod_extension.valueCoding.display': 'adjustment_type',
    'billablePeriod_extension.valueCoding.code': 'adjustment_code'
})

# Ensure all columns exist
#for col in base_columns:
#    if col not in eob_basetable.columns:
#        eob_basetable[col] = None
# Select only needed columns
#
eob_basetable.columns = eob_basetable.columns.str.replace('.', '_')
base_columns = [
    'Claim_ID', 
    'Patient_ID',
    'disposition',
    'created',
    'outcome',
    'resourceType',
    'status',
    'use',
    'billablePeriod_start',
    'billablePeriod_end',
    'adjustment_type',
    'adjustment_code',
    'insurer_identifier_value',
    'meta_lastUpdated',
    'payment_amount_currency',
    'payment_amount_value',
    'payment_date',
    'provider_identifier_system',
    'provider_identifier_value',
    'provider_reference',
    'provider_display',
    'referral_display',
    'referral_identifier_value',
    'facility_identifier_value',
    'facility_Code_ext',
    'facility_Display',
    'subType_text',
]
eob_basetable = eob_basetable[base_columns]
eob_basetable

,Claim_ID,Patient_ID,disposition,created,outcome,resourceType,status,use,billablePeriod_start,billablePeriod_end,adjustment_type,adjustment_code,insurer_identifier_value,meta_lastUpdated,payment_amount_currency,payment_amount_value,payment_date,provider_identifier_system,provider_identifier_value,provider_reference,provider_display,referral_display,referral_identifier_value,facility_identifier_value,facility_Code_ext,facility_Display,subType_text
0,carrier-27286904395,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2019-12-27,2019-12-27,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,64.42,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,carrier-27334545890,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-10,2020-01-10,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
2,carrier-27334545891,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-09,2020-01-09,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,164.60,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
3,carrier-27396860372,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-23,2020-01-23,NaN,NaN,CMS,2020-03-01T04:45:59.805+00:00,USD,96.30,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
4,carrier-27548148011,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-30,2020-01-30,NaN,NaN,CMS,2020-04-12T22:53:20.402+00:00,USD,111.94,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,TROY DALE FOSTER D.O.,1134415169,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,outpatient-9174161667,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-09-08,2025-09-08,Final bill,3,CMS,2025-09-26T16:54:02.790+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16847,outpatient-9212710749,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-10-01,2025-10-01,Final bill,3,CMS,2025-10-31T16:28:56.430+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16848,outpatient-9212710750,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-10-13,2025-10-13,Final bill,3,CMS,2025-10-31T16:28:56.430+00:00,USD,7.84,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16849,outpatient-9519284917,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-12-22,2025-12-22,Final bill,3,CMS,2026-01-16T16:42:31.654+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16850,outpatient-9623755765,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2026-01-12,2026-01-12,Final bill,3,CMS,2026-01-30T17:06:01.301+00:00,USD,104.33,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient

In [125]:
eob_basetable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16851 entries, 0 to 16850
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Claim_ID                    16851 non-null  object
 1   Patient_ID                  16851 non-null  object
 2   disposition                 8554 non-null   object
 3   created                     16851 non-null  object
 4   outcome                     16851 non-null  object
 5   resourceType                16851 non-null  object
 6   status                      16851 non-null  object
 7   use                         16851 non-null  object
 8   billablePeriod_start        16851 non-null  object
 9   billablePeriod_end          16851 non-null  object
 10  insurer_identifier_value    16851 non-null  object
 11  meta_lastUpdated            16851 non-null  object
 12  payment_amount_currency     10208 non-null  object
 13  payment_amount_value        10208 non-null  float64
 14  payment_date                984 non-null    object
 15  provider_identifier_system  15197 non-null  object
 16  provider_identifier_value   15197 non-null  object
 17  provider_reference          1654 non-null   object
 18  provider_display            698 non-null    object
 19  referral_display            7432 non-null   object
 20  referral_identifier_value   7480 non-null   object
 21  facility_identifier_value   6643 non-null   object
 22  facility_Code_ext           8297 non-null   object
 23  facility_Display            8297 non-null   object
 24  subType_text                1654 non-null   object
dtypes: float64(1), object(24)
memory usage: 3.2+ MB

In [105]:
eob_df_facility_ext = eob_df.explode('facility_extension')
eob_df_facility_ext = json_normalize(eob_df_facility_ext.to_dict(orient='records'),meta = [col for col in eob_df.columns if col != 'facility_extension'])
eob_df_facility_ext

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,identifier,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,facility_extension.url,facility_extension.valueCoding.code,facility_extension.valueCoding.display,facility_extension.valueCoding.system
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545891,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2020-01-09,2020-01-09,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,164.60,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27396860372,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 390.2...",claim,2020-01-23,2020-01-23,CMS,2020-03-01T04:45:59.805+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,96.30,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'TROY DALE FOSTER D....,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27548148011,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 662.9...",claim,2020-01-30,2020-01-30,CMS,2020-04-12T22:53:20.402+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,111.94,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",TROY DALE FOSTER D.O.,"[{'code': 'npi', 'display': 'National Provider...",1134415169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9174161667,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 703},...",claim,2025-09-08,2025-09-08,CMS,2025-09-26T16:54:02.790+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...
16847,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'DR. PAUL R BRADLEY ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710749,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 375},...",claim,2025-10-01,2025-10-01,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...
16848,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'SNEHAL SHRIVASTAVA ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710750,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 8}, '...",claim,2025-10-13,2025-10-13,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,7.84,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...
16849,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...
16850,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'system': 'https://bluebutton.cms.gov/resour...,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",[{'url': 'https://bluebutton.cms.gov/resources...,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...

In [41]:
eob_df_item_ext = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta='Claim_ID'
)
eob_df_item_ext = json_normalize(
    eob_df_item_ext.to_dict(orient='records'),
    record_path='extension',
    meta = ['Claim_ID', 'locationCodeableConcept.extension', 'productOrService.extension', 'revenue.extension']
)
eob_df_item_ext = json_normalize(
    eob_df_item_ext.to_dict(orient='records'),
    record_path='locationCodeableConcept.extension',
    meta = [col for col in eob_df_item_ext.columns if col != 'locationCodeableConcept.extension'],
    record_prefix= 'loc_'
)

eob_df_item_ext.columns = eob_df_item_ext.columns.str.replace('.', '_')
eob_df_item_ext = eob_df_item_ext[['Claim_ID'] + [c for c in eob_df_item_ext.columns if c != 'Claim_ID']]
eob_df_item_ext.drop(columns= ['revenue_extension', 'productOrService_extension'], inplace = True)
eob_df_item_ext

,Claim_ID,loc_url,loc_valueCoding_code,loc_valueCoding_system,loc_valueIdentifier_system,loc_valueIdentifier_value,loc_valueCoding_display,url,valueCoding_code,valueCoding_system,valueQuantity_value,valueCoding_display,valueIdentifier_system,valueIdentifier_value,valueQuantity_code,valueQuantity_system,valueQuantity_unit
0,carrier-20897811241,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,carrier-20897811241,https://bluebutton.cms.gov/resources/variables...,752302544,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,carrier-20897811241,https://bluebutton.cms.gov/resources/variables...,00,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,carrier-20897811241,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0480381,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,carrier-20897811241,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457849,carrier-34683243735,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0659663,NaN,https://bluebutton.cms.gov/resources/variables...,A,https://bluebutton.cms.gov/resources/variables...,NaN,Allowed,NaN,NaN,NaN,NaN,NaN
457850,carrier-34683243735,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN
457851,carrier-34683243735,https://bluebutton.cms.gov/resources/variables...,755015100,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN
457852,carrier-34683243735,https://bluebutton.cms.gov/resources/variables...,99,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN
457853,carrier-34683243735,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0659663,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN

In [40]:
eob_df_item_ext

,loc_url,loc_valueCoding_code,loc_valueCoding_system,loc_valueIdentifier_system,loc_valueIdentifier_value,loc_valueCoding_display,url,valueCoding_code,valueCoding_system,valueQuantity_value,valueCoding_display,valueIdentifier_system,valueIdentifier_value,valueQuantity_code,valueQuantity_system,valueQuantity_unit,Claim_ID,productOrService_extension,revenue_extension
0,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
1,https://bluebutton.cms.gov/resources/variables...,752302544,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
2,https://bluebutton.cms.gov/resources/variables...,00,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
3,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0480381,NaN,https://bluebutton.cms.gov/resources/variables...,840611484,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
4,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457849,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0659663,NaN,https://bluebutton.cms.gov/resources/variables...,A,https://bluebutton.cms.gov/resources/variables...,NaN,Allowed,NaN,NaN,NaN,NaN,NaN,carrier-34683243735,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
457850,https://bluebutton.cms.gov/resources/variables...,TX,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN,carrier-34683243735,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
457851,https://bluebutton.cms.gov/resources/variables...,755015100,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN,carrier-34683243735,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
457852,https://bluebutton.cms.gov/resources/variables...,99,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN,carrier-34683243735,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN
457853,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,45D0659663,NaN,https://bluebutton.cms.gov/resources/variables...,0,https://bluebutton.cms.gov/resources/variables...,NaN,Service Subject to Deductible,NaN,NaN,NaN,NaN,NaN,carrier-34683243735,[{'url': 'http://hl7.org/fhir/StructureDefinit...,NaN

In [38]:
eob_df_item_ext.info()

<class 'pandas.DataFrame'>
RangeIndex: 457854 entries, 0 to 457853
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   product_url                  457854 non-null  str
 1   product_valueCoding.code     457854 non-null  str
 2   product_valueCoding.display  457854 non-null  str
 3   product_valueCoding.system   457854 non-null  str
 4   loc_url                      457854 non-null  str
 5   loc_valueCoding.code         386627 non-null  str
 6   loc_valueCoding.system       386627 non-null  str
 7   loc_valueIdentifier.system   71227 non-null   str
 8   loc_valueIdentifier.value    71227 non-null   str
 9   loc_valueCoding.display      9288 non-null    str
 10  url                          457854 non-null  str
 11  valueCoding.code             390006 non-null  str
 12  valueCoding.system           390006 non-null  str
 13  valueQuantity.value          66726 non-null   object
 14  valueCoding.display          260220 non-null  str
 15  valueIdentifier.system       1122 non-null    str
 16  valueIdentifier.value        1122 non-null    str
 17  valueQuantity.code           1122 non-null    str
 18  valueQuantity.system         1122 non-null    str
 19  valueQuantity.unit           1122 non-null    str
 20  Claim_ID                     457854 non-null  str
 21  revenue.extension            0 non-null       object
dtypes: object(2), str(20)
memory usage: 76.8+ MB

In [17]:
eob_df_type = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='type_coding',
    meta='Claim_ID'
)
eob_df_type.rename(columns = {
    'code': 'clm_type_cd',
}, inplace= True)
eob_df_type = eob_df_type[['Claim_ID', 'clm_type_cd', 'display', 'system']]
eob_df_type = eob_df_type[eob_df_type['system']=='https://bluebutton.cms.gov/resources/variables/nch_clm_type_cd']
eob_df_type = eob_df_type.reset_index(drop = True)
eob_df_type

,Claim_ID,clm_type_cd,display,system
0,carrier-20897811241,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
1,carrier-20944329733,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
2,carrier-21106403489,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
3,carrier-21155373512,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
4,carrier-21200601242,71,"Local carrier non-durable medical equipment, p...",https://bluebutton.cms.gov/resources/variables...
...,...,...,...,...
10447,outpatient-8312279482,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...
10448,outpatient-8329521415,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...
10449,outpatient-8468545509,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...
10450,outpatient-8497385923,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...
10451,outpatient-9624565892,40,Hospital Outpatient claim,https://bluebutton.cms.gov/resources/variables...

In [ ]:
def eob_contained(eob_df, file):
    if 'contained' in eob_df.columns:        
        eob_df_contained = json_normalize(
            eob_df.to_dict(orient='records'),
            record_path='contained',
            meta = 'Claim_ID'
        )
        eob_df_contained_identifier = json_normalize(
            eob_df_contained.to_dict(orient= 'records'),
            record_path='identifier',
            meta = [col for col in eob_df_contained.columns if col != 'identifier']
        )
        eob_df_contained_identifier = json_normalize(
            eob_df_contained_identifier.to_dict(orient= 'records'),
            record_path='type.coding',
            meta = [col for col in eob_df_contained_identifier.columns if col != 'type.coding'],
            record_prefix='type_'
        )
        eob_df_contained_identifier = eob_df_contained_identifier.reset_index(drop = True)
        eob_df_contained_identifier.rename(columns = {'value':'NPI'}, inplace = True)
        eob_df_contained_identifier = eob_df_contained_identifier[['Claim_ID', 'type_code', 'NPI', 'active', 'name', 'resourceType']].copy()
        eob_df_contained_identifier['bcda_extract_date'] = pd.Timestamp.today()
        eob_df_contained_identifier['bcda_file'] = file.name
        eob_df_contained_identifier['extract_from'] = extract_from
        eob_df_contained_identifier['extract_to'] = extract_to
    else:
        eob_df_contained_identifier= pd.DataFrame(columns = [
            'Claim_ID',
            'type_code',
            'NPI',
            'active',
            'name',
            'resourceType',
            'bcda_extract_date',
            'bcda_file',
            'extract_from',
            'extract_to'
        ])
    return eob_df_contained_identifier

In [19]:
eob_df_contained = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='contained',
    meta = 'Claim_ID'
)
eob_df_contained = eob_df_contained.explode('identifier')

eob_df_contained = json_normalize(
    eob_df_contained.to_dict(orient='records')
)
eob_df_contained = eob_df_contained.explode('identifier.type.coding')
eob_df_contained = json_normalize(
    eob_df_contained.to_dict(orient='records')
)
#if 'code.coding' in eob_df_contained.columns:
eob_df_contained = eob_df_contained.explode('code.coding')

eob_df_contained = json_normalize(
    eob_df_contained.to_dict(orient='records')
)
eob_df_contained.rename(columns = {
    'valueQuantity.value': 'results',
    'code.coding.code': 'test_cd',
    'code.coding.display': 'test_display'
})
eob_df_contained.rename(columns = {'identifier.value':'NPI', 'identifier.type.coding.code': 'type_code'}, inplace = True)

#cols = [
#    'Claim_ID',
#    'id',
#    'type_code',
#    'NPI', 
#    'active', 
#    'name', 
#    'test_cd',
#    'test_display',
#    'results',
#    'resourceType'
#]
#eob_df_contained = eob_df_contained.reset_index(drop = True)
#eob_df_contained = eob_df_contained.reindex(columns = cols)
eob_df_contained

,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID,NPI,identifier.system,identifier,type_code,identifier.type.coding.system,identifier.type.coding,code.coding.code,code.coding.display,code.coding.system
0,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN,NaN,NaN,NaN
1,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761,1346570710,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
2,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN,NaN,NaN,NaN
3,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656,1346570710,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
4,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5708263442,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710750,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
3306,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917,450032,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN,NaN,NaN,NaN
3307,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN
3308,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765,450032,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN,NaN,NaN,NaN
3309,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN

In [16]:
eob_df_contained = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='contained',
    meta = 'Claim_ID'
)

eob_df_contained = eob_df_contained.explode('identifier')


eob_df_contained = json_normalize(
    eob_df_contained.to_dict(orient='records')
)
eob_df_contained = eob_df_contained.explode('identifier.type.coding')

eob_df_contained = json_normalize(
    eob_df_contained.to_dict(orient='records')
)

eob_df_contained

,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID,identifier.value,identifier.system,identifier,identifier.type.coding.code,identifier.type.coding.system,identifier.type.coding
0,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN
1,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761,1346570710,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN
2,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN
3,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656,1346570710,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN
4,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5708263442,670067,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710750,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN
3306,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917,450032,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN
3307,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN
3308,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765,450032,NaN,NaN,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,NaN
3309,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765,1124092036,http://hl7.org/fhir/sid/us-npi,NaN,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN

In [20]:
eob_df_contained[eob_df_contained['code.coding.code'].notna()]

,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID,NPI,identifier.system,identifier,type_code,identifier.type.coding.system,identifier.type.coding,code.coding.code,code.coding.display,code.coding.system
878,NaN,line-observation-2,NaN,Observation,NaN,unknown,NaN,35.2,carrier-27090497792,NaN,NaN,NaN,NaN,NaN,NaN,R2,Hematocrit Test,https://bluebutton.cms.gov/resources/variables...
879,NaN,line-observation-2,NaN,Observation,NaN,unknown,NaN,35.2,carrier-27140086004,NaN,NaN,NaN,NaN,NaN,NaN,R2,Hematocrit Test,https://bluebutton.cms.gov/resources/variables...

In [ ]:
eob_df_contained = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='contained',
    meta = 'Claim_ID'
)
eob_df_contained_identifier = json_normalize(
    eob_df_contained.to_dict(orient= 'records'),
    record_path='identifier',
    meta = [col for col in eob_df_contained.columns if col != 'identifier']
)
eob_df_contained_identifier = eob_df_contained_identifier[eob_df_contained_identifier['system'] == 'http://hl7.org/fhir/sid/us-npi']
eob_df_contained_identifier = eob_df_contained_identifier.reset_index(drop = True)
#eob_df_contained_identifier.drop(columns=['status', 'code.coding', 'valueQuantity.value','meta.profile', 'type.coding', 'system', 'id'], inplace = True)
eob_df_contained_identifier.rename(columns = {'value':'NPI'}, inplace = True)
#eob_df_contained_identifier = eob_df_contained_identifier[['Claim_ID', 'NPI', 'active', 'name', 'resourceType']]
eob_df_contained_identifier

,NPI,type.coding,system,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID
0,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761
1,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656
2,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5708263442
3,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5760565014
4,1124076401,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,DECATUR HOSPITAL AUTHORITY,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5792729936
...,...,...,...,...,...,...,...,...,...,...,...,...
1649,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9174161667
1650,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710749
1651,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710750
1652,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917
1653,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765

In [25]:
eob_df_contained = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='contained',
    meta = 'Claim_ID'
)
eob_df_contained_identifier = json_normalize(
    eob_df_contained.to_dict(orient= 'records'),
    record_path='identifier',
    meta = [col for col in eob_df_contained.columns if col != 'identifier']
)
eob_df_contained_identifier

,value,type.coding,system,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID
0,670067,"[{'code': 'PRN', 'system': 'http://terminology...",NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761
1,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761
2,670067,"[{'code': 'PRN', 'system': 'http://terminology...",NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656
3,1346570710,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656
4,670067,"[{'code': 'PRN', 'system': 'http://terminology...",NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5708263442
...,...,...,...,...,...,...,...,...,...,...,...,...
3303,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710750
3304,450032,"[{'code': 'PRN', 'system': 'http://terminology...",NaN,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917
3305,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917
3306,450032,"[{'code': 'PRN', 'system': 'http://terminology...",NaN,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765
3307,1124092036,"[{'code': 'npi', 'system': 'http://hl7.org/fhi...",http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765

In [27]:
eob_df_contained_identifier_type = json_normalize(
    eob_df_contained_identifier.to_dict(orient='records'),
    record_path='type.coding',
    meta=[col for col in eob_df_contained_identifier.columns if col != 'type.coding'],
    record_prefix='type_'
)
eob_df_contained_identifier_type

,type_code,type_system,value,system,active,id,name,resourceType,meta.profile,status,code.coding,valueQuantity.value,Claim_ID
0,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,670067,NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761
1,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1346570710,http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5684894761
2,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,670067,NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656
3,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1346570710,http://hl7.org/fhir/sid/us-npi,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5697926656
4,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,670067,NaN,True,provider-org,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-5708263442
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1124092036,http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9212710750
3304,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,450032,NaN,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917
3305,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1124092036,http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9519284917
3306,PRN,http://terminology.hl7.org/CodeSystem/v2-0203,450032,NaN,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765
3307,npi,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1124092036,http://hl7.org/fhir/sid/us-npi,True,provider-org,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,NaN,outpatient-9623755765

In [5]:
eob_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21781 entries, 0 to 21780
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   benefitBalance                   10452 non-null  object
 1   careTeam                         21780 non-null  object
 2   created                          21781 non-null  str
 3   diagnosis                        10452 non-null  object
 4   disposition                      8645 non-null   str
 5   extension                        10452 non-null  object
 6   Claim_ID                         21781 non-null  str
 7   identifier                       21781 non-null  object
 8   insurance                        21781 non-null  object
 9   item                             21781 non-null  object
 10  outcome                          21781 non-null  str
 11  resourceType                     21781 non-null  str
 12  status                           21781 non-null  str
 13  supportingInfo                   21781 non-null  object
 14  total                            21781 non-null  object
 15  use                              21781 non-null  str
 16  billablePeriod_end               21781 non-null  str
 17  billablePeriod_start             21781 non-null  str
 18  insurer_identifier_value         21781 non-null  str
 19  meta_lastUpdated                 21781 non-null  str
 20  meta_profile                     21781 non-null  object
 21  Patient_ID                       21781 non-null  object
 22  payment_amount_currency          10452 non-null  str
 23  payment_amount_value             10452 non-null  float64
 24  provider_identifier_system       19974 non-null  str
 25  provider_identifier_value        19974 non-null  str
 26  referral_display                 7508 non-null   str
 27  referral_identifier_type_coding  7586 non-null   object
 28  referral_identifier_value        7586 non-null   str
 29  type_coding                      21781 non-null  object
 30  provider_display                 661 non-null    str
 31  provider_type                    665 non-null    str
 32  facility_display                 10905 non-null  str
 33  facility_extension               13136 non-null  object
 34  facility_identifier_type_coding  11329 non-null  object
 35  facility_identifier_value        11329 non-null  str
 36  contained                        1835 non-null   object
 37  billablePeriod_extension         1697 non-null   object
 38  provider_reference               1807 non-null   str
 39  subType_coding                   1807 non-null   object
 40  subType_text                     1807 non-null   str
 41  procedure                        44 non-null     object
 42  payment_date                     1601 non-null   str
dtypes: float64(1), object(19), str(23)
memory usage: 7.1+ MB

In [20]:
list_columns = [
    col for col in eob_df.columns
    if isinstance(eob_df[col].dropna().iloc[0], list)
]

print(list_columns)

['benefitBalance', 'careTeam', 'diagnosis', 'extension', 'identifier', 'insurance', 'item', 'supportingInfo', 'total', 'meta_profile', 'referral_identifier_type_coding', 'type_coding', 'facility_extension', 'facility_identifier_type_coding', 'contained', 'billablePeriod_extension', 'subType_coding', 'procedure']

In [ ]:

pd.set_option('display.max_columns', None)

eob_basetable = eob_df.drop(columns= list_columns)
eob_basetable

,created,disposition,Claim_ID,outcome,resourceType,status,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,referral_display,referral_identifier_value,provider_display,provider_type,facility_display,facility_identifier_value,provider_reference,subType_text,payment_date
0,2026-02-26T18:22:11+00:00,01,carrier-20897811241,complete,ExplanationOfBenefit,active,claim,2014-06-05,2014-06-05,CMS,2020-01-01T00:00:00.000+00:00,40261907,USD,10.79,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,DR. RICHARD LEROY HOZDIC II MD,1932115136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-02-26T18:22:11+00:00,01,carrier-20944329733,complete,ExplanationOfBenefit,active,claim,2014-06-05,2014-06-05,CMS,2020-01-01T00:00:00.000+00:00,40261907,USD,4.23,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,DR. RICHARD LEROY HOZDIC II MD,1932115136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-02-26T18:22:11+00:00,01,carrier-21106403489,complete,ExplanationOfBenefit,active,claim,2014-07-22,2014-07-22,CMS,2020-01-01T00:00:00.000+00:00,40261907,USD,19.06,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,DR. LLOYD MASON FRUGE MD,1275547242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-02-26T18:22:11+00:00,01,carrier-21155373512,complete,ExplanationOfBenefit,active,claim,2014-07-25,2014-07-25,CMS,2020-01-01T00:00:00.000+00:00,40261907,USD,33.18,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,DR. LLOYD MASON FRUGE MD,1275547242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-02-26T18:22:11+00:00,01,carrier-21200601242,complete,ExplanationOfBenefit,active,claim,2014-08-11,2014-08-11,CMS,2020-01-01T00:00:00.000+00:00,40261907,USD,54.58,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,DR. STANLEY CLEVELAND KNOWLES MD,1063419646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21776,2026-02-26T18:23:06+00:00,NaN,outpatient-8312279482,complete,ExplanationOfBenefit,active,claim,2024-11-04,2024-11-04,CMS,2024-11-22T16:51:56.068+00:00,387972038,USD,86.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#provider-org,Outpatient,NaN
21777,2026-02-26T18:23:06+00:00,NaN,outpatient-8329521415,complete,ExplanationOfBenefit,active,claim,2024-11-18,2024-11-18,CMS,2024-12-07T03:23:45.951+00:00,387972038,USD,9.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#provider-org,Outpatient,NaN
21778,2026-02-26T18:23:06+00:00,NaN,outpatient-8468545509,complete,ExplanationOfBenefit,active,claim,2024-12-02,2024-12-02,CMS,2024-12-27T17:15:32.288+00:00,387972038,USD,167.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#provider-org,Outpatient,NaN
21779,2026-02-26T18:23:06+00:00,NaN,outpatient-8497385923,complete,ExplanationOfBenefit,active,claim,2024-12-27,2024-12-27,CMS,2025-01-17T16:01:28.921+00:00,387972038,USD,87.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#provider-org,Outpatient,NaN
21780,2026-02-26T18:23:06+00:00,NaN,outpatient-9624565892,complete,ExplanationOfBenefit,active,claim,2025-11-03,2025-11-03,CMS,2026-01-30T17:12:06.267+00:00,387972038,USD,114.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#provider-org,Outpatient,NaN

In [26]:
if 'benefitBalance' in eob_df.columns:
    eob_benefitbalance = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='benefitBalance',
        meta = 'Claim_ID'
    )
    if 'category.coding' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('category.coding')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        #eob_benefitbalance_category_coding = json_normalize(
        #    eob_benefitbalance.to_dict(orient='records'),
        #    record_path='category.coding',
        #    meta = ['Claim_ID', 'financial']
        #)
    if 'financial' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('financial')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        eob_benefitbalance.rename(columns = {
        'financial.usedMoney.currency': 'currency_type',
        'financial.usedMoney.value' : 'amount'
        }, inplace = True)
    
        
        #eob_benefitbalance_financial = json_normalize(
        #    eob_benefitbalance_category_coding.to_dict(orient='records'),
        #    record_path='financial',
        #    meta = [col for col in eob_benefitbalance_category_coding.columns if col != 'financial']
        #)
    eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
    )
    if 'financial.type.coding' in eob_benefitbalance.columns:
        eob_benefitbalance = eob_benefitbalance.explode('financial.type.coding')
        eob_benefitbalance = json_normalize(
        eob_benefitbalance.to_dict(orient='records')
        )
        eob_benefitbalance.rename(columns = {
        'financial.type.coding.display': 'type',
        }, inplace = True)
    
    #eob_benefitbalance_financial_type_coding = json_normalize(
    #    eob_benefitbalance_financial.to_dict(orient='records'),
    #    record_path='type.coding',
    #    meta = [col for col in eob_benefitbalance_financial.columns if col != 'type.coding'],
    #    record_prefix='type_coding_'
    #)
    
    
    #if 'financial.usedUnsignedInt' not in eob_benefitbalance.columns:
    #    eob_benefitbalance['usedUnsignedInt'] = None
    if 'financial.usedUnsignedInt' in eob_benefitbalance.columns:
        eob_benefitbalance.rename(columns = {'financial.usedUnsignedInt':'usedUnsignedInt'}, inplace = True)
eob_benefitbalance

,Claim_ID,category.coding.code,category.coding.display,category.coding.system,currency_type,amount,usedUnsignedInt,financial.type.coding.code,type,financial.type.coding.system
0,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,Carrier Claim Cash Deductible Applied Amount (...,https://bluebutton.cms.gov/resources/codesyste...
1,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,64.42,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
2,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
3,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,69.99,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Submitted Charge Amount (sum...,https://bluebutton.cms.gov/resources/codesyste...
4,carrier-27286904395,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,65.73,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Allowed Charge Amount (sum o...,https://bluebutton.cms.gov/resources/codesyste...
...,...,...,...,...,...,...,...,...,...,...
55079,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,26.62,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Part B Coinsurance Amount,https://bluebutton.cms.gov/resources/codesyste...
55080,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,104.33,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
55081,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
55082,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Blood Deductible Liability Amount,https://bluebutton.cms.gov/resources/codesyste...
55083,outpatient-9623755765,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Primary Payer (if not Medicare) Claim Paid...,https://bluebutton.cms.gov/resources/codesyste...

In [23]:
eob_benefitbalance = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='benefitBalance',
    meta = 'Claim_ID'
)
eob_benefitbalance = eob_benefitbalance.explode('category.coding')
eob_benefitbalance = eob_benefitbalance.explode('financial')
eob_benefitbalance = json_normalize(
    eob_benefitbalance.to_dict(orient= 'records')
)
eob_benefitbalance = eob_benefitbalance.explode('financial.type.coding')
eob_benefitbalance = json_normalize(
    eob_benefitbalance.to_dict(orient= 'records')
)
eob_benefitbalance

,Claim_ID,financial.usedMoney.currency,financial.usedMoney.value,category.coding.code,category.coding.display,category.coding.system,financial.usedUnsignedInt,financial.type.coding.code,financial.type.coding.display,financial.type.coding.system
0,carrier-27286904395,USD,0.00,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,Carrier Claim Cash Deductible Applied Amount (...,https://bluebutton.cms.gov/resources/codesyste...
1,carrier-27286904395,USD,64.42,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
2,carrier-27286904395,USD,0.00,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Claim Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
3,carrier-27286904395,USD,69.99,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Submitted Charge Amount (sum...,https://bluebutton.cms.gov/resources/codesyste...
4,carrier-27286904395,USD,65.73,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Carrier Claim Allowed Charge Amount (sum o...,https://bluebutton.cms.gov/resources/codesyste...
...,...,...,...,...,...,...,...,...,...,...
55079,outpatient-9623755765,USD,26.62,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Part B Coinsurance Amount,https://bluebutton.cms.gov/resources/codesyste...
55080,outpatient-9623755765,USD,104.33,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Provider Payment Amount,https://bluebutton.cms.gov/resources/codesyste...
55081,outpatient-9623755765,USD,0.00,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,Claim Outpatient Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesyste...
55082,outpatient-9623755765,USD,0.00,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Beneficiary Blood Deductible Liability Amount,https://bluebutton.cms.gov/resources/codesyste...
55083,outpatient-9623755765,USD,0.00,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,NaN,https://bluebutton.cms.gov/resources/variables...,NCH Primary Payer (if not Medicare) Claim Paid...,https://bluebutton.cms.gov/resources/codesyste...

In [8]:
eob_benefitbalance = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='benefitBalance',
    meta = 'Claim_ID'
)
eob_benefitbalance

,financial,category.coding,Claim_ID
0,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",carrier-27286904395
1,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",carrier-27334545890
2,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",carrier-27334545891
3,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",carrier-27396860372
4,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",carrier-27548148011
...,...,...,...
10203,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",outpatient-9174161667
10204,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",outpatient-9212710749
10205,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",outpatient-9212710750
10206,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",outpatient-9519284917
10207,[{'type': {'coding': [{'code': 'https://bluebu...,"[{'code': '1', 'display': 'Medical Care', 'sys...",outpatient-9623755765

In [9]:
eob_benefitbalance_category_coding = json_normalize(
    eob_benefitbalance.to_dict(orient='records'),
    record_path='category.coding',
    meta = ['Claim_ID', 'financial']
)
eob_benefitbalance_category_coding

,code,display,system,Claim_ID,financial
0,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395,[{'type': {'coding': [{'code': 'https://bluebu...
1,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27334545890,[{'type': {'coding': [{'code': 'https://bluebu...
2,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27334545891,[{'type': {'coding': [{'code': 'https://bluebu...
3,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27396860372,[{'type': {'coding': [{'code': 'https://bluebu...
4,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27548148011,[{'type': {'coding': [{'code': 'https://bluebu...
...,...,...,...,...,...
10203,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9174161667,[{'type': {'coding': [{'code': 'https://bluebu...
10204,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9212710749,[{'type': {'coding': [{'code': 'https://bluebu...
10205,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9212710750,[{'type': {'coding': [{'code': 'https://bluebu...
10206,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9519284917,[{'type': {'coding': [{'code': 'https://bluebu...
10207,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765,[{'type': {'coding': [{'code': 'https://bluebu...

In [10]:
eob_benefitbalance_financial = json_normalize(
    eob_benefitbalance_category_coding.to_dict(orient='records'),
    record_path='financial',
    meta = [col for col in eob_benefitbalance_category_coding.columns if col != 'financial']
)
eob_benefitbalance_financial

,type.coding,usedMoney.currency,usedMoney.value,usedUnsignedInt,code,display,system,Claim_ID
0,[{'code': 'https://bluebutton.cms.gov/resource...,USD,0.00,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395
1,[{'code': 'https://bluebutton.cms.gov/resource...,USD,64.42,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395
2,[{'code': 'https://bluebutton.cms.gov/resource...,USD,0.00,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395
3,[{'code': 'https://bluebutton.cms.gov/resource...,USD,69.99,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395
4,[{'code': 'https://bluebutton.cms.gov/resource...,USD,65.73,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,carrier-27286904395
...,...,...,...,...,...,...,...,...
55079,[{'code': 'https://bluebutton.cms.gov/resource...,USD,26.62,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765
55080,[{'code': 'https://bluebutton.cms.gov/resource...,USD,104.33,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765
55081,[{'code': 'https://bluebutton.cms.gov/resource...,USD,0.00,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765
55082,[{'code': 'https://bluebutton.cms.gov/resource...,USD,0.00,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765
55083,[{'code': 'https://bluebutton.cms.gov/resource...,USD,0.00,NaN,1,Medical Care,http://terminology.hl7.org/CodeSystem/ex-benef...,outpatient-9623755765

In [11]:

eob_benefitbalance = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='benefitBalance',
    meta = 'Claim_ID'
)

eob_benefitbalance_category_coding = json_normalize(
    eob_benefitbalance.to_dict(orient='records'),
    record_path='category.coding',
    meta = ['Claim_ID', 'financial']
)

eob_benefitbalance_financial = json_normalize(
    eob_benefitbalance_category_coding.to_dict(orient='records'),
    record_path='financial',
    meta = [col for col in eob_benefitbalance_category_coding.columns if col != 'financial']
)

eob_benefitbalance_financial_type_coding = json_normalize(
    eob_benefitbalance_financial.to_dict(orient='records'),
    record_path='type.coding',
    meta = [col for col in eob_benefitbalance_financial.columns if col != 'type.coding'],
    record_prefix='type_coding_'
)

eob_benefitbalance_financial_type_coding.columns = eob_benefitbalance_financial_type_coding.columns.str.replace('.', '_')
eob_benefitbalance_financial_type_coding.drop(columns = ['system', 'type_coding_system', 'type_coding_code'], inplace = True)
eob_benefitbalance_financial_type_coding.rename(columns = {
    'type_coding_display': 'type',
    'usedMoney_currency': 'currency_type',
    'usedMoney_value' : 'amount'
}, inplace = True)

eob_benefitbalance_financial_type_coding = eob_benefitbalance_financial_type_coding[['Claim_ID', 'currency_type', 'amount', 'type', 'code', 'display', 'usedUnsignedInt']]
eob_benefitbalance_financial_type_coding
####################################################################################################################################################################################

,Claim_ID,currency_type,amount,type,code,display,usedUnsignedInt
0,carrier-27286904395,USD,0.0,Carrier Claim Cash Deductible Applied Amount (...,1,Medical Care,NaN
1,carrier-27286904395,USD,64.42,NCH Claim Provider Payment Amount,1,Medical Care,NaN
2,carrier-27286904395,USD,0.0,NCH Claim Payment Amount to Beneficiary,1,Medical Care,NaN
3,carrier-27286904395,USD,69.99,NCH Carrier Claim Submitted Charge Amount (sum...,1,Medical Care,NaN
4,carrier-27286904395,USD,65.73,NCH Carrier Claim Allowed Charge Amount (sum o...,1,Medical Care,NaN
...,...,...,...,...,...,...,...
55079,outpatient-9623755765,USD,26.62,NCH Beneficiary Part B Coinsurance Amount,1,Medical Care,NaN
55080,outpatient-9623755765,USD,104.33,Claim Outpatient Provider Payment Amount,1,Medical Care,NaN
55081,outpatient-9623755765,USD,0.0,Claim Outpatient Payment Amount to Beneficiary,1,Medical Care,NaN
55082,outpatient-9623755765,USD,0.0,NCH Beneficiary Blood Deductible Liability Amount,1,Medical Care,NaN
55083,outpatient-9623755765,USD,0.0,NCH Primary Payer (if not Medicare) Claim Paid...,1,Medical Care,NaN

In [236]:
eob_careteam = json_normalize(
    eob_df.to_dict(orient= 'records'),
    record_path= 'careTeam',
    meta = 'Claim_ID'
)

eob_careteam_1 = json_normalize(
    eob_careteam.to_dict(orient='records'),
    record_path= 'role.coding',
    meta= [col for col in eob_careteam.columns if col != 'role.coding']
)

eob_careteam_1 = eob_careteam_1.drop(columns= ['code', 'system', 'provider.identifier.type.coding', 'qualification.coding', 'extension'])
eob_careteam_1.rename(columns = {
    'display': 'role',
    'provider.display': 'Provider',
    'provider.identifier.value': 'NPI',
    'sequence': 'CareTeam_Sequence'
}, inplace = True)
eob_careteam_1 = eob_careteam_1[['Claim_ID', 'CareTeam_Sequence', 'Provider', 'NPI', 'role', 'responsible']]
eob_careteam_1

,Claim_ID,CareTeam_Sequence,Provider,NPI,role,responsible
0,carrier-20897811241,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,Referring,NaN
1,carrier-20897811241,2,NaN,269285YMT9,Referring,NaN
2,carrier-20897811241,3,LABORATORY CORPORATION OF AMERICA,1265418669,Performing provider,True
3,carrier-20944329733,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,Referring,NaN
4,carrier-20944329733,2,NaN,269285YMT9,Referring,NaN
...,...,...,...,...,...,...
37921,outpatient-8312279482,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37922,outpatient-8329521415,1,ARWA ALBASHAIREH MD,1760902605,Attending,NaN
37923,outpatient-8468545509,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37924,outpatient-8497385923,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37925,outpatient-9624565892,1,GULNAR PITTS APRN,1104419241,Attending,NaN

,Claim_ID,CareTeam_Sequence,Provider,NPI,role,responsible
0,carrier-20897811241,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,Referring,NaN
1,carrier-20897811241,2,NaN,269285YMT9,Referring,NaN
2,carrier-20897811241,3,LABORATORY CORPORATION OF AMERICA,1265418669,Performing provider,True
3,carrier-20944329733,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,Referring,NaN
4,carrier-20944329733,2,NaN,269285YMT9,Referring,NaN
...,...,...,...,...,...,...
37921,outpatient-8312279482,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37922,outpatient-8329521415,1,ARWA ALBASHAIREH MD,1760902605,Attending,NaN
37923,outpatient-8468545509,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37924,outpatient-8497385923,1,GULNAR PITTS APRN,1104419241,Attending,NaN
37925,outpatient-9624565892,1,GULNAR PITTS APRN,1104419241,Attending,NaN

In [110]:
eob_careteam_provider_coding_0 = eob_careteam.explode('provider.identifier.type.coding')
eob_careteam_provider_coding_0

,sequence,provider.display,provider.identifier.type.coding,provider.identifier.value,qualification.coding,role.coding,extension,responsible,Claim_ID
0,1,DR. RICHARD LEROY HOZDIC II MD,"{'code': 'npi', 'display': 'National Provider ...",1932115136,"[{'code': '207Q00000X', 'display': 'Family Med...","[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20897811241
1,2,NaN,"{'code': 'npi', 'display': 'National Provider ...",269285YMT9,NaN,"[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20897811241
2,3,LABORATORY CORPORATION OF AMERICA,"{'code': 'npi', 'display': 'National Provider ...",1265418669,"[{'code': '291U00000X', 'display': 'Clinical M...","[{'code': 'performing', 'display': 'Performing...",[{'url': 'https://bluebutton.cms.gov/resources...,True,carrier-20897811241
3,1,DR. RICHARD LEROY HOZDIC II MD,"{'code': 'npi', 'display': 'National Provider ...",1932115136,"[{'code': '207Q00000X', 'display': 'Family Med...","[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20944329733
4,2,NaN,"{'code': 'npi', 'display': 'National Provider ...",269285YMT9,NaN,"[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20944329733
...,...,...,...,...,...,...,...,...,...
37921,1,GULNAR PITTS APRN,"{'code': 'npi', 'display': 'National Provider ...",1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8312279482
37922,1,ARWA ALBASHAIREH MD,"{'code': 'npi', 'display': 'National Provider ...",1760902605,"[{'code': '207R00000X', 'display': 'Internal M...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8329521415
37923,1,GULNAR PITTS APRN,"{'code': 'npi', 'display': 'National Provider ...",1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8468545509
37924,1,GULNAR PITTS APRN,"{'code': 'npi', 'display': 'National Provider ...",1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8497385923
37925,1,GULNAR PITTS APRN,"{'code': 'npi', 'display': 'National Provider ...",1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-9624565892

In [125]:


eob_careteam_provider_coding = json_normalize(
    eob_careteam.to_dict(orient= 'records'),
    record_path= 'provider.identifier.type.coding',
    meta = [col for col in eob_careteam.columns if col != 'provider.identifier.type.coding']
)
eob_careteam_provider_coding#[eob_careteam_provider_coding['Claim_ID']== 'carrier-20897811241']

,code,display,system,sequence,provider.display,provider.identifier.value,qualification.coding,role.coding,extension,responsible,Claim_ID
0,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,"[{'code': '207Q00000X', 'display': 'Family Med...","[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20897811241
1,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,2,NaN,269285YMT9,NaN,"[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20897811241
2,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,3,LABORATORY CORPORATION OF AMERICA,1265418669,"[{'code': '291U00000X', 'display': 'Clinical M...","[{'code': 'performing', 'display': 'Performing...",[{'url': 'https://bluebutton.cms.gov/resources...,True,carrier-20897811241
3,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,"[{'code': '207Q00000X', 'display': 'Family Med...","[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20944329733
4,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,2,NaN,269285YMT9,NaN,"[{'code': 'referring', 'display': 'Referring',...",NaN,NaN,carrier-20944329733
...,...,...,...,...,...,...,...,...,...,...,...
37921,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,GULNAR PITTS APRN,1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8312279482
37922,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,ARWA ALBASHAIREH MD,1760902605,"[{'code': '207R00000X', 'display': 'Internal M...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8329521415
37923,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,GULNAR PITTS APRN,1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8468545509
37924,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,GULNAR PITTS APRN,1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-8497385923
37925,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,GULNAR PITTS APRN,1104419241,"[{'code': '363LF0000X', 'display': 'Family Nur...","[{'code': 'attending', 'display': 'Attending',...",NaN,NaN,outpatient-9624565892

In [237]:
eob_careteam_provider_coding_qual_0 = eob_careteam_provider_coding.explode('qualification.coding')

eob_careteam_provider_coding_qual = json_normalize(
    eob_careteam_provider_coding_qual_0.to_dict(orient='records'),
    meta=[col for col in eob_careteam_provider_coding_qual_0.columns if col !='qualification.coding']
)
eob_careteam_provider_coding_qual =eob_careteam_provider_coding_qual.drop(columns='qualification.coding')
eob_careteam_provider_coding_qual

,code,display,system,sequence,provider.display,provider.identifier.value,role.coding,extension,responsible,Claim_ID,qualification.coding.code,qualification.coding.display,qualification.coding.system
0,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,"[{'code': 'referring', 'display': 'Referring', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,carrier-20897811241,207Q00000X,Family Medicine Physician,http://nucc.org/provider-taxonomy
1,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,2,NaN,269285YMT9,"[{'code': 'referring', 'display': 'Referring', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,carrier-20897811241,NaN,NaN,NaN
2,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,3,LABORATORY CORPORATION OF AMERICA,1265418669,"[{'code': 'performing', 'display': 'Performing provider', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd', 'valueCoding': {'code': '5', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd', 'valueCoding': {'code': '1', 'display': 'Participating', 'system': 'https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd'}}]",True,carrier-20897811241,291U00000X,Clinical Medical Laboratory,http://nucc.org/provider-taxonomy
3,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,3,LABORATORY CORPORATION OF AMERICA,1265418669,"[{'code': 'performing', 'display': 'Performing provider', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd', 'valueCoding': {'code': '5', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd', 'valueCoding': {'code': '1', 'display': 'Participating', 'system': 'https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd'}}]",True,carrier-20897811241,69,Clinical laboratory (billing independently),https://bluebutton.cms.gov/resources/variables/prvdr_spclty
4,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,"[{'code': 'referring', 'display': 'Referring', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,carrier-20944329733,207Q00000X,Family Medicine Physician,http://nucc.org/provider-taxonomy
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46570,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,GULNAR PITTS APRN,1104419241,"[{'code': 'attending', 'display': 'Attending', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,outpatient-8312279482,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy
46571,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,ARWA ALBASHAIREH MD,1760902605,"[{'code': 'attending', 'display': 'Attending', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,outpatient-8329521415,207R00000X,Internal Medicine Physician,http://nucc.org/provider-taxonomy
46572,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,GULNAR PITTS APRN,1104419241,"[{'code': 'attending', 'display': 'Attending', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,outpatient-8468545509,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy
46573,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,GULNAR PITTS APRN,1104419241,"[{'code': 'attending', 'display': 'Attending', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,outpatient-8497385923,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy
46574,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,1,GULNAR PITTS APRN,1104419241,"[{'code': 'attending', 'display': 'Attending', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole'}]",NaN,NaN,outpatient-9624565892,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy

In [282]:
eob_careteam = json_normalize(
    eob_df.to_dict(orient= 'records'),
    record_path= 'careTeam',
    meta = 'Claim_ID'
)

eob_careteam_provider_coding = json_normalize(
    eob_careteam.to_dict(orient= 'records'),
    record_path= 'provider.identifier.type.coding',
    meta = [col for col in eob_careteam.columns if col != 'provider.identifier.type.coding']
)


eob_careteam_provider_coding_qual_0 = eob_careteam_provider_coding.explode('qualification.coding')

eob_careteam_provider_coding_qual = json_normalize(
    eob_careteam_provider_coding_qual_0.to_dict(orient='records'),
    meta=[col for col in eob_careteam_provider_coding_qual_0.columns if col !='qualification.coding']
)
eob_careteam_provider_coding_qual =eob_careteam_provider_coding_qual.drop(columns='qualification.coding')
eob_careteam_provider_coding_qual

eob_careteam_provider_coding_qual_role_0 = eob_careteam_provider_coding_qual.explode('role.coding')
eob_careteam_provider_coding_qual_role = json_normalize(
    eob_careteam_provider_coding_qual_role_0.to_dict(orient='records'),
    meta=[col for col in eob_careteam_provider_coding_qual_role_0.columns if col != 'role.coding']
)

eob_careteam_provider_coding_qual_role.columns = eob_careteam_provider_coding_qual_role.columns.str.replace('.', '_')
eob_careteam_provider_coding_qual_role = eob_careteam_provider_coding_qual_role.drop(columns = 'extension')
eob_careteam_provider_coding_qual_role.drop(columns = ['system','code' , 'display', 'qualification_coding_system','role_coding_code','role_coding_system'], inplace = True)
eob_careteam_provider_coding_qual_role.rename(columns = {
    'sequence': 'careteam_sequence',
    'qualification_coding_code': 'qualification_code',
    'qualification_coding_display': 'qualification_display',
    'role_coding_display': 'role'
}, inplace = True)
eob_careteam_provider_coding_qual_role = eob_careteam_provider_coding_qual_role[['Claim_ID', 'careteam_sequence', 'provider_identifier_value', 'qualification_code', 'qualification_display', 'role']]
eob_careteam_provider_coding_qual_role
###################################################################################################################################################

,Claim_ID,careteam_sequence,provider_identifier_value,qualification_code,qualification_display,role
0,carrier-20897811241,1,1932115136,207Q00000X,Family Medicine Physician,Referring
1,carrier-20897811241,2,269285YMT9,NaN,NaN,Referring
2,carrier-20897811241,3,1265418669,291U00000X,Clinical Medical Laboratory,Performing provider
3,carrier-20897811241,3,1265418669,69,Clinical laboratory (billing independently),Performing provider
4,carrier-20944329733,1,1932115136,207Q00000X,Family Medicine Physician,Referring
...,...,...,...,...,...,...
46570,outpatient-8312279482,1,1104419241,363LF0000X,Family Nurse Practitioner,Attending
46571,outpatient-8329521415,1,1760902605,207R00000X,Internal Medicine Physician,Attending
46572,outpatient-8468545509,1,1104419241,363LF0000X,Family Nurse Practitioner,Attending
46573,outpatient-8497385923,1,1104419241,363LF0000X,Family Nurse Practitioner,Attending
46574,outpatient-9624565892,1,1104419241,363LF0000X,Family Nurse Practitioner,Attending

In [ ]:
eob_careteam_provider_ext = eob_careteam_provider_coding_qual_role.explode('extension')
eob_careteam_provider_ext_2 = json_normalize(eob_careteam_provider_ext.to_dict(orient='records'), meta= [col for col in eob_careteam_provider_ext.columns if col != 'extension'] )
eob_careteam_provider_ext_2 = eob_careteam_provider_ext_2.drop(columns = 'extension')
eob_careteam_provider_ext_2#[eob_careteam_provider_ext_2['Claim_ID']== 'carrier-20897811241']
####################################################################################################################################################################################

,sequence,provider.display,provider.identifier.value,responsible,Claim_ID,provider.identifier.type.coding.code,provider.identifier.type.coding.display,provider.identifier.type.coding.system,qualification.coding.code,qualification.coding.display,qualification.coding.system,role.coding.code,role.coding.display,role.coding.system,extension.url,extension.valueCoding.code,extension.valueCoding.system,extension.valueCoding.display
0,1,DR. RICHARD LEROY HOZDIC II MD,1932115136,NaN,carrier-20897811241,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,207Q00000X,Family Medicine Physician,http://nucc.org/provider-taxonomy,referring,Referring,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
1,2,NaN,269285YMT9,NaN,carrier-20897811241,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,NaN,NaN,NaN,referring,Referring,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
2,3,LABORATORY CORPORATION OF AMERICA,1265418669,True,carrier-20897811241,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,291U00000X,Clinical Medical Laboratory,http://nucc.org/provider-taxonomy,performing,Performing provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd,5,https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd,NaN
3,3,LABORATORY CORPORATION OF AMERICA,1265418669,True,carrier-20897811241,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,291U00000X,Clinical Medical Laboratory,http://nucc.org/provider-taxonomy,performing,Performing provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd,1,https://bluebutton.cms.gov/resources/variables/prtcptng_ind_cd,Participating
4,3,LABORATORY CORPORATION OF AMERICA,1265418669,True,carrier-20897811241,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,69,Clinical laboratory (billing independently),https://bluebutton.cms.gov/resources/variables/prvdr_spclty,performing,Performing provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd,5,https://bluebutton.cms.gov/resources/variables/carr_line_prvdr_type_cd,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62542,1,GULNAR PITTS APRN,1104419241,NaN,outpatient-8312279482,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy,attending,Attending,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
62543,1,ARWA ALBASHAIREH MD,1760902605,NaN,outpatient-8329521415,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,207R00000X,Internal Medicine Physician,http://nucc.org/provider-taxonomy,attending,Attending,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
62544,1,GULNAR PITTS APRN,1104419241,NaN,outpatient-8468545509,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy,attending,Attending,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
62545,1,GULNAR PITTS APRN,1104419241,NaN,outpatient-8497385923,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy,attending,Attending,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN
62546,1,GULNAR PITTS APRN,1104419241,NaN,outpatient-9624565892,npi,National Provider Identifier,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,363LF0000X,Family Nurse Practitioner,http://nucc.org/provider-taxonomy,attending,Attending,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole,NaN,NaN,NaN,NaN

In [140]:
eob_df_diag =json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='diagnosis',
    meta = 'Claim_ID'
)

eob_df_diag

,sequence,type,diagnosisCodeableConcept.coding,extension,Claim_ID
0,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]","[{'code': '7881', 'display': 'DYSURIA', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-20897811241
1,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]","[{'code': '7881', 'display': 'DYSURIA', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-20944329733
2,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]","[{'code': '78900', 'display': 'ABDMNAL PAIN UNSPCF SITE', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21106403489
3,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]","[{'code': '78900', 'display': 'ABDMNAL PAIN UNSPCF SITE', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21155373512
4,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]","[{'code': '20200', 'display': 'NDLR LYM UNSP XTRNDL ORG', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21200601242
...,...,...,...,...,...
33762,2,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]","[{'code': 'E0800', 'display': 'DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'E0800', 'display': 'DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892
33763,3,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]","[{'code': 'I10', 'display': 'ESSENTIAL (PRIMARY) HYPERTENSION', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'I10', 'display': 'ESSENTIAL (PRIMARY) HYPERTENSION', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892
33764,4,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]","[{'code': 'Z794', 'display': 'LONG TERM (CURRENT) USE OF INSULIN', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'Z794', 'display': 'LONG TERM (CURRENT) USE OF INSULIN', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892
33765,5,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]","[{'code': 'Z940', 'display': 'KIDNEY TRANSPLANT STATUS', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'Z940', 'display': 'KIDNEY TRANSPLANT STATUS', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892
33766,6,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]","[{'code': 'E559', 'display': '""VITAMIN D DEFICIENCY, UNSPECIFIED""', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'E559', 'display': '""VITAMIN D DEFICIENCY, UNSPECIFIED""', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892

In [145]:
eob_df_diag_type = eob_df_diag.explode('type')

eob_df_diag_type = json_normalize(
    eob_df_diag_type.to_dict(orient='records'),
    meta='Claim_ID'
)
eob_df_diag_type = eob_df_diag_type.explode('type.coding')
eob_df_diag_type = json_normalize(
    eob_df_diag_type.to_dict(orient='records'),
    meta='Claim_ID'
)
eob_df_diag_type

,sequence,diagnosisCodeableConcept.coding,extension,Claim_ID,type.coding.code,type.coding.display,type.coding.system
0,1,"[{'code': '7881', 'display': 'DYSURIA', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-20897811241,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagnosistype
1,1,"[{'code': '7881', 'display': 'DYSURIA', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-20944329733,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagnosistype
2,1,"[{'code': '78900', 'display': 'ABDMNAL PAIN UNSPCF SITE', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21106403489,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagnosistype
3,1,"[{'code': '78900', 'display': 'ABDMNAL PAIN UNSPCF SITE', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21155373512,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagnosistype
4,1,"[{'code': '20200', 'display': 'NDLR LYM UNSP XTRNDL ORG', 'system': 'http://hl7.org/fhir/sid/icd-9-cm'}]",NaN,carrier-21200601242,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagnosistype
...,...,...,...,...,...,...,...
33762,2,"[{'code': 'E0800', 'display': 'DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'E0800', 'display': 'DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType
33763,3,"[{'code': 'I10', 'display': 'ESSENTIAL (PRIMARY) HYPERTENSION', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'I10', 'display': 'ESSENTIAL (PRIMARY) HYPERTENSION', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType
33764,4,"[{'code': 'Z794', 'display': 'LONG TERM (CURRENT) USE OF INSULIN', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'Z794', 'display': 'LONG TERM (CURRENT) USE OF INSULIN', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType
33765,5,"[{'code': 'Z940', 'display': 'KIDNEY TRANSPLANT STATUS', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'Z940', 'display': 'KIDNEY TRANSPLANT STATUS', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType
33766,6,"[{'code': 'E559', 'display': '""VITAMIN D DEFICIENCY, UNSPECIFIED""', 'system': 'http://hl7.org/fhir/sid/icd-10-cm'}, {'code': 'E559', 'display': '""VITAMIN D DEFICIENCY, UNSPECIFIED""', 'system': 'http://hl7.org/fhir/sid/icd-10'}]",NaN,outpatient-9624565892,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType

In [146]:
eob_df_diag_diagnosis = eob_df_diag.explode('diagnosisCodeableConcept.coding')

diagnosisCodeableConcept_coding = json_normalize(
    eob_df_diag_diagnosis.to_dict(orient='records'),
    meta='Claim_ID'
)
diagnosisCodeableConcept_coding

,sequence,type,extension,Claim_ID,diagnosisCodeableConcept.coding.code,diagnosisCodeableConcept.coding.display,diagnosisCodeableConcept.coding.system
0,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]",NaN,carrier-20897811241,7881,DYSURIA,http://hl7.org/fhir/sid/icd-9-cm
1,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]",NaN,carrier-20944329733,7881,DYSURIA,http://hl7.org/fhir/sid/icd-9-cm
2,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]",NaN,carrier-21106403489,78900,ABDMNAL PAIN UNSPCF SITE,http://hl7.org/fhir/sid/icd-9-cm
3,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]",NaN,carrier-21155373512,78900,ABDMNAL PAIN UNSPCF SITE,http://hl7.org/fhir/sid/icd-9-cm
4,1,"[{'coding': [{'code': 'principal', 'display': 'principal', 'system': 'http://terminology.hl7.org/CodeSystem/ex-diagnosistype'}]}]",NaN,carrier-21200601242,20200,NDLR LYM UNSP XTRNDL ORG,http://hl7.org/fhir/sid/icd-9-cm
...,...,...,...,...,...,...,...
65593,4,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]",NaN,outpatient-9624565892,Z794,LONG TERM (CURRENT) USE OF INSULIN,http://hl7.org/fhir/sid/icd-10
65594,5,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]",NaN,outpatient-9624565892,Z940,KIDNEY TRANSPLANT STATUS,http://hl7.org/fhir/sid/icd-10-cm
65595,5,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]",NaN,outpatient-9624565892,Z940,KIDNEY TRANSPLANT STATUS,http://hl7.org/fhir/sid/icd-10
65596,6,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]",NaN,outpatient-9624565892,E559,"""VITAMIN D DEFICIENCY, UNSPECIFIED""",http://hl7.org/fhir/sid/icd-10-cm
65597,6,"[{'coding': [{'code': 'other', 'display': 'Other', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimDiagnosisType'}]}]",NaN,outpatient-9624565892,E559,"""VITAMIN D DEFICIENCY, UNSPECIFIED""",http://hl7.org/fhir/sid/icd-10

In [225]:
eob_df_diag =json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='diagnosis',
    meta = 'Claim_ID'
)

eob_df_diag_diagnosis = eob_df_diag.explode('diagnosisCodeableConcept.coding')

diagnosisCodeableConcept_coding = json_normalize(
    eob_df_diag_diagnosis.to_dict(orient='records'),
    meta='Claim_ID'
)

diagnosisCodeableConcept_type = diagnosisCodeableConcept_coding.explode('type')

diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type.to_dict(orient='records'),
    meta='Claim_ID'
)
diagnosisCodeableConcept_type

diagnosisCodeableConcept_type_2 = diagnosisCodeableConcept_type.explode('type.coding')

diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type_2.to_dict(orient='records'),
    meta='Claim_ID'
)

diagnosisCodeableConcept_type.drop(columns = ['diagnosisCodeableConcept.coding.system', 'type.coding.system', 'type.coding.code', 'extension'], inplace = True)
diagnosisCodeableConcept_type.rename(columns = {
    'sequence': 'diagnosis_sequence',
    'diagnosisCodeableConcept.coding.code': 'diagnosis_code',
    'diagnosisCodeableConcept.coding.display': 'diagnosis_display',
    'type.coding.display': 'Diagnosis_Code_Type'
}, inplace = True)
diagnosisCodeableConcept_type = diagnosisCodeableConcept_type[['Claim_ID', 'diagnosis_sequence', 'diagnosis_code', 'diagnosis_display']]
diagnosisCodeableConcept_type=diagnosisCodeableConcept_type.drop_duplicates()
diagnosisCodeableConcept_type
####################################################################################################################################################################################

,Claim_ID,diagnosis_sequence,diagnosis_code,diagnosis_display
0,carrier-20897811241,1,7881,DYSURIA
1,carrier-20944329733,1,7881,DYSURIA
2,carrier-21106403489,1,78900,ABDMNAL PAIN UNSPCF SITE
3,carrier-21155373512,1,78900,ABDMNAL PAIN UNSPCF SITE
4,carrier-21200601242,1,20200,NDLR LYM UNSP XTRNDL ORG
...,...,...,...,...
65588,outpatient-9624565892,2,E0800,DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA
65590,outpatient-9624565892,3,I10,ESSENTIAL (PRIMARY) HYPERTENSION
65592,outpatient-9624565892,4,Z794,LONG TERM (CURRENT) USE OF INSULIN
65594,outpatient-9624565892,5,Z940,KIDNEY TRANSPLANT STATUS
65596,outpatient-9624565892,6,E559,"""VITAMIN D DEFICIENCY, UNSPECIFIED"""

In [226]:
diagnosisCodeableConcept_type[diagnosisCodeableConcept_type['Claim_ID']== 'outpatient-9624565892']

,Claim_ID,diagnosis_sequence,diagnosis_code,diagnosis_display
65586,outpatient-9624565892,1,D849,"""IMMUNODEFICIENCY, UNSPECIFIED"""
65588,outpatient-9624565892,2,E0800,DIAB D/T UNDRL COND W HYPROSM W/O NONKET HYPRGLY-HYPROS COMA
65590,outpatient-9624565892,3,I10,ESSENTIAL (PRIMARY) HYPERTENSION
65592,outpatient-9624565892,4,Z794,LONG TERM (CURRENT) USE OF INSULIN
65594,outpatient-9624565892,5,Z940,KIDNEY TRANSPLANT STATUS
65596,outpatient-9624565892,6,E559,"""VITAMIN D DEFICIENCY, UNSPECIFIED"""

In [11]:
eob_df_ext = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='extension',
    meta = 'Claim_ID'
)
eob_df_ext[eob_df_ext['Claim_ID'] == 'outpatient-8329521415']
#eob_df_ext.info()
####################################################################################################################################################################################

,url,valueCoding.code,valueCoding.display,valueCoding.system,valueIdentifier.system,valueIdentifier.value,valueDate,valueMoney.currency,valueMoney.value,valueQuantity.value,Claim_ID
65663,https://bluebutton.cms.gov/resources/variables...,W,Part B institutional claim record (outpatient ...,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-8329521415
65664,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,22433000959404ARA,NaN,NaN,NaN,NaN,outpatient-8329521415
65665,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,2024-11-25,NaN,NaN,NaN,outpatient-8329521415
65666,https://bluebutton.cms.gov/resources/variables...,3,NaN,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-8329521415
65667,https://bluebutton.cms.gov/resources/variables...,07101,NaN,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-8329521415

In [157]:
eob_df_idnetifier = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='identifier',
    meta = 'Claim_ID'
)
eob_df_idnetifier

,system,value,type.coding,Claim_ID
0,https://bluebutton.cms.gov/resources/variables/clm_id,20897811241,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",carrier-20897811241
1,https://bluebutton.cms.gov/resources/identifier/claim-group,1651072082,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",carrier-20897811241
2,https://bluebutton.cms.gov/resources/variables/clm_id,20944329733,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",carrier-20944329733
3,https://bluebutton.cms.gov/resources/identifier/claim-group,83652425,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",carrier-20944329733
4,https://bluebutton.cms.gov/resources/variables/clm_id,21106403489,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",carrier-21106403489
...,...,...,...,...
54886,https://bluebutton.cms.gov/resources/identifier/claim-group,34235871497,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",outpatient-8468545509
54887,https://bluebutton.cms.gov/resources/variables/clm_id,8497385923,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",outpatient-8497385923
54888,https://bluebutton.cms.gov/resources/identifier/claim-group,34431115203,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",outpatient-8497385923
54889,https://bluebutton.cms.gov/resources/variables/clm_id,9624565892,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",outpatient-9624565892
54890,https://bluebutton.cms.gov/resources/identifier/claim-group,39004410854,"[{'code': 'uc', 'display': 'Unique Claim ID', 'system': 'http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType'}]",outpatient-9624565892

In [ ]:
eob_df_idnetifier_type_coding = json_normalize(
    eob_df_idnetifier.to_dict(orient='records'),
    record_path='type.coding',
    meta = [col for col in eob_df_idnetifier.columns if col != 'type.coding'],
    meta_prefix= 'type_'
)
eob_df_idnetifier_type_coding
##########################################################################################################################################################################

,code,display,system,type_system,type_value,type_Claim_ID
0,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/variables/clm_id,20897811241,carrier-20897811241
1,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/identifier/claim-group,1651072082,carrier-20897811241
2,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/variables/clm_id,20944329733,carrier-20944329733
3,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/identifier/claim-group,83652425,carrier-20944329733
4,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/variables/clm_id,21106403489,carrier-21106403489
...,...,...,...,...,...,...
54886,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/identifier/claim-group,34235871497,outpatient-8468545509
54887,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/variables/clm_id,8497385923,outpatient-8497385923
54888,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/identifier/claim-group,34431115203,outpatient-8497385923
54889,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/variables/clm_id,9624565892,outpatient-9624565892
54890,uc,Unique Claim ID,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType,https://bluebutton.cms.gov/resources/identifier/claim-group,39004410854,outpatient-9624565892

In [238]:
eob_df_insurance = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='insurance',
    meta = 'Claim_ID'
)
eob_df_insurance.drop(columns = 'coverage.extension', inplace = True)
eob_df_insurance.rename(columns = {'coverage.reference': 'Coverage_ID'}, inplace = True)
eob_df_insurance = eob_df_insurance[['Claim_ID', 'Coverage_ID', 'focal']]
eob_df_insurance
#####################################################################################################################################################################

                    Claim_ID                Coverage_ID  focal
0        carrier-20897811241   Coverage/part-b-40261907   True
1        carrier-20944329733   Coverage/part-b-40261907   True
2        carrier-21106403489   Coverage/part-b-40261907   True
3        carrier-21155373512   Coverage/part-b-40261907   True
4        carrier-21200601242   Coverage/part-b-40261907   True
...                      ...                        ...    ...
21776  outpatient-8312279482  Coverage/part-b-387972038   True
21777  outpatient-8329521415  Coverage/part-b-387972038   True
21778  outpatient-8468545509  Coverage/part-b-387972038   True
21779  outpatient-8497385923  Coverage/part-b-387972038   True
21780  outpatient-9624565892  Coverage/part-b-387972038   True

[21781 rows x 3 columns]

In [ ]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item

,adjudication,careTeamSequence,diagnosisSequence,extension,sequence,category.coding,locationCodeableConcept.coding,locationCodeableConcept.extension,productOrService.coding,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID
0,"[{'category': {'coding': [{'code': 'denialreason', 'display': 'Denial Reason', 'system': 'http:/...",[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '8406...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '81', 'display': 'Independent Laboratory. A laboratory certified to perform diagnostic...","[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code'...","[{'code': '87086', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241
1,"[{'category': {'coding': [{'code': 'denialreason', 'display': 'Denial Reason', 'system': 'http:/...",[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code'...","[{'code': '81001', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733
2,"[{'category': {'coding': [{'code': 'denialreason', 'display': 'Denial Reason', 'system': 'http:/...",[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code'...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489
3,"[{'category': {'coding': [{'code': 'denialreason', 'display': 'Denial Reason', 'system': 'http:/...",[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",2,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code'...","[{'code': '82150', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489
4,"[{'category': {'coding': [{'code': 'denialreason', 'display': 'Denial Reason', 'system': 'http:/...",[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code'...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45753,"[{'amount': {'currency': 'USD', 'value': 5.18}, 'category': {'coding': [{'code': 'submitted', 'd...",NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",5,NaN,NaN,NaN,"[{'code': '82570', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45754,"[{'amount': {'currency': 'USD', 'value': 41.28}, 'category': {'coding': [{'code': 'submitted', '...",NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",6,NaN,NaN,NaN,"[{'code': '83970', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45755,"[{'amount': {'currency': 'USD', 'value': 3.67}, 'category': {'coding': [{'code': 'submitted', 'd...",NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",7,NaN,NaN,NaN,"[{'code': '84156', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45756,"[{'amount': {'currency': 'USD', 'value': 7.77}, 'category': {'coding': [{'code': 'submitted', 'd...",NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",8,NaN,NaN,NaN,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45757,"[{'amount': {'currency': 'USD', 'value': 0}, 'category': {'coding': [{'code': 'submitted', 'disp...",NaN,NaN,NaN,9,NaN,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': '...",0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/var...","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892

In [ ]:
eob_df_item2 = eob_df_item.drop(columns = ['adjudication', 'extension', 'locationCodeableConcept.extension', 'productOrService.extension', 'revenue.extension'])
eob_df_item2.info()

,careTeamSequence,diagnosisSequence,extension,sequence,category.coding,locationCodeableConcept.coding,productOrService.coding,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '8406...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '81', 'display': 'Independent Laboratory. A laboratory certified to perform diagnostic...","[{'code': '87086', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '81001', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",2,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '82150', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '7519...",1,"[{'code': '5', 'display': 'Diagnostic laboratory', 'system': 'https://bluebutton.cms.gov/resourc...","[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45753,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",5,NaN,NaN,"[{'code': '82570', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45754,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",6,NaN,NaN,"[{'code': '83970', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45755,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",7,NaN,NaN,"[{'code': '84156', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45756,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'...",8,NaN,NaN,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892
45757,NaN,NaN,NaN,9,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}]",0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/var...","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {...",NaN,outpatient-9624565892

In [247]:
eob_df_item_category_coding = eob_df_item2.explode('category.coding')

eob_df_item_category_coding = json_normalize(
    eob_df_item_category_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_category_coding = eob_df_item_category_coding.drop(columns = ['category.coding', 'category.coding.system'])
eob_df_item_category_coding

,careTeamSequence,diagnosisSequence,sequence,locationCodeableConcept.coding,productOrService.coding,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,informationSequence,Claim_ID,category.coding.code,category.coding.display
0,[3],[1],1,"[{'code': '81', 'display': 'Independent Laboratory. A laboratory certified to perform diagnostic...","[{'code': '87086', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory
1,[3],[1],1,"[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '81001', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory
2,[3],[1],1,"[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory
3,[3],[1],2,"[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '82150', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory
4,[3],[1],1,"[{'code': '11', 'display': 'Office. Location, other than a hospital, skilled nursing facility (S...","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45753,NaN,NaN,5,NaN,"[{'code': '82570', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN
45754,NaN,NaN,6,NaN,"[{'code': '83970', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN
45755,NaN,NaN,7,NaN,"[{'code': '84156', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN
45756,NaN,NaN,8,NaN,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN
45757,NaN,NaN,9,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}]",0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/var...",NaN,outpatient-9624565892,NaN,NaN

In [250]:
eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')

eob_df_item_location_coding = json_normalize(
    eob_df_item_location_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_location_coding = eob_df_item_location_coding.drop(columns = ['locationCodeableConcept.coding.system', 'locationCodeableConcept.coding'])
eob_df_item_location_coding

,careTeamSequence,diagnosisSequence,sequence,productOrService.coding,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,informationSequence,Claim_ID,category.coding.code,category.coding.display,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display
0,[3],[1],1,"[{'code': '87086', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests indep...
1,[3],[1],1,"[{'code': '81001', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment faci..."
2,[3],[1],1,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment faci..."
3,[3],[1],2,"[{'code': '82150', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment faci..."
4,[3],[1],1,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment faci..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45753,NaN,NaN,5,"[{'code': '82570', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN
45754,NaN,NaN,6,"[{'code': '83970', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN
45755,NaN,NaN,7,"[{'code': '84156', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN
45756,NaN,NaN,8,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton....",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN
45757,NaN,NaN,9,"[{'code': 'NULL', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}]",0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/var...",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN

In [263]:
eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')

eob_df_item_product_coding = json_normalize(
    eob_df_item_product_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_product_coding = eob_df_item_product_coding.drop(columns ='productOrService.coding.system')
eob_df_item_product_coding.info()

<class 'pandas.DataFrame'>
RangeIndex: 45767 entries, 0 to 45766
Data columns (total 18 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   careTeamSequence                        30321 non-null  object
 1   diagnosisSequence                       14128 non-null  object
 2   sequence                                45767 non-null  int64
 3   quantity.value                          45767 non-null  float64
 4   servicedPeriod.end                      18992 non-null  str
 5   servicedPeriod.start                    18992 non-null  str
 6   modifier                                11997 non-null  object
 7   servicedDate                            23844 non-null  str
 8   locationAddress.state                   15446 non-null  str
 9   revenue.coding                          15446 non-null  object
 10  informationSequence                     28 non-null     object
 11  Claim_ID                                45767 non-null  str
 12  category.coding.code                    18992 non-null  str
 13  category.coding.display                 18992 non-null  str
 14  locationCodeableConcept.coding.code     18992 non-null  str
 15  locationCodeableConcept.coding.display  18992 non-null  str
 16  productOrService.coding.code            45767 non-null  str
 17  productOrService.coding.display         10566 non-null  str
dtypes: float64(1), int64(1), object(5), str(11)
memory usage: 6.3+ MB

In [29]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)

eob_df_item2 = eob_df_item.drop(columns = ['adjudication', 'extension', 'locationCodeableConcept.extension', 'productOrService.extension', 'revenue.extension'])

eob_df_item_category_coding = eob_df_item2.explode('category.coding')

eob_df_item_category_coding = json_normalize(
    eob_df_item_category_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_category_coding = eob_df_item_category_coding.drop(columns = ['category.coding', 'category.coding.system'])

eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')

eob_df_item_location_coding = json_normalize(
    eob_df_item_location_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_location_coding = eob_df_item_location_coding.drop(columns = ['locationCodeableConcept.coding.system', 'locationCodeableConcept.coding'])

eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')

eob_df_item_product_coding = json_normalize(
    eob_df_item_product_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_product_coding = eob_df_item_product_coding.drop(columns ='productOrService.coding.system')

eob_df_item_revenue_coding = eob_df_item_product_coding.explode('revenue.coding')

eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_revenue_coding = eob_df_item_revenue_coding.drop(columns = ['revenue.coding.system', 'revenue.coding'])
eob_df_item_revenue_coding.rename(columns = {
    'sequence': 'item_sequence',
    'quantity.value': 'quantity',
    'category.coding.code': 'category_code',
    'category.coding.display': 'category_display',
    'locationCodeableConcept.coding.code': 'location_code',
    'locationCodeableConcept.coding.display': 'location_display',
    'productOrService.coding.code': 'product_code',
    'productOrService.coding.display': 'product_display',
    'revenue.coding.code': 'revenue_code',
    'revenue.coding.display': 'revenue_display',
    'servicedPeriod.end': 'serviceperiod_end',
    'servicedPeriod.start': 'serviceperiod_start'
}, inplace = True)
eob_df_item_revenue_coding = eob_df_item_revenue_coding[['Claim_ID', 'item_sequence', 'careTeamSequence', 'diagnosisSequence', 'product_code', 'product_display','revenue_code', 'revenue_display', 'category_code', 'category_display', 'location_code','serviceperiod_start','serviceperiod_end','servicedDate', 'location_display']]
eob_df_item_revenue_coding

,Claim_ID,item_sequence,careTeamSequence,diagnosisSequence,product_code,product_display,revenue_code,revenue_display,category_code,category_display,location_code,serviceperiod_start,serviceperiod_end,servicedDate,location_display
0,carrier-20897811241,1,[3],[1],87086,NaN,NaN,NaN,5,Diagnostic laboratory,81,2014-06-05,2014-06-05,NaN,Independent Laboratory. A laboratory certified...
1,carrier-20944329733,1,[3],[1],81001,NaN,NaN,NaN,5,Diagnostic laboratory,11,2014-06-05,2014-06-05,NaN,"Office. Location, other than a hospital, skill..."
2,carrier-21106403489,1,[3],[1],85025,NaN,NaN,NaN,5,Diagnostic laboratory,11,2014-07-22,2014-07-22,NaN,"Office. Location, other than a hospital, skill..."
3,carrier-21106403489,2,[3],[1],82150,NaN,NaN,NaN,5,Diagnostic laboratory,11,2014-07-22,2014-07-22,NaN,"Office. Location, other than a hospital, skill..."
4,carrier-21155373512,1,[3],[1],85025,NaN,NaN,NaN,5,Diagnostic laboratory,11,2014-07-25,2014-07-25,NaN,"Office. Location, other than a hospital, skill..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46632,outpatient-9624565892,5,NaN,NaN,82570,NaN,0300,Laboratory-general classification,NaN,NaN,NaN,NaN,NaN,2025-11-03,NaN
46633,outpatient-9624565892,6,NaN,NaN,83970,NaN,0300,Laboratory-general classification,NaN,NaN,NaN,NaN,NaN,2025-11-03,NaN
46634,outpatient-9624565892,7,NaN,NaN,84156,NaN,0300,Laboratory-general classification,NaN,NaN,NaN,NaN,NaN,2025-11-03,NaN
46635,outpatient-9624565892,8,NaN,NaN,85025,NaN,0300,Laboratory-general classification,NaN,NaN,NaN,NaN,NaN,2025-11-03,NaN
46636,outpatient-9624565892,9,NaN,NaN,NULL,NaN,0001,Total charge,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [189]:
eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')

eob_df_item_location_coding = json_normalize(
    eob_df_item_location_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_location_coding

,careTeamSequence,diagnosisSequence,extension,sequence,locationCodeableConcept.extension,productOrService.coding,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '752302544', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0480381'}}]","[{'code': '87086', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'code': '81001', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1H', 'display': 'Lab tests - other (non-Medicare fee schedule)', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",2,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'code': '82150', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45753,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,NaN,"[{'code': '82570', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45754,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,NaN,"[{'code': '83970', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45755,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,NaN,"[{'code': '84156', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45756,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,NaN,"[{'code': '85025', 'system': 'https://bluebutton.cms.gov/resources/codesystem/hcpcs'}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [191]:
eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')

eob_df_item_product_coding = json_normalize(
    eob_df_item_product_coding.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_product_coding

,careTeamSequence,diagnosisSequence,extension,sequence,locationCodeableConcept.extension,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '752302544', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0480381'}}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,81001,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1H', 'display': 'Lab tests - other (non-Medicare fee schedule)', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",2,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,82150,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]","[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45762,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,NaN,"[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
45763,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,NaN,"[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
45764,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,NaN,"[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
45765,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,NaN,"[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN
45766,NaN,NaN,NaN,9,NaN,"[{'url': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason', 'valueCoding': {'code': 'NULL', 'display': 'Data Absent Reason', 'system': 'http://hl7.org/fhir/StructureDefinition/data-absent-reason'}}]",0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN

In [192]:
eob_df_item_product_ext = eob_df_item_product_coding.explode('productOrService.extension')

eob_df_item_product_ext = json_normalize(
    eob_df_item_product_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_product_ext

,careTeamSequence,diagnosisSequence,extension,sequence,locationCodeableConcept.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,productOrService.extension
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '752302544', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0480381'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,81001,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1H', 'display': 'Lab tests - other (non-Medicare fee schedule)', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",2,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,82150,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45762,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
45763,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
45764,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
45765,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,"[{'code': '0300', 'display': 'Laboratory-general classification', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN
45766,NaN,NaN,NaN,9,NaN,0.0,NaN,NaN,NaN,NaN,AR,"[{'code': '0001', 'display': 'Total charge', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr'}]","[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN

In [193]:
eob_df_item_revenue = eob_df_item_product_ext.explode('revenue.coding')

eob_df_item_revenue = json_normalize(
    eob_df_item_revenue.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_revenue

,careTeamSequence,diagnosisSequence,extension,sequence,locationCodeableConcept.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,productOrService.extension,revenue.coding.code,revenue.coding.display,revenue.coding.system
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '752302544', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0480381'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,81001,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1H', 'display': 'Lab tests - other (non-Medicare fee schedule)', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",2,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,82150,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46632,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr
46633,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr
46634,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr
46635,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr
46636,NaN,NaN,NaN,9,NaN,0.0,NaN,NaN,NaN,NaN,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables/rev_cntr

In [195]:
eob_df_item_revenue_ext = eob_df_item_revenue.explode('revenue.extension')

eob_df_item_revenue_ext = json_normalize(
    eob_df_item_revenue_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_revenue_ext

,careTeamSequence,diagnosisSequence,extension,sequence,locationCodeableConcept.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,productOrService.extension,revenue.coding.code,revenue.coding.display,revenue.coding.system,revenue.extension.url,revenue.extension.valueCoding.code,revenue.extension.valueCoding.display,revenue.extension.valueCoding.system
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '752302544', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0480381'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,81001,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1H', 'display': 'Lab tests - other (non-Medicare fee schedule)', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",2,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-22,2014-07-22,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21106403489,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,82150,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1D', 'display': 'Lab tests - blood counts', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,"[{'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd', 'valueCoding': {'code': 'TX', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_state_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip', 'valueCoding': {'code': '755513245', 'system': 'https://bluebutton.cms.gov/resources/variables/prvdr_zip'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd', 'valueCoding': {'code': '00', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'valueIdentifier': {'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num', 'value': '45D0976266'}}]",1.0,2014-07-25,2014-07-25,NaN,NaN,NaN,NaN,NaN,NaN,carrier-21155373512,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46632,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,NaN,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
46633,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,NaN,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
46634,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,NaN,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
46635,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,NaN,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,NaN,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
46636,NaN,NaN,NaN,9,NaN,0.0,NaN,NaN,NaN,NaN,AR,NaN,NaN,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables/rev_cntr,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd

In [196]:
eob_df_item_location = eob_df_item_revenue.explode('locationCodeableConcept.extension')

eob_df_item_location = json_normalize(
    eob_df_item_location.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_location

,careTeamSequence,diagnosisSequence,extension,sequence,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,productOrService.extension,revenue.coding.code,revenue.coding.display,revenue.coding.system,locationCodeableConcept.extension.url,locationCodeableConcept.extension.valueCoding.code,locationCodeableConcept.extension.valueCoding.system,locationCodeableConcept.extension.valueIdentifier.system,locationCodeableConcept.extension.valueIdentifier.value,locationCodeableConcept.extension.valueCoding.display,locationCodeableConcept.extension
0,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN
1,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_zip,752302544,https://bluebutton.cms.gov/resources/variables/prvdr_zip,NaN,NaN,NaN,NaN
2,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd,00,https://bluebutton.cms.gov/resources/variables/carr_line_prcng_lclty_cd,NaN,NaN,NaN,NaN
3,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '840611484', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1F', 'display': 'Lab tests - bacterial cultures', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_clia_lab_num,45D0480381,NaN,NaN
4,[3],[1],"[{'url': 'https://bluebutton.cms.gov/resources/variables/tax_num', 'valueCoding': {'code': '751928214', 'system': 'https://bluebutton.cms.gov/resources/variables/tax_num'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueQuantity': {'value': 1}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt', 'valueCoding': {'code': '3', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd', 'valueCoding': {'code': '3', 'display': 'Services', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/betos_cd', 'valueCoding': {'code': 'T1C', 'display': 'Lab tests - urinalysis', 'system': 'https://bluebutton.cms.gov/resources/variables/betos_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Allowed', 'system': 'https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd'}}, {'url': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible', 'valueCoding': {'code': '1', 'display': 'Service Not Subject to Deductible', 'system': 'https://bluebutton.cms.gov/resources/variables/line_service_deductible'}}]",1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20944329733,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,11,"Office. Location, other than a hospital, skilled nursing facility (SNF), military treatment facility, community health center, State or local public health clinic, or intermediate care facility (ICF), where the health professional routinely provides health examinations, diagnosis, and treatment of illness or injury on an ambulatory basis.",https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,81001,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92527,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",5,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92528,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",6,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92529,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",7,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92530,NaN,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt', 'valueQuantity': {'value': 1}}]",8,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92531,NaN,NaN,NaN,9,0.0,NaN,NaN,NaN,NaN,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
eob_df_ext = eob_df_item_location.explode('extension')

eob_df_ext = json_normalize(
    eob_df_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_ext

,careTeamSequence,diagnosisSequence,sequence,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,category.coding,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,productOrService.extension,revenue.coding.code,revenue.coding.display,revenue.coding.system,locationCodeableConcept.extension.url,locationCodeableConcept.extension.valueCoding.code,locationCodeableConcept.extension.valueCoding.system,locationCodeableConcept.extension.valueIdentifier.system,locationCodeableConcept.extension.valueIdentifier.value,locationCodeableConcept.extension.valueCoding.display,locationCodeableConcept.extension,extension.url,extension.valueCoding.code,extension.valueCoding.system,extension.valueQuantity.value,extension.valueCoding.display,extension.valueIdentifier.system,extension.valueIdentifier.value,extension.valueQuantity.code,extension.valueQuantity.system,extension.valueQuantity.unit,extension
0,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/tax_num,840611484,https://bluebutton.cms.gov/resources/variables/tax_num,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,3,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd,3,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd,NaN,Services,NaN,NaN,NaN,NaN,NaN,NaN
4,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,NaN,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/betos_cd,T1F,https://bluebutton.cms.gov/resources/variables/betos_cd,NaN,Lab tests - bacterial cultures,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485494,NaN,NaN,5,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485495,NaN,NaN,6,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485496,NaN,NaN,7,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485497,NaN,NaN,8,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485498,NaN,NaN,9,0.0,NaN,NaN,NaN,NaN,AR,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd', 'valueCoding': {'code': 'A', 'display': 'Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)', 'system': 'https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd'}}]",NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [200]:
eob_df_rev_ext = eob_df_ext.explode('revenue.extension')

eob_df_rev_ext = json_normalize(
    eob_df_rev_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)

columns = ['revenue.extension','revenue.coding', 'category.coding', 'locationCodeableConcept.extension', 'productOrService.extension', 'extension']

eob_item=eob_df_rev_ext.drop(columns = columns)

eob_item

,careTeamSequence,diagnosisSequence,sequence,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,servicedDate,locationAddress.state,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,locationCodeableConcept.coding,productOrService.coding.code,productOrService.coding.system,productOrService.coding.display,productOrService.extension.url,productOrService.extension.valueCoding.code,productOrService.extension.valueCoding.display,productOrService.extension.valueCoding.system,revenue.coding.code,revenue.coding.display,revenue.coding.system,locationCodeableConcept.extension.url,locationCodeableConcept.extension.valueCoding.code,locationCodeableConcept.extension.valueCoding.system,locationCodeableConcept.extension.valueIdentifier.system,locationCodeableConcept.extension.valueIdentifier.value,locationCodeableConcept.extension.valueCoding.display,extension.url,extension.valueCoding.code,extension.valueCoding.system,extension.valueQuantity.value,extension.valueCoding.display,extension.valueIdentifier.system,extension.valueIdentifier.value,extension.valueQuantity.code,extension.valueQuantity.system,extension.valueQuantity.unit,revenue.extension.url,revenue.extension.valueCoding.code,revenue.extension.valueCoding.display,revenue.extension.valueCoding.system
0,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/tax_num,840611484,https://bluebutton.cms.gov/resources/variables/tax_num,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,3,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cnt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd,3,https://bluebutton.cms.gov/resources/variables/carr_line_mtus_cd,NaN,Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[3],[1],1,1.0,2014-06-05,2014-06-05,NaN,NaN,NaN,NaN,carrier-20897811241,5,Diagnostic laboratory,https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd,81,Independent Laboratory. A laboratory certified to perform diagnostic and/or clinical tests independent of an institution or a physician's office.,https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd,NaN,87086,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,TX,https://bluebutton.cms.gov/resources/variables/prvdr_state_cd,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/betos_cd,T1F,https://bluebutton.cms.gov/resources/variables/betos_cd,NaN,Lab tests - bacterial cultures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485494,NaN,NaN,5,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82570,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
485495,NaN,NaN,6,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83970,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
485496,NaN,NaN,7,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84156,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
485497,NaN,NaN,8,0.0,NaN,NaN,NaN,2025-11-03,AR,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85025,https://bluebutton.cms.gov/resources/codesystem/hcpcs,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_unit_cnt,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd
485498,NaN,NaN,9,0.0,NaN,NaN,NaN,NaN,AR,NaN,outpatient-9624565892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NaN,http://hl7.org/fhir/StructureDefinition/data-absent-reason,NULL,Data Absent Reason,http://hl7.org/fhir/StructureDefinition/data-absent-reason,0001,Total charge,https://bluebutton.cms.gov/resources/variables/rev_cntr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd,A,"Services not paid under OPPS; uses a different fee schedule (e.g., ambulance, PT, mammography)",https://bluebutton.cms.gov/resources/variables/rev_cntr_stus_ind_cd

In [ ]:
eob_df_rev_ext.info()

<class 'pandas.DataFrame'>
RangeIndex: 485499 entries, 0 to 485498
Data columns (total 54 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   careTeamSequence                                          469183 non-null  object
 1   diagnosisSequence                                         331736 non-null  object
 2   sequence                                                  485499 non-null  int64
 3   quantity.value                                            485499 non-null  float64
 4   servicedPeriod.end                                        457854 non-null  str
 5   servicedPeriod.start                                      457854 non-null  str
 6   modifier                                                  143604 non-null  object
 7   servicedDate                                              24714 non-null   str
 8   locationAddress.state                                     16316 non-null   str
 9   revenue.coding                                            0 non-null       float64
 10  revenue.extension                                         0 non-null       float64
 11  informationSequence                                       784 non-null     object
 12  Claim_ID                                                  485499 non-null  str
 13  category.coding.code                                      457854 non-null  str
 14  category.coding.display                                   457854 non-null  str
 15  category.coding.system                                    457854 non-null  str
 16  category.coding                                           0 non-null       float64
 17  locationCodeableConcept.coding.code                       457854 non-null  str
 18  locationCodeableConcept.coding.display                    457854 non-null  str
 19  locationCodeableConcept.coding.system                     457854 non-null  str
 20  locationCodeableConcept.coding                            0 non-null       float64
 21  productOrService.coding.code                              485499 non-null  str
 22  productOrService.coding.system                            485499 non-null  str
 23  productOrService.coding.display                           10566 non-null   str
 24  productOrService.extension.url                            470275 non-null  str
 25  productOrService.extension.valueCoding.code               470275 non-null  str
 26  productOrService.extension.valueCoding.display            470149 non-null  str
 27  productOrService.extension.valueCoding.system             470275 non-null  str
 28  productOrService.extension                                0 non-null       float64
 29  revenue.coding.code                                       16316 non-null   str
 30  revenue.coding.display                                    15867 non-null   str
 31  revenue.coding.system                                     16316 non-null   str
 32  locationCodeableConcept.extension.url                     457854 non-null  str
 33  locationCodeableConcept.extension.valueCoding.code        386627 non-null  str
 34  locationCodeableConcept.extension.valueCoding.system      386627 non-null  str
 35  locationCodeableConcept.extension.valueIdentifier.system  71227 non-null   str
 36  locationCodeableConcept.extension.valueIdentifier.value   71227 non-null   str
 37  locationCodeableConcept.extension.valueCoding.display     9288 non-null    str
 38  locationCodeableConcept.extension                         0 non-null       float64
 39  extension.url                                             472391 non-null  str
 40  extension.valueCoding.code                                390006 non-null  str
 41  extension.valueCoding.system                              390006 non-null  str
 42  extension.valueQuantity.value                             81263 non-null   float64
 43  extension.valueCoding.display                             260220 non-null  str
 44  extension.valueIdentifier.system                          1122 non-null    str
 45  extension.valueIdentifier.value                           1122 non-null    str
 46  extension.valueQuantity.code                              1122 non-null    str
 47  extension.valueQuantity.system                            1122 non-null    str
 48  extension.valueQuantity.unit                              1122 non-null    str
 49  extension                                                 0 non-null       float64
 50  revenue.extension.url                                     14544 non-null   str
 51  revenue.extension.valueCoding.code                        14544 non-null   str
 52  revenue.extension.valueCoding.display                     14412 non-null   str
 53  revenue.extension.valueCoding.system                      14544 non-null   str
dtypes: float64(9), int64(1), object(4), str(40)
memory usage: 200.0+ MB

In [39]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)

eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = ['Claim_ID', 'sequence']
)

eob_df_item_adjudication = eob_df_item_adjudication.explode('category.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('reason.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('extension')

eob_df_item_adjudication = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records')
)
eob_df_item_adjudication = eob_df_item_adjudication[
    ~eob_df_item_adjudication['category.coding.code'].str.contains('http', na=False)
]

eob_df_item_adjudication

,extension,amount.currency,amount.value,Claim_ID,sequence,category.coding.code,category.coding.display,category.coding.system,reason.coding.code,reason.coding.display,reason.coding.system,reason.coding,extension.url,extension.valueCoding.code,extension.valueCoding.display,extension.valueCoding.system
0,NaN,NaN,NaN,carrier-27286904395,1,denialreason,Denial Reason,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,0,N/A,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN,NaN
1,NaN,USD,48.01,carrier-27286904395,1,benefit,Benefit Amount,http://terminology.hl7.org/CodeSystem/adjudica...,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,1,100%,https://bluebutton.cms.gov/resources/variables...
3,NaN,USD,0.00,carrier-27286904395,1,paidtopatient,Paid to patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,USD,48.01,carrier-27286904395,1,paidtoprovider,Paid to provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,USD,0.00,carrier-27286904395,1,deductible,Deductible,http://terminology.hl7.org/CodeSystem/adjudica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688746,NaN,USD,0.00,outpatient-9623755765,2,priorpayerpaid,Prior payer paid,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688748,NaN,USD,0.00,outpatient-9623755765,2,paidtoprovider,Paid to provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688750,NaN,USD,0.00,outpatient-9623755765,2,paidtopatient,Paid to patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688752,NaN,USD,0.00,outpatient-9623755765,2,paidbypatient,Paid by patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688754,NaN,USD,0.00,outpatient-9623755765,2,submitted,Submitted Amount,http://terminology.hl7.org/CodeSystem/adjudica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = ['Claim_ID', 'sequence']
)
eob_df_item_adjudication = eob_df_item_adjudication.explode('reason.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('category.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('extension')
eob_df_item_adjudication = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records')
)
eob_df_item_adjudication = eob_df_item_adjudication[
    eob_df_item_adjudication['category.coding.code'].str.contains('http', na=False)
]
eob_df_item_adjudication.rename(columns = {
    'amount.currency': 'currency_type',
    'sequence': 'item_sequence',
    'amount.value': 'amount',
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display',
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display',
    'category.coding.display': 'display'
}, inplace = True)
cols = ['Claim_ID','item_sequence', 'display', 'currency_type', 'amount', 'reason_code', 'reason_display', 'LINE_PMT_80_100_CD', 'LINE_PMT_80_100_display']
eob_df_item_adjudication = eob_df_item_adjudication.reindex(columns=cols)
eob_df_item_adjudication = eob_df_item_adjudication.drop_duplicates()
eob_df_item_adjudication=eob_df_item_adjudication.reset_index(drop = True)
eob_df_item_adjudication

,Claim_ID,item_sequence,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
0,carrier-27286904395,1,Line NCH Medicare Payment Amount,USD,48.01,NaN,NaN,1,100%
1,carrier-27286904395,1,Line Payment Amount to Beneficiary,USD,0.00,NaN,NaN,NaN,NaN
2,carrier-27286904395,1,Line Provider Payment Amount,USD,48.01,NaN,NaN,NaN,NaN
3,carrier-27286904395,1,Line Beneficiary Part B Deductible Amount,USD,0.00,NaN,NaN,NaN,NaN
4,carrier-27286904395,1,Line Primary Payer (if not Medicare) Paid Amount,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
334523,outpatient-9623755765,2,Revenue Center 2nd Medicare Secondary Payer (M...,USD,0.00,NaN,NaN,NaN,NaN
334524,outpatient-9623755765,2,Revenue Center (Medicare) Provider Payment Amount,USD,0.00,NaN,NaN,NaN,NaN
334525,outpatient-9623755765,2,Revenue Center Payment Amount to Beneficiary,USD,0.00,NaN,NaN,NaN,NaN
334526,outpatient-9623755765,2,Revenue Center Patient Responsibility Payment ...,USD,0.00,NaN,NaN,NaN,NaN
334527,outpatient-9623755765,2,Revenue Center (Medicare) Payment Amount,USD,0.00,NaN,NaN,NaN,NaN

In [16]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = ['Claim_ID', 'sequence']
)
eob_df_item_adjudication = eob_df_item_adjudication.explode('reason.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('category.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('extension')
eob_df_item_adjudication = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records')
)
eob_df_item_adjudication = eob_df_item_adjudication[
    eob_df_item_adjudication['category.coding.code'].str.contains('http', na=False)
]
eob_df_item_adjudication.rename(columns = {
    'amount.currency': 'currency_type',
    'amount.value': 'amount',
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display',
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display',
    'category.coding.display': 'display'
}, inplace = True)
eob_df_item_adjudication = eob_df_item_adjudication[['Claim_ID', 'sequence', 'display', 'currency_type', 'amount', 'reason_code', 'reason_display', 'LINE_PMT_80_100_CD', 'LINE_PMT_80_100_display']]
eob_df_item_adjudication

,Claim_ID,sequence,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
2,carrier-27286904395,1,Line NCH Medicare Payment Amount,USD,48.01,NaN,NaN,1,100%
4,carrier-27286904395,1,Line Payment Amount to Beneficiary,USD,0.00,NaN,NaN,NaN,NaN
6,carrier-27286904395,1,Line Provider Payment Amount,USD,48.01,NaN,NaN,NaN,NaN
8,carrier-27286904395,1,Line Beneficiary Part B Deductible Amount,USD,0.00,NaN,NaN,NaN,NaN
10,carrier-27286904395,1,Line Primary Payer (if not Medicare) Paid Amount,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
688747,outpatient-9623755765,2,Revenue Center 2nd Medicare Secondary Payer (M...,USD,0.00,NaN,NaN,NaN,NaN
688749,outpatient-9623755765,2,Revenue Center (Medicare) Provider Payment Amount,USD,0.00,NaN,NaN,NaN,NaN
688751,outpatient-9623755765,2,Revenue Center Payment Amount to Beneficiary,USD,0.00,NaN,NaN,NaN,NaN
688753,outpatient-9623755765,2,Revenue Center Patient Responsibility Payment ...,USD,0.00,NaN,NaN,NaN,NaN
688755,outpatient-9623755765,2,Revenue Center (Medicare) Payment Amount,USD,0.00,NaN,NaN,NaN,NaN

In [138]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_category_coding = eob_df_item.explode('category.coding')
eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')
eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')
eob_df_item_revenue_coding = eob_df_item_product_coding.explode('revenue.coding')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('revenue.extension')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier')
eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier.coding')
eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding
eob_df_item_revenue_coding.rename(columns = {
    'sequence': 'item_sequence',
    'quantity.value': 'quantity',
    'category.coding.code': 'category_code',
    'category.coding.display': 'category_display',
    'locationCodeableConcept.coding.code': 'location_code',
    'locationCodeableConcept.coding.display': 'location_display',
    'productOrService.coding.code': 'product_code',
    'productOrService.coding.display': 'product_display',
    'revenue.coding.code': 'revenue_code',
    'revenue.coding.display': 'revenue_display',
    'servicedPeriod.end': 'serviceperiod_end',
    'servicedPeriod.start': 'serviceperiod_start',
    'revenue.extension.valueCoding.display': 'revenue_ext_display',
    'revenue.extension.valueCoding.code': 'revenue_ext_code',
    'modifier.coding.code': 'modifier_code',
    'modifier.coding.version': 'modifier_version'
}, inplace = True)
cols = [
            'Claim_ID',
    'item_sequence',
    'careTeamSequence',
    'diagnosisSequence',
    'product_code',
    'product_display',
    'revenue_code',
    'revenue_display',
    'revenue_ext_code',
    'revenue_ext_display',
    'category_code',
    'category_display',
    'modifier_code',
    'modifier_version',
    'location_code',
    'location_display',
    'serviceperiod_start',
    'serviceperiod_end',
    'servicedDate'
]

eob_df_item_revenue_coding = eob_df_item_revenue_coding.reindex(columns = cols)

eob_df_item_revenue_coding['careTeamSequence'] = eob_df_item_revenue_coding['careTeamSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)
eob_df_item_revenue_coding['diagnosisSequence'] = eob_df_item_revenue_coding['diagnosisSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)
eob_df_item_revenue_coding.drop_duplicates(inplace = True)
eob_df_item_revenue_coding

,Claim_ID,item_sequence,careTeamSequence,diagnosisSequence,product_code,product_display,revenue_code,revenue_display,revenue_ext_code,revenue_ext_display,category_code,category_display,modifier_code,modifier_version,location_code,location_display,serviceperiod_start,serviceperiod_end,servicedDate
0,carrier-27286904395,1,2.0,NaN,90653,NaN,NaN,NaN,NaN,NaN,V,Pneumococcal/flu vaccine,NaN,NaN,60,Mass Immunization Center. A location where pro...,2019-12-27,2019-12-27,NaN
1,carrier-27286904395,2,2.0,NaN,G0008,NaN,NaN,NaN,NaN,NaN,V,Pneumococcal/flu vaccine,NaN,NaN,60,Mass Immunization Center. A location where pro...,2019-12-27,2019-12-27,NaN
2,carrier-27334545890,1,3.0,NaN,99214,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,11,"Office. Location, other than a hospital, skill...",2020-01-10,2020-01-10,NaN
3,carrier-27334545891,1,3.0,NaN,64493,NaN,NaN,NaN,NaN,NaN,2,Surgery,50,9,22,Outpatient Hospital. A portion of a hospital w...,2020-01-09,2020-01-09,NaN
4,carrier-27334545891,2,3.0,NaN,64494,NaN,NaN,NaN,NaN,NaN,2,Surgery,50,9,22,Outpatient Hospital. A portion of a hospital w...,2020-01-09,2020-01-09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39502,outpatient-9519284917,1,NaN,NaN,36415,NaN,0300,Laboratory-general classification,N,Packaged incidental service (no separate APC p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-22
39503,outpatient-9519284917,2,NaN,NaN,G0463,NaN,0510,Clinic-general classification,V,Medical visit to clinic or emergency department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-22
39504,outpatient-9519284917,3,NaN,NaN,NULL,NaN,0001,Total charge,A,Services not paid under OPPS; uses a different...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39505,outpatient-9623755765,1,NaN,NaN,G0463,NaN,0510,Clinic-general classification,V,Medical visit to clinic or emergency department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-12
39506,outpatient-9623755765,2,NaN,NaN,NULL,NaN,0001,Total charge,A,Services not paid under OPPS; uses a different...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
eob_df_item_revenue_coding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39496 entries, 0 to 39506
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Claim_ID             39496 non-null  object
 1   item_sequence        39496 non-null  int64
 2   careTeamSequence     26462 non-null  float64
 3   diagnosisSequence    15411 non-null  float64
 4   product_code         39496 non-null  object
 5   product_display      7387 non-null   object
 6   revenue_code         13034 non-null  object
 7   revenue_display      12747 non-null  object
 8   revenue_ext_code     10782 non-null  object
 9   revenue_ext_display  10576 non-null  object
 10  category_code        19819 non-null  object
 11  category_display     19819 non-null  object
 12  modifier_code        11785 non-null  object
 13  modifier_version     8315 non-null   object
 14  location_code        19819 non-null  object
 15  location_display     19819 non-null  object
 16  serviceperiod_start  19819 non-null  object
 17  serviceperiod_end    19819 non-null  object
 18  servicedDate         16619 non-null  object
dtypes: float64(2), int64(1), object(16)
memory usage: 6.0+ MB

In [172]:
eob_df_item_adjudication_reason = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records'),
    record_path='category.coding',
    meta = [col for col in eob_df_item_adjudication.columns if col != 'category.coding']
)
eob_df_item_adjudication_reason[eob_df_item_adjudication_reason['Claim_ID'] == 'carrier-20897811241']

,code,display,system,reason.coding,extension,amount.currency,amount.value,Claim_ID
0,denialreason,Denial Reason,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudicationDiscriminator,"[{'code': '0', 'display': 'N/A', 'system': 'https://bluebutton.cms.gov/resources/variables/carr_line_rdcd_pmt_phys_astn_c'}]",NaN,NaN,NaN,carrier-20897811241
1,benefit,Benefit Amount,http://terminology.hl7.org/CodeSystem/adjudication,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd', 'valueCoding': {'code': '1', 'display': '100%', 'system': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd'}}]",USD,10.79,carrier-20897811241
2,https://bluebutton.cms.gov/resources/variables/line_nch_pmt_amt,Line NCH Medicare Payment Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,"[{'url': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd', 'valueCoding': {'code': '1', 'display': '100%', 'system': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd'}}]",USD,10.79,carrier-20897811241
3,paidtopatient,Paid to patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,NaN,USD,0.0,carrier-20897811241
4,https://bluebutton.cms.gov/resources/variables/line_bene_pmt_amt,Line Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,0.0,carrier-20897811241
5,paidtoprovider,Paid to provider,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,NaN,USD,10.79,carrier-20897811241
6,https://bluebutton.cms.gov/resources/variables/line_prvdr_pmt_amt,Line Provider Payment Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,10.79,carrier-20897811241
7,deductible,Deductible,http://terminology.hl7.org/CodeSystem/adjudication,NaN,NaN,USD,0.0,carrier-20897811241
8,https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt,Line Beneficiary Part B Deductible Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,0.0,carrier-20897811241
9,priorpayerpaid,Prior payer paid,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,NaN,USD,0.0,carrier-20897811241
10,https://bluebutton.cms.gov/resources/variables/line_bene_prmry_pyr_pd_amt,Line Primary Payer (if not Medicare) Paid Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,0.0,carrier-20897811241
11,coinsurance,Co-insurance,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,NaN,USD,0.0,carrier-20897811241
12,https://bluebutton.cms.gov/resources/variables/line_coinsrnc_amt,Line Beneficiary Coinsurance Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,0.0,carrier-20897811241
13,submitted,Submitted Amount,http://terminology.hl7.org/CodeSystem/adjudication,NaN,NaN,USD,72.0,carrier-20897811241
14,https://bluebutton.cms.gov/resources/variables/line_sbmtd_chrg_amt,Line Submitted Charge Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,72.0,carrier-20897811241
15,eligible,Eligible Amount,http://terminology.hl7.org/CodeSystem/adjudication,NaN,NaN,USD,11.01,carrier-20897811241
16,https://bluebutton.cms.gov/resources/variables/line_alowd_chrg_amt,Line Allowed Charge Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,NaN,USD,11.01,carrier-20897811241

In [176]:
eob_df_item_adjudication_reason_coding = eob_df_item_adjudication_reason.explode('reason.coding')

eob_df_item_adjudication_reason_coding = json_normalize(
    eob_df_item_adjudication_reason_coding.to_dict(orient='records'),
    meta = 'Claim_ID',
)
eob_df_item_adjudication_reason_coding

,code,display,system,extension,amount.currency,amount.value,Claim_ID,reason.coding.code,reason.coding.display,reason.coding.system,reason.coding
0,denialreason,Denial Reason,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudicationDiscriminator,NaN,NaN,NaN,carrier-20897811241,0,N/A,https://bluebutton.cms.gov/resources/variables/carr_line_rdcd_pmt_phys_astn_c,NaN
1,benefit,Benefit Amount,http://terminology.hl7.org/CodeSystem/adjudication,"[{'url': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd', 'valueCoding': {'code': '1', 'display': '100%', 'system': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd'}}]",USD,10.79,carrier-20897811241,NaN,NaN,NaN,NaN
2,https://bluebutton.cms.gov/resources/variables/line_nch_pmt_amt,Line NCH Medicare Payment Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,"[{'url': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd', 'valueCoding': {'code': '1', 'display': '100%', 'system': 'https://bluebutton.cms.gov/resources/variables/line_pmt_80_100_cd'}}]",USD,10.79,carrier-20897811241,NaN,NaN,NaN,NaN
3,paidtopatient,Paid to patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,USD,0.00,carrier-20897811241,NaN,NaN,NaN,NaN
4,https://bluebutton.cms.gov/resources/variables/line_bene_pmt_amt,Line Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,USD,0.00,carrier-20897811241,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
883979,https://bluebutton.cms.gov/resources/variables/rev_cntr_bene_pmt_amt,Revenue Center Payment Amount to Beneficiary,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,USD,0.00,outpatient-9624565892,NaN,NaN,NaN,NaN
883980,paidbypatient,Paid by patient,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication,NaN,USD,0.00,outpatient-9624565892,NaN,NaN,NaN,NaN
883981,https://bluebutton.cms.gov/resources/variables/rev_cntr_ptnt_rspnsblty_pmt,Revenue Center Patient Responsibility Payment Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,USD,0.00,outpatient-9624565892,NaN,NaN,NaN,NaN
883982,submitted,Submitted Amount,http://terminology.hl7.org/CodeSystem/adjudication,NaN,USD,0.00,outpatient-9624565892,NaN,NaN,NaN,NaN
883983,https://bluebutton.cms.gov/resources/variables/rev_cntr_pmt_amt_amt,Revenue Center (Medicare) Payment Amount,https://bluebutton.cms.gov/resources/codesystem/adjudication,NaN,USD,0.00,outpatient-9624565892,NaN,NaN,NaN,NaN

In [ ]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)

eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = 'Claim_ID'
)


eob_df_item_adjudication_reason = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records'),
    record_path='category.coding',
    meta = [col for col in eob_df_item_adjudication.columns if col != 'category.coding']
)


eob_df_item_adjudication_reason_coding = eob_df_item_adjudication_reason.explode('reason.coding')

eob_df_item_adjudication_reason_coding = json_normalize(
    eob_df_item_adjudication_reason_coding.to_dict(orient='records'),
    meta = 'Claim_ID',
)

eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding.explode('extension')

eob_df_item_adjudication_reason_coding_ext = json_normalize(
    eob_df_item_adjudication_reason_coding_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)

eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding_ext[
    ~eob_df_item_adjudication_reason_coding_ext['code'].str.contains('http', na=False)
]

eob_df_item_adjudication_reason_coding_ext.drop(columns = [ 'code', 'system', 'extension', 'reason.coding.system', 'extension.url', 'extension.valueCoding.system', 'reason.coding'], inplace = True)
eob_df_item_adjudication_reason_coding_ext.rename(columns = {
    'amount.currency': 'currency_type',
    'amount.value': 'amount',
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display',
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display'
}, inplace = True)
eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding_ext[['Claim_ID', 'display', 'currency_type', 'amount', 'reason_code', 'reason_display', 'LINE_PMT_80_100_CD', 'LINE_PMT_80_100_display']]

eob_df_item_adjudication_reason_coding_ext_2=eob_df_item_adjudication_reason_coding_ext.reset_index(drop = True)
eob_df_item_adjudication_reason_coding_ext_2
#################################################################################################################################################################################

,Claim_ID,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
0,carrier-20897811241,Denial Reason,NaN,NaN,0,N/A,NaN,NaN
1,carrier-20897811241,Benefit Amount,USD,10.79,NaN,NaN,1,100%
2,carrier-20897811241,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
3,carrier-20897811241,Paid to provider,USD,10.79,NaN,NaN,NaN,NaN
4,carrier-20897811241,Deductible,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
451471,outpatient-9624565892,Prior payer paid,USD,0.00,NaN,NaN,NaN,NaN
451472,outpatient-9624565892,Paid to provider,USD,0.00,NaN,NaN,NaN,NaN
451473,outpatient-9624565892,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
451474,outpatient-9624565892,Paid by patient,USD,0.00,NaN,NaN,NaN,NaN
451475,outpatient-9624565892,Submitted Amount,USD,0.00,NaN,NaN,NaN,NaN

In [ ]:
eob_df_item_adjudication_reason_coding_ext_2 = eob_df_item_adjudication_reason_coding_ext[
    ~eob_df_item_adjudication_reason_coding_ext['code'].str.contains('http', na=False)
]

<class 'pandas.DataFrame'>
Index: 451476 entries, 0 to 883982
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Claim_ID                 451476 non-null  str
 1   code                     451476 non-null  str
 2   display                  451476 non-null  str
 3   currency_type            432508 non-null  str
 4   amount                   432508 non-null  float64
 5   reason_code              18968 non-null   str
 6   reason_display           17870 non-null   str
 7   LINE_PMT_80_100_CD       18992 non-null   str
 8   LINE_PMT_80_100_display  18992 non-null   str
dtypes: float64(1), str(8)
memory usage: 34.4 MB

In [277]:
eob_df_item_adjudication_reason_coding_ext_2=eob_df_item_adjudication_reason_coding_ext_2.reset_index(drop = True)
eob_df_item_adjudication_reason_coding_ext_2

,Claim_ID,code,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
0,carrier-20897811241,denialreason,Denial Reason,NaN,NaN,0,N/A,NaN,NaN
1,carrier-20897811241,benefit,Benefit Amount,USD,10.79,NaN,NaN,1,100%
2,carrier-20897811241,paidtopatient,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
3,carrier-20897811241,paidtoprovider,Paid to provider,USD,10.79,NaN,NaN,NaN,NaN
4,carrier-20897811241,deductible,Deductible,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
451471,outpatient-9624565892,priorpayerpaid,Prior payer paid,USD,0.00,NaN,NaN,NaN,NaN
451472,outpatient-9624565892,paidtoprovider,Paid to provider,USD,0.00,NaN,NaN,NaN,NaN
451473,outpatient-9624565892,paidtopatient,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
451474,outpatient-9624565892,paidbypatient,Paid by patient,USD,0.00,NaN,NaN,NaN,NaN
451475,outpatient-9624565892,submitted,Submitted Amount,USD,0.00,NaN,NaN,NaN,NaN

In [284]:
eob_total = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='total',
    meta='Claim_ID'
)

eob_total

,amount.currency,amount.value,category.coding,Claim_ID
0,USD,0.0,"[{'code': 'priorpayerpaid', 'display': 'Prior payer paid', 'system': 'http://hl7.org/fhir/us/car...",carrier-20897811241
1,USD,0.0,"[{'code': 'priorpayerpaid', 'display': 'Prior payer paid', 'system': 'http://hl7.org/fhir/us/car...",carrier-20944329733
2,USD,0.0,"[{'code': 'priorpayerpaid', 'display': 'Prior payer paid', 'system': 'http://hl7.org/fhir/us/car...",carrier-21106403489
3,USD,0.0,"[{'code': 'priorpayerpaid', 'display': 'Prior payer paid', 'system': 'http://hl7.org/fhir/us/car...",carrier-21155373512
4,USD,0.0,"[{'code': 'priorpayerpaid', 'display': 'Prior payer paid', 'system': 'http://hl7.org/fhir/us/car...",carrier-21200601242
...,...,...,...,...
33105,USD,664.0,"[{'code': 'submitted', 'display': 'Submitted Amount', 'system': 'http://terminology.hl7.org/Code...",outpatient-8312279482
33106,USD,89.0,"[{'code': 'submitted', 'display': 'Submitted Amount', 'system': 'http://terminology.hl7.org/Code...",outpatient-8329521415
33107,USD,1119.0,"[{'code': 'submitted', 'display': 'Submitted Amount', 'system': 'http://terminology.hl7.org/Code...",outpatient-8468545509
33108,USD,698.0,"[{'code': 'submitted', 'display': 'Submitted Amount', 'system': 'http://terminology.hl7.org/Code...",outpatient-8497385923
33109,USD,875.0,"[{'code': 'submitted', 'display': 'Submitted Amount', 'system': 'http://terminology.hl7.org/Code...",outpatient-9624565892

In [ ]:
eob_total = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='total',
    meta='Claim_ID'
)

eob_total

eob_total_category = eob_total.explode('category.coding')

eob_total_category = json_normalize(
    eob_total_category.to_dict(orient='records')
    , meta = 'Claim_ID'
)
eob_total_category.drop(columns = ['category.coding.system', 'category.coding.code'], inplace = True)
eob_total_category.rename(columns= {
    'amount.currency': 'currency_type',
    'amount.value': 'amount',
    'category.coding.display': 'category'
}, inplace = True)

eob_total_category = eob_total_category[['Claim_ID', 'category', 'currency_type', 'amount']]

eob_total_category

                    Claim_ID                   category currency_type  amount
0        carrier-20897811241           Prior payer paid           USD     0.0
1        carrier-20897811241  Claim Total Charge Amount           USD     0.0
2        carrier-20944329733           Prior payer paid           USD     0.0
3        carrier-20944329733  Claim Total Charge Amount           USD     0.0
4        carrier-21106403489           Prior payer paid           USD     0.0
...                      ...                        ...           ...     ...
43557  outpatient-8468545509  Claim Total Charge Amount           USD  1119.0
43558  outpatient-8497385923           Submitted Amount           USD   698.0
43559  outpatient-8497385923  Claim Total Charge Amount           USD   698.0
43560  outpatient-9624565892           Submitted Amount           USD   875.0
43561  outpatient-9624565892  Claim Total Charge Amount           USD   875.0

[43562 rows x 4 columns]

In [37]:
def eob_contained(eob_df, file):
    eob_df_contained = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='contained',
        meta = 'Claim_ID'
    )
    eob_df_contained_identifier = json_normalize(
        eob_df_contained.to_dict(orient= 'records'),
        record_path='identifier',
        meta = [col for col in eob_df_contained.columns if col != 'identifier']
    )
    eob_df_contained_identifier = json_normalize(
        eob_df_contained_identifier.to_dict(orient= 'records'),
        record_path='type.coding',
        meta = [col for col in eob_df_contained_identifier.columns if col != 'type.coding'],
        record_prefix='type_'
    )
    keep_columns = ['Claim_ID', 'NPI', 'active', 'name', 'resourceType']
    #eob_df_contained_identifier = eob_df_contained_identifier[eob_df_contained_identifier['system'] == 'http://hl7.org/fhir/sid/us-npi']
    eob_df_contained_identifier = eob_df_contained_identifier.reset_index(drop = True)
    eob_df_contained_identifier.rename(columns = {'value':'NPI'}, inplace = True)
    #eob_df_contained_identifier.drop(columns=['status', 'code.coding', 'valueQuantity.value','meta.profile', 'type.coding', 'system', 'id'], inplace = True)
    eob_df_contained_identifier = eob_df_contained_identifier[['Claim_ID', 'NPI', 'active', 'name', 'resourceType', 'type_code']].copy()
    eob_df_contained_identifier['bcda_extract_date'] = pd.Timestamp.today()
    eob_df_contained_identifier['bcda_file'] = file.name
    return eob_df_contained_identifier

eob_contained(eob_df,filepath)

,Claim_ID,NPI,active,name,resourceType,type_code,bcda_extract_date,bcda_file
0,outpatient-5684894761,670067,True,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,PRN,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
1,outpatient-5684894761,1346570710,True,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,npi,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
2,outpatient-5697926656,670067,True,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,PRN,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
3,outpatient-5697926656,1346570710,True,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,npi,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
4,outpatient-5708263442,670067,True,"ARLINGTON ORTHOPEDIC AND SPINE HOSPITAL, LLC",Organization,PRN,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
...,...,...,...,...,...,...,...,...
3303,outpatient-9212710750,1124092036,True,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,npi,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
3304,outpatient-9519284917,450032,True,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,PRN,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
3305,outpatient-9519284917,1124092036,True,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,npi,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
3306,outpatient-9623755765,450032,True,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,PRN,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson
3307,outpatient-9623755765,1124092036,True,CHRISTUS GOOD SHEPHERD MEDICAL CENTER,Organization,npi,2026-03-13 12:22:38.366013,ExplanationOfBenefit_4_20260226182428.ndjson

In [41]:
def getwatermarks():
    query = """
    SELECT TOP 1 date
    FROM BCDA_data.dbo.watermark
    ORDER BY id DESC
    """

    timestamp = pd.read_sql(query, engine).iloc[0,0]

    query = """
        SELECT date
        FROM BCDA_data.dbo.watermark
        ORDER BY ID DESC
        OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY
    """

    timestamp_2 = pd.read_sql(query, engine).iloc[0,0]

    return timestamp, timestamp_2

extract_from, extract_to = getwatermarks()

def eob_contained(eob_df, file):
    eob_df_contained = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='contained',
        meta = 'Claim_ID'
    )
    eob_df_contained_identifier = json_normalize(
        eob_df_contained.to_dict(orient= 'records'),
        record_path='identifier',
        meta = [col for col in eob_df_contained.columns if col != 'identifier']
    )
    eob_df_contained_identifier = json_normalize(
        eob_df_contained_identifier.to_dict(orient= 'records'),
        record_path='type.coding',
        meta = [col for col in eob_df_contained_identifier.columns if col != 'type.coding'],
        record_prefix='type_'
    )
    eob_df_contained_identifier = eob_df_contained_identifier.reset_index(drop = True)
    eob_df_contained_identifier.rename(columns = {'value':'NPI'}, inplace = True)
    #eob_df_contained_identifier.drop(columns=['status', 'code.coding', 'valueQuantity.value','meta.profile', 'type.coding', 'system', 'id'], inplace = True)
    eob_df_contained_identifier = eob_df_contained_identifier[['Claim_ID', 'type_code', 'NPI', 'active', 'name', 'resourceType']].copy()
    eob_df_contained_identifier['bcda_extract_date'] = pd.Timestamp.today()
    eob_df_contained_identifier['bcda_file'] = file.name
    eob_df_contained_identifier['extract_from'] = extract_from
    eob_df_contained_identifier['extract_to'] = extract_to
    return eob_df_contained_identifier

def load_to_sql(df, table_name, file_name, engine):

    df = df.copy()

    try:
        df.to_sql(
            name=table_name,
            con=engine,
            if_exists='append',
            index=False,
            chunksize=5000
        )

    except Exception as e:
        print(f"SQL INSERT FAILED {file_name}")
        print(e)
        raise
contained_df = eob_contained(eob_df, filepath)
load_to_sql(contained_df,'EOB_contained_Staging', filepath.name, engine)
del contained_df

In [44]:
eob_df_sup = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='supportingInfo',
    meta='Claim_ID'
)
eob_df_sup

,sequence,timingDate,category.coding,code.coding,valueQuantity.value,timingPeriod.end,timingPeriod.start,valueQuantity.code,valueQuantity.system,valueQuantity.unit,valueReference.reference,Claim_ID
0,1,2020-01-10,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
1,1,2020-01-31,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890
2,1,2020-01-31,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
3,1,2020-02-21,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27396860372
4,1,2020-04-03,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27548148011
...,...,...,...,...,...,...,...,...,...,...,...,...
68578,2,NaN,"[{'code': 'typeofbill', 'display': 'Type of Bi...","[{'code': '1', 'display': 'Admit thru discharg...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917
68579,3,NaN,"[{'code': 'discharge-status', 'display': 'Disc...","[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917
68580,1,2026-01-23,"[{'code': 'clmrecvddate', 'display': 'Claim Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765
68581,2,NaN,"[{'code': 'typeofbill', 'display': 'Type of Bi...","[{'code': '1', 'display': 'Admit thru discharg...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765
68582,3,NaN,"[{'code': 'discharge-status', 'display': 'Disc...","[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765

In [62]:
eob_df_sup_catcode = eob_df_sup.explode('category.coding')

eob_df_sup_catcode =json_normalize(eob_df_sup_catcode.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode

,sequence,timingDate,code.coding,valueQuantity.value,timingPeriod.end,timingPeriod.start,valueQuantity.code,valueQuantity.system,valueQuantity.unit,valueReference.reference,Claim_ID,category.coding.code,category.coding.display,category.coding.system
0,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
1,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...
2,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
3,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...
4,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100460,3,NaN,"[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
100461,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
100462,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...
100463,2,NaN,"[{'code': '1', 'display': 'Admit thru discharg...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,typeofbill,Type of Bill,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
100464,3,NaN,"[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...

In [ ]:

eob_df_sup_catcode = json_normalize(
    eob_df_sup.to_dict(orient='records'),
    record_path='category.coding',
    meta=[col for col in eob_df_sup.columns if col != 'category.coding']
)
eob_df_sup_catcode

,code,display,system,sequence,timingDate,code.coding,valueQuantity.value,timingPeriod.end,timingPeriod.start,valueQuantity.code,valueQuantity.system,valueQuantity.unit,valueReference.reference,Claim_ID
0,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
1,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
2,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890
3,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890
4,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100460,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,3,NaN,"[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917
100461,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765
100462,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765
100463,typeofbill,Type of Bill,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,2,NaN,"[{'code': '1', 'display': 'Admit thru discharg...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765
100464,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,3,NaN,"[{'code': '01', 'display': 'Discharged to home...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765

In [74]:
eob_df_sup = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='supportingInfo',
    meta='Claim_ID'
)
eob_df_sup_catcode = eob_df_sup.explode('category.coding')
eob_df_sup_catcode =json_normalize(eob_df_sup_catcode.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code = eob_df_sup_catcode.explode('code.coding')
eob_df_sup_catcode_code =json_normalize(eob_df_sup_catcode_code.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code.columns = eob_df_sup_catcode_code.columns.str.replace('.','_')
eob_df_sup_catcode_code.rename(columns={
    'sequence': 'Supp_Sequence'
    
})
eob_df_sup_catcode_code

,sequence,timingDate,code_coding,valueQuantity_value,timingPeriod_end,timingPeriod_start,valueQuantity_code,valueQuantity_system,valueQuantity_unit,valueReference_reference,Claim_ID,category_coding_code,category_coding_display,category_coding_system,code_coding_code,code_coding_display,code_coding_system
0,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN
1,1,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN
2,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN
3,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN
4,1,2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100460,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,01,Discharged to home/self-care (routine charge).,https://bluebutton.cms.gov/resources/variables...
100461,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,clmrecvddate,Claim Received Date,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,NaN,NaN,NaN
100462,1,2026-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,https://bluebutton.cms.gov/resources/variables...,NCH Weekly Claim Processing Date,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN
100463,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,typeofbill,Type of Bill,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,1,Admit thru discharge claim,https://bluebutton.cms.gov/resources/variables...
100464,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...,01,Discharged to home/self-care (routine charge).,https://bluebutton.cms.gov/resources/variables...

In [75]:
eob_df_sup = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='supportingInfo',
    meta='Claim_ID'
)

eob_df_sup_catcode = eob_df_sup.explode('category.coding')

eob_df_sup_catcode =json_normalize(eob_df_sup_catcode.to_dict(orient='records'), meta = 'Claim_ID')

eob_df_sup_catcode_code = eob_df_sup_catcode.explode('code.coding')

eob_df_sup_catcode_code =json_normalize(eob_df_sup_catcode_code.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100465 entries, 0 to 100464
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   sequence                  100465 non-null  int64
 1   timingDate                20418 non-null   object
 2   code.coding               0 non-null       float64
 3   valueQuantity.value       13638 non-null   float64
 4   timingPeriod.end          123 non-null     object
 5   timingPeriod.start        204 non-null     object
 6   valueQuantity.code        196 non-null     object
 7   valueQuantity.system      196 non-null     object
 8   valueQuantity.unit        196 non-null     object
 9   valueReference.reference  4 non-null       object
 10  Claim_ID                  100465 non-null  object
 11  category.coding.code      100465 non-null  object
 12  category.coding.display   100465 non-null  object
 13  category.coding.system    100465 non-null  object
 14  code.coding.code          66201 non-null   object
 15  code.coding.display       65809 non-null   object
 16  code.coding.system        66201 non-null   object
dtypes: float64(2), int64(1), object(14)
memory usage: 13.0+ MB

In [66]:
eob_df_sup_catcode_code = eob_df_sup_catcode.explode('code.coding')

eob_df_sup_catcode_code =json_normalize(eob_df_sup_catcode_code.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code[eob_df_sup_catcode_code['code.coding'].notna()]

Empty DataFrame
Columns: [sequence, timingDate, code.coding, valueQuantity.value, timingPeriod.end, timingPeriod.start, valueQuantity.code, valueQuantity.system, valueQuantity.unit, valueReference.reference, Claim_ID, category.coding.code, category.coding.display, category.coding.system, code.coding.code, code.coding.display, code.coding.system]
Index: []

In [84]:
eob_df_sup_catcode_code = json_normalize(
    eob_df_sup_catcode.to_dict(orient='records'),
    record_path='code.coding',
    meta=[col for col in eob_df_sup_catcode.columns if col != 'code.coding'],
    record_prefix='Code_'
)
eob_df_sup_catcode_code

,Code_code,Code_display,Code_system,sequence,timingDate,valueQuantity.value,timingPeriod.end,timingPeriod.start,valueQuantity.code,valueQuantity.system,valueQuantity.unit,valueReference.reference,Claim_ID,category.coding.code,category.coding.display,category.coding.system
0,RXDINV,Rx dispense invoice,http://terminology.hl7.org/CodeSystem/v3-ActCode,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pde-40548511669,compoundcode,Compound Code,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
1,C,Covered,https://bluebutton.cms.gov/resources/variables...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pde-40548511669,info,Information,http://terminology.hl7.org/CodeSystem/claiminf...
2,C,Covered,https://bluebutton.cms.gov/resources/variables...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pde-40548511669,https://bluebutton.cms.gov/resources/variables...,Drug Coverage Status Code,https://bluebutton.cms.gov/resources/codesyste...
3,0,No Product Selection Indicated (may also have ...,https://bluebutton.cms.gov/resources/variables...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pde-40548511669,info,Information,http://terminology.hl7.org/CodeSystem/claiminf...
4,0,No Product Selection Indicated (may also have ...,https://bluebutton.cms.gov/resources/variables...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pde-40548511669,https://bluebutton.cms.gov/resources/variables...,Dispense as Written (DAW) Product Selection Code,https://bluebutton.cms.gov/resources/codesyste...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,01,Discharged to home/self-care (routine charge).,https://bluebutton.cms.gov/resources/variables...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9212710750,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
66197,1,Admit thru discharge claim,https://bluebutton.cms.gov/resources/variables...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917,typeofbill,Type of Bill,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
66198,01,Discharged to home/self-care (routine charge).,https://bluebutton.cms.gov/resources/variables...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9519284917,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
66199,1,Admit thru discharge claim,https://bluebutton.cms.gov/resources/variables...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,typeofbill,Type of Bill,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
66200,01,Discharged to home/self-care (routine charge).,https://bluebutton.cms.gov/resources/variables...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outpatient-9623755765,discharge-status,Discharge Status,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...

In [ ]:
eob_df_sup = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='supportingInfo',
    meta='Claim_ID'
)
eob_df_sup_catcode = eob_df_sup.explode('category.coding')
eob_df_sup_catcode =json_normalize(eob_df_sup_catcode.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code = eob_df_sup_catcode.explode('code.coding')
eob_df_sup_catcode_code =json_normalize(eob_df_sup_catcode_code.to_dict(orient='records'), meta = 'Claim_ID')
eob_df_sup_catcode_code.columns = eob_df_sup_catcode_code.columns.str.replace('.','_')
eob_df_sup_catcode_code.rename(columns={
    'sequence': 'Supp_Sequence'
    
})
eob_df_sup_catcode_code=eob_df_sup_catcode_code[['Claim_ID']]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100465 entries, 0 to 100464
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   sequence                  100465 non-null  int64
 1   timingDate                20418 non-null   object
 2   code_coding               0 non-null       float64
 3   valueQuantity_value       13638 non-null   float64
 4   timingPeriod_end          123 non-null     object
 5   timingPeriod_start        204 non-null     object
 6   valueQuantity_code        196 non-null     object
 7   valueQuantity_system      196 non-null     object
 8   valueQuantity_unit        196 non-null     object
 9   valueReference_reference  4 non-null       object
 10  Claim_ID                  100465 non-null  object
 11  category_coding_code      100465 non-null  object
 12  category_coding_display   100465 non-null  object
 13  category_coding_system    100465 non-null  object
 14  code_coding_code          66201 non-null   object
 15  code_coding_display       65809 non-null   object
 16  code_coding_system        66201 non-null   object
dtypes: float64(2), int64(1), object(14)
memory usage: 13.0+ MB

In [110]:
eob_df_procedure = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='procedure',
    meta = 'Claim_ID',
    
)
eob_df_procedure_2 = eob_df_procedure.explode('procedureCodeableConcept.coding')

eob_df_procedure_2 =json_normalize(
    eob_df_procedure_2.to_dict(orient='records')
)
eob_df_procedure_2

,date,sequence,Claim_ID,procedureCodeableConcept.coding.code,procedureCodeableConcept.coding.system,procedureCodeableConcept.coding.display
0,2025-03-04T00:00:00+00:00,1,inpatient-8626292891,3E02340,http://www.cms.gov/Medicare/Coding/ICD10,NaN
1,2025-03-04T00:00:00+00:00,1,inpatient-8626292891,3E02340,http://hl7.org/fhir/sid/icd-10,NaN
2,2025-08-11T00:00:00+00:00,1,inpatient-9140805680,0SG10A0,http://www.cms.gov/Medicare/Coding/ICD10,"""FUSION 2-4 L JT W INTBD FUS DEV, ANT APPR A C..."
3,2025-08-11T00:00:00+00:00,1,inpatient-9140805680,0SG10A0,http://hl7.org/fhir/sid/icd-10,"""FUSION 2-4 L JT W INTBD FUS DEV, ANT APPR A C..."
4,2025-08-11T00:00:00+00:00,2,inpatient-9140805680,0SG1071,http://www.cms.gov/Medicare/Coding/ICD10,"""FUSION 2-4 L JT W AUTOL SUB, POST APPR P COL,..."
...,...,...,...,...,...,...
317,2024-04-16T00:00:00+00:00,2,inpatient-7978128056,0FT40ZZ,http://hl7.org/fhir/sid/icd-10,"""RESECTION OF GALLBLADDER, OPEN APPROACH"""
318,2024-04-18T00:00:00+00:00,3,inpatient-7978128056,0WQF0ZZ,http://www.cms.gov/Medicare/Coding/ICD10,"""REPAIR ABDOMINAL WALL, OPEN APPROACH"""
319,2024-04-18T00:00:00+00:00,3,inpatient-7978128056,0WQF0ZZ,http://hl7.org/fhir/sid/icd-10,"""REPAIR ABDOMINAL WALL, OPEN APPROACH"""
320,2024-04-22T00:00:00+00:00,4,inpatient-7978128056,3E0436Z,http://www.cms.gov/Medicare/Coding/ICD10,"""INTRODUCTION OF NUTRITIONAL INTO CENTRAL VEIN..."
321,2024-04-22T00:00:00+00:00,4,inpatient-7978128056,3E0436Z,http://hl7.org/fhir/sid/icd-10,"""INTRODUCTION OF NUTRITIONAL INTO CENTRAL VEIN..."

In [ ]:
eob_df_procedure = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='procedure',
    meta = 'Claim_ID',
    
)
eob_df_procedure_2 = eob_df_procedure.explode('procedureCodeableConcept.coding')

eob_df_procedure_2 =json_normalize(
    eob_df_procedure_2.to_dict(orient='records')
)
#eob_df_procedure_2 = json_normalize(
#    eob_df_procedure.to_dict(orient='records'),
#    record_path= 'procedureCodeableConcept.coding',
#    meta = [col for col in eob_df_procedure.columns if col != 'procedureCodeableConcept.coding']
#)
eob_df_procedure_2.rename(columns ={
    'procedureCodeableConcept.coding.code': 'procedure_code',
    'procedureCodeableConcept.coding.display': 'procedure'
}, inplace = True)
cols = [
    'Claim_ID',
    'sequence',
    'procedure_code',
    'procedure',
    'date'
]
eob_df_procedure_2 = eob_df_procedure_2.reindex(columns=cols)
if 'procedure' in eob_df_procedure_2.columns:
    eob_df_procedure_2['procedure'] = eob_df_procedure_2['procedure'].str.replace('"', '')
eob_df_procedure_2

,Claim_ID,sequence,procedure_code,procedure,date
0,inpatient-8626292891,1,3E02340,NaN,2025-03-04T00:00:00+00:00
1,inpatient-8626292891,1,3E02340,NaN,2025-03-04T00:00:00+00:00
2,inpatient-9140805680,1,0SG10A0,"FUSION 2-4 L JT W INTBD FUS DEV, ANT APPR A CO...",2025-08-11T00:00:00+00:00
3,inpatient-9140805680,1,0SG10A0,"FUSION 2-4 L JT W INTBD FUS DEV, ANT APPR A CO...",2025-08-11T00:00:00+00:00
4,inpatient-9140805680,2,0SG1071,"FUSION 2-4 L JT W AUTOL SUB, POST APPR P COL, ...",2025-08-11T00:00:00+00:00
...,...,...,...,...,...
317,inpatient-7978128056,2,0FT40ZZ,"RESECTION OF GALLBLADDER, OPEN APPROACH",2024-04-16T00:00:00+00:00
318,inpatient-7978128056,3,0WQF0ZZ,"REPAIR ABDOMINAL WALL, OPEN APPROACH",2024-04-18T00:00:00+00:00
319,inpatient-7978128056,3,0WQF0ZZ,"REPAIR ABDOMINAL WALL, OPEN APPROACH",2024-04-18T00:00:00+00:00
320,inpatient-7978128056,4,3E0436Z,"INTRODUCTION OF NUTRITIONAL INTO CENTRAL VEIN,...",2024-04-22T00:00:00+00:00
321,inpatient-7978128056,4,3E0436Z,"INTRODUCTION OF NUTRITIONAL INTO CENTRAL VEIN,...",2024-04-22T00:00:00+00:00

In [ ]:
eob_df_fac_ext = json_normalize(
    eob_df.to_dict(orient= 'records'),
    record_path= 'facility'
)

In [ ]:
def eob_basetable(eob_df, file): list_columns = [ col for col in eob_df.columns if isinstance(eob_df[col].dropna().iloc[0], list) ] eob_basetable = eob_df.drop(columns= list_columns) eob_basetable['bcda_extract_date'] = pd.Timestamp.today() eob_basetable['bcda_file'] = file.name eob_basetable['extract_from'] = extract_from eob_basetable['extract_to'] = extract_to return eob_basetable

In [24]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item

,adjudication,careTeamSequence,extension,sequence,category.coding,locationCodeableConcept.coding,locationCodeableConcept.extension,productOrService.coding,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,diagnosisSequence,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID
0,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': 'V', 'display': 'Pneumococcal/flu va...","[{'code': '60', 'display': 'Mass Immunization ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '90653', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
1,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,2,"[{'code': 'V', 'display': 'Pneumococcal/flu va...","[{'code': '60', 'display': 'Mass Immunization ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': 'G0008', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395
2,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': '1', 'display': 'Medical care', 'sys...","[{'code': '11', 'display': 'Office. Location, ...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '99214', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-10,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890
3,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,"[{'code': '2', 'display': 'Surgery', 'system':...","[{'code': '22', 'display': 'Outpatient Hospita...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '64493', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,"[{'coding': [{'code': '50', 'system': 'https:/...",NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
4,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,2,"[{'code': '2', 'display': 'Surgery', 'system':...","[{'code': '22', 'display': 'Outpatient Hospita...",[{'url': 'https://bluebutton.cms.gov/resources...,"[{'code': '64494', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,"[{'coding': [{'code': '50', 'system': 'https:/...",NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36113,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,NaN,NaN,"[{'code': '36415', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,"[{'code': '0300', 'display': 'Laboratory-gener...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36114,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,2,NaN,NaN,NaN,"[{'code': 'G0463', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,"[{'code': '0510', 'display': 'Clinic-general c...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36115,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,3,NaN,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fh...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,"[{'code': '0001', 'display': 'Total charge', '...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9519284917
36116,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,NaN,NaN,"[{'code': 'G0463', 'system': 'https://bluebutt...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2026-01-12,TX,"[{'code': '0510', 'display': 'Clinic-general c...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9623755765
36117,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,2,NaN,NaN,NaN,"[{'code': 'NULL', 'system': 'http://hl7.org/fh...",[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,"[{'code': '0001', 'display': 'Total charge', '...",[{'url': 'https://bluebutton.cms.gov/resources...,NaN,outpatient-9623755765

In [36]:

eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)

eob_df_item_category_coding = eob_df_item.explode('category.coding')
eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')
eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')
eob_df_item_revenue_coding = eob_df_item_product_coding.explode('revenue.coding')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('revenue.extension')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier')


eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier.coding')

eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding

,adjudication,careTeamSequence,extension,sequence,locationCodeableConcept.extension,productOrService.extension,quantity.value,servicedPeriod.end,servicedPeriod.start,modifier,diagnosisSequence,servicedDate,locationAddress.state,revenue.coding,revenue.extension,informationSequence,Claim_ID,category.coding.code,category.coding.display,category.coding.system,locationCodeableConcept.coding.code,locationCodeableConcept.coding.display,locationCodeableConcept.coding.system,productOrService.coding.code,productOrService.coding.system,modifier.coding,category.coding,locationCodeableConcept.coding,productOrService.coding.display,revenue.coding.code,revenue.coding.display,revenue.coding.system,revenue.extension.url,revenue.extension.valueCoding.code,revenue.extension.valueCoding.display,revenue.extension.valueCoding.system,modifier.coding.code,modifier.coding.system,modifier.coding.version,modifier.coding.display
0,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,90653,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[{'category': {'coding': [{'code': 'denialreas...,[2],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2019-12-27,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27286904395,V,Pneumococcal/flu vaccine,https://bluebutton.cms.gov/resources/variables...,60,Mass Immunization Center. A location where pro...,https://bluebutton.cms.gov/resources/variables...,G0008,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-10,2020-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545890,1,Medical care,https://bluebutton.cms.gov/resources/variables...,11,"Office. Location, other than a hospital, skill...",https://bluebutton.cms.gov/resources/variables...,99214,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,1,[{'url': 'https://bluebutton.cms.gov/resources...,[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64493,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN
4,[{'category': {'coding': [{'code': 'denialreas...,[3],[{'url': 'https://bluebutton.cms.gov/resources...,2,[{'url': 'https://bluebutton.cms.gov/resources...,[{'url': 'http://hl7.org/fhir/StructureDefinit...,1.0,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carrier-27334545891,2,Surgery,https://bluebutton.cms.gov/resources/variables...,22,Outpatient Hospital. A portion of a hospital w...,https://bluebutton.cms.gov/resources/variables...,64494,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,https://bluebutton.cms.gov/resources/codesyste...,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39502,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,36415,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,0300,Laboratory-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,N,Packaged incidental service (no separate APC p...,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN
39503,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,2,NaN,[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2025-12-22,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN
39504,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,3,NaN,[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9519284917,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN
39505,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,[{'url': 'https://bluebutton.cms.gov/resources...,1,NaN,[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,2026-01-12,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,G0463,https://bluebutton.cms.gov/resources/codesyste...,NaN,NaN,NaN,NaN,0510,Clinic-general classification,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,V,Medical visit to clinic or emergency department,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN
39506,"[{'amount': {'currency': 'USD', 'value': 0}, '...",NaN,NaN,2,NaN,[{'url': 'http://hl7.org/fhir/StructureDefinit...,0.0,NaN,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN,outpatient-9623755765,NaN,NaN,NaN,NaN,NaN,NaN,NULL,http://hl7.org/fhir/StructureDefinition/data-a...,NaN,NaN,NaN,NaN,0001,Total charge,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,A,Services not paid under OPPS; uses a different...,https://bluebutton.cms.gov/resources/variables...,NaN,NaN,NaN,NaN

In [ ]:

eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)

eob_df_item_category_coding = eob_df_item.explode('category.coding')
eob_df_item_location_coding = eob_df_item_category_coding.explode('locationCodeableConcept.coding')
eob_df_item_product_coding = eob_df_item_location_coding.explode('productOrService.coding')
eob_df_item_revenue_coding = eob_df_item_product_coding.explode('revenue.coding')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('revenue.extension')
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier')


eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding = eob_df_item_revenue_coding.explode('modifier.coding')

eob_df_item_revenue_coding = json_normalize(
    eob_df_item_revenue_coding.to_dict(orient='records')
)
eob_df_item_revenue_coding


eob_df_item_revenue_coding.rename(columns = {
    'sequence': 'item_sequence',
    'quantity.value': 'quantity',
    'category.coding.code': 'category_code',
    'category.coding.display': 'category_display',
    'locationCodeableConcept.coding.code': 'location_code',
    'locationCodeableConcept.coding.display': 'location_display',
    'productOrService.coding.code': 'product_code',
    'productOrService.coding.display': 'product_display',
    'revenue.coding.code': 'revenue_code',
    'revenue.coding.display': 'revenue_display',
    'servicedPeriod.end': 'serviceperiod_end',
    'servicedPeriod.start': 'serviceperiod_start',
    'revenue.extension.valueCoding.display': 'revenue_ext_display',
    'revenue.extension.valueCoding.code': 'revenue_ext_code',
    'modifier.coding.code': 'modifier_code',
    'modifier.coding.version': 'modifier_version'
}, inplace = True)
eob_df_item_revenue_coding = eob_df_item_revenue_coding[[
    'Claim_ID',
    'item_sequence',
    'careTeamSequence',
    'diagnosisSequence',
    'product_code',
    'product_display',
    'revenue_code',
    'revenue_display',
    'revenue_ext_code',
    'revenue_ext_display',
    'category_code',
    'category_display',
    'modifier_code',
    'modifier_version',
    'location_code',
    'location_display',
    'serviceperiod_start',
    'serviceperiod_end',
    'servicedDate'
]].copy()
eob_df_item_revenue_coding['careTeamSequence'] = eob_df_item_revenue_coding['careTeamSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)
eob_df_item_revenue_coding['diagnosisSequence'] = eob_df_item_revenue_coding['diagnosisSequence'].apply(lambda x: x[0] if isinstance(x, list) else x)


eob_df_item_revenue_coding

,Claim_ID,item_sequence,careTeamSequence,diagnosisSequence,product_code,product_display,revenue_code,revenue_display,revenue_ext_code,revenue_ext_display,category_code,category_display,modifier_code,modifier_version,location_code,serviceperiod_start,serviceperiod_end,servicedDate,location_display
0,carrier-27286904395,1,2.0,NaN,90653,NaN,NaN,NaN,NaN,NaN,V,Pneumococcal/flu vaccine,NaN,NaN,60,2019-12-27,2019-12-27,NaN,Mass Immunization Center. A location where pro...
1,carrier-27286904395,2,2.0,NaN,G0008,NaN,NaN,NaN,NaN,NaN,V,Pneumococcal/flu vaccine,NaN,NaN,60,2019-12-27,2019-12-27,NaN,Mass Immunization Center. A location where pro...
2,carrier-27334545890,1,3.0,NaN,99214,NaN,NaN,NaN,NaN,NaN,1,Medical care,NaN,NaN,11,2020-01-10,2020-01-10,NaN,"Office. Location, other than a hospital, skill..."
3,carrier-27334545891,1,3.0,NaN,64493,NaN,NaN,NaN,NaN,NaN,2,Surgery,50,9,22,2020-01-09,2020-01-09,NaN,Outpatient Hospital. A portion of a hospital w...
4,carrier-27334545891,2,3.0,NaN,64494,NaN,NaN,NaN,NaN,NaN,2,Surgery,50,9,22,2020-01-09,2020-01-09,NaN,Outpatient Hospital. A portion of a hospital w...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39502,outpatient-9519284917,1,NaN,NaN,36415,NaN,0300,Laboratory-general classification,N,Packaged incidental service (no separate APC p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-22,NaN
39503,outpatient-9519284917,2,NaN,NaN,G0463,NaN,0510,Clinic-general classification,V,Medical visit to clinic or emergency department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-22,NaN
39504,outpatient-9519284917,3,NaN,NaN,NULL,NaN,0001,Total charge,A,Services not paid under OPPS; uses a different...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39505,outpatient-9623755765,1,NaN,NaN,G0463,NaN,0510,Clinic-general classification,V,Medical visit to clinic or emergency department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-12,NaN
39506,outpatient-9623755765,2,NaN,NaN,NULL,NaN,0001,Total charge,A,Services not paid under OPPS; uses a different...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
if 'procedure' in eob_df.columns:
    print('yes')
else:
    print('no')

yes

In [ ]:
eob_basetable = eob_df.explode('facility_extension')
eob_basetable = eob_basetable.explode('billablePeriod_extension')
eob_basetable = eob_basetable.explode('identifier')
eob_basetable

,benefitBalance,careTeam,created,diagnosis,disposition,extension,Claim_ID,insurance,item,outcome,resourceType,status,supportingInfo,total,use,billablePeriod_end,billablePeriod_start,insurer_identifier_value,meta_lastUpdated,meta_profile,Patient_ID,payment_amount_currency,payment_amount_value,provider_identifier_system,provider_identifier_value,type_coding,referral_display,referral_identifier_type_coding,referral_identifier_value,provider_display,provider_type,facility_display,facility_extension,facility_identifier_type_coding,facility_identifier_value,payment_date,contained,billablePeriod_extension,provider_reference,subType_coding,subType_text,procedure,identifier.system,identifier.type.coding,identifier.value,facility_extension.url,facility_extension.valueCoding.code,facility_extension.valueCoding.display,facility_extension.valueCoding.system,billablePeriod_extension.url,billablePeriod_extension.valueCoding.code,billablePeriod_extension.valueCoding.display,billablePeriod_extension.valueCoding.system
0,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",27286904395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'identifier': {'type': {'coding...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27286904395,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2019-12-27,2019-12-27,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,64.42,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/identifie...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",17707104678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",27334545890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545890,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 60.93...",claim,2020-01-10,2020-01-10,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,0.00,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/identifie...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",17870735847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'ZACHARY Q. BOTONE M...,2026-02-26T18:22:18+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,01,[{'url': 'https://bluebutton.cms.gov/resources...,carrier-27334545891,[{'coverage': {'reference': 'Coverage/part-b-4...,[{'adjudication': [{'category': {'coding': [{'...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 0}, '...",claim,2020-01-09,2020-01-09,CMS,2020-01-01T00:00:00.000+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,431397073,USD,164.60,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,"[{'code': '71', 'display': 'Local carrier non-...",ZACHARY Q. BOTONE MD,"[{'code': 'npi', 'display': 'National Provider...",1063614337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bluebutton.cms.gov/resources/variables...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",27334545891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40340,"[{'category': {'coding': [{'code': '1', 'displ...",[{'provider': {'display': 'SNEHAL SHRIVASTAVA ...,2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9212710750,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 8}, '...",claim,2025-10-13,2025-10-13,CMS,2025-10-31T16:28:56.430+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,7.84,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/identifie...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",37833817202,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
40341,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",9519284917,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
40342,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9519284917,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 507},...",claim,2025-12-22,2025-12-22,CMS,2026-01-16T16:42:31.654+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,96.48,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/identifie...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",38814677001,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
40343,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/variables...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",9623755765,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...
40344,"[{'category': {'coding': [{'code': '1', 'displ...","[{'provider': {'display': 'LEAH GATDULA MD', '...",2026-02-26T18:23:04+00:00,[{'diagnosisCodeableConcept': {'coding': [{'co...,NaN,[{'url': 'https://bluebutton.cms.gov/resources...,outpatient-9623755765,[{'coverage': {'reference': 'Coverage/part-b-7...,[{'adjudication': [{'amount': {'currency': 'US...,complete,ExplanationOfBenefit,active,[{'category': {'coding': [{'code': 'clmrecvdda...,"[{'amount': {'currency': 'USD', 'value': 499},...",claim,2026-01-12,2026-01-12,CMS,2026-01-30T17:06:01.301+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,73564997,USD,104.33,NaN,NaN,"[{'code': '40', 'display': 'Hospital Outpatien...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'active': True, 'id': 'provider-org', 'ident...",NaN,#provider-org,"[{'code': 'outpatient', 'system': 'http://hl7....",Outpatient,NaN,https://bluebutton.cms.gov/resources/identifie...,"[{'code': 'uc', 'display': 'Unique Claim ID', ...",39004027649,https://bluebutton.cms.gov/resources/variables...,1,Hospital,https://bluebutton.cms.gov/resources/variables...,https://bluebutton.cms.gov/resources/variables...,3,Final bill,https://bluebutton.cms.gov/resources/variables...

In [41]:
eob_basetable = eob_df.explode('facility_extension')
eob_basetable = eob_basetable.explode('billablePeriod_extension')
eob_basetable = json_normalize(
    eob_basetable.to_dict(orient='records')
)
eob_basetable = eob_basetable.rename(columns={
    'id': 'Claim_ID',
    'facility_extension.valueCoding.code': 'facility_Code_ext',
    'facility_extension.valueCoding.display': 'facility_Display',
    'billablePeriod_extension.valueCoding.code': 'adjustment_code',
    'billablePeriod_extension.valueCoding.display': 'adjustment_type'
})
eob_basetable.columns = eob_basetable.columns.str.replace('.', '_')
base_columns = [
    'Claim_ID', 
    'Patient_ID',
    'disposition',
    'created',
    'outcome',
    'resourceType',
    'status',
    'use',
    'billablePeriod_start',
    'billablePeriod_end',
    'adjustment_type',
    'adjustment_code',
    'insurer_identifier_value',
    'meta_lastUpdated',
    'payment_amount_currency',
    'payment_amount_value',
    'payment_date',
    'provider_identifier_system',
    'provider_identifier_value',
    'provider_reference',
    'provider_display',
    'referral_display',
    'referral_identifier_value',
    'facility_identifier_value',
    'facility_Code_ext',
    'facility_Display',
    'subType_text',
]
eob_basetable = eob_basetable[base_columns]
eob_basetable

,Claim_ID,Patient_ID,disposition,created,outcome,resourceType,status,use,billablePeriod_start,billablePeriod_end,adjustment_type,adjustment_code,insurer_identifier_value,meta_lastUpdated,payment_amount_currency,payment_amount_value,payment_date,provider_identifier_system,provider_identifier_value,provider_reference,provider_display,referral_display,referral_identifier_value,facility_identifier_value,facility_Code_ext,facility_Display,subType_text
0,carrier-27286904395,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2019-12-27,2019-12-27,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,64.42,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,carrier-27334545890,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-10,2020-01-10,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,0.00,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
2,carrier-27334545891,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-09,2020-01-09,NaN,NaN,CMS,2020-01-01T00:00:00.000+00:00,USD,164.60,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
3,carrier-27396860372,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-23,2020-01-23,NaN,NaN,CMS,2020-03-01T04:45:59.805+00:00,USD,96.30,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,ZACHARY Q. BOTONE MD,1063614337,NaN,NaN,NaN,NaN
4,carrier-27548148011,431397073,01,2026-02-26T18:22:18+00:00,complete,ExplanationOfBenefit,active,claim,2020-01-30,2020-01-30,NaN,NaN,CMS,2020-04-12T22:53:20.402+00:00,USD,111.94,NaN,https://bluebutton.cms.gov/resources/variables...,UNKNOWN,NaN,NaN,TROY DALE FOSTER D.O.,1134415169,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,outpatient-9174161667,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-09-08,2025-09-08,Final bill,3,CMS,2025-09-26T16:54:02.790+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16847,outpatient-9212710749,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-10-01,2025-10-01,Final bill,3,CMS,2025-10-31T16:28:56.430+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16848,outpatient-9212710750,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-10-13,2025-10-13,Final bill,3,CMS,2025-10-31T16:28:56.430+00:00,USD,7.84,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16849,outpatient-9519284917,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2025-12-22,2025-12-22,Final bill,3,CMS,2026-01-16T16:42:31.654+00:00,USD,96.48,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient
16850,outpatient-9623755765,73564997,NaN,2026-02-26T18:23:04+00:00,complete,ExplanationOfBenefit,active,claim,2026-01-12,2026-01-12,Final bill,3,CMS,2026-01-30T17:06:01.301+00:00,USD,104.33,NaN,NaN,NaN,#provider-org,NaN,NaN,NaN,NaN,1,Hospital,Outpatient

In [1]:
eob_basetable

NameError: name 'eob_basetable' is not defined

In [54]:
eob_df_identifier = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path=['identifier'],
    meta='Claim_ID'
)
eob_df_identifier=eob_df_identifier.explode('type.coding')
eob_df_identifier=json_normalize(
    eob_df_identifier.to_dict(orient='records')
)
eob_df_identifier= eob_df_identifier[['Claim_ID', 'value', 'system']]
eob_df_identifier

,Claim_ID,value,system
0,carrier-27286904395,27286904395,https://bluebutton.cms.gov/resources/variables...
1,carrier-27286904395,17707104678,https://bluebutton.cms.gov/resources/identifie...
2,carrier-27334545890,27334545890,https://bluebutton.cms.gov/resources/variables...
3,carrier-27334545890,17870735847,https://bluebutton.cms.gov/resources/identifie...
4,carrier-27334545891,27334545891,https://bluebutton.cms.gov/resources/variables...
...,...,...,...
40340,outpatient-9212710750,37833817202,https://bluebutton.cms.gov/resources/identifie...
40341,outpatient-9519284917,9519284917,https://bluebutton.cms.gov/resources/variables...
40342,outpatient-9519284917,38814677001,https://bluebutton.cms.gov/resources/identifie...
40343,outpatient-9623755765,9623755765,https://bluebutton.cms.gov/resources/variables...
40344,outpatient-9623755765,39004027649,https://bluebutton.cms.gov/resources/identifie...

In [74]:
eob_careteam = json_normalize(
    eob_df.to_dict(orient= 'records'),
    record_path= 'careTeam',
    meta = 'Claim_ID'
)
eob_careteam=eob_careteam.explode('provider.identifier.type.coding')
eob_careteam=eob_careteam.explode('role.coding')
eob_careteam=eob_careteam.explode('qualification.coding')
eob_careteam = json_normalize(
    eob_careteam.to_dict(orient='records')
)
eob_careteam.columns = eob_careteam.columns.str.replace('.', '_')
eob_careteam.rename(columns = {
    'sequence': 'careteam_sequence',
    'qualification_coding_code': 'qualification_code',
    'qualification_coding_display': 'qualification_display',
    'role_coding_display': 'role'
}, inplace = True)
eob_careteam = eob_careteam[['Claim_ID', 'careteam_sequence', 'provider_identifier_value', 'qualification_code', 'qualification_display', 'role']]
eob_careteam['careteam_sequence'] = eob_careteam['careteam_sequence'].apply(
    lambda x: x[0] if isinstance(x, list) else x
)
eob_careteam

,Claim_ID,careteam_sequence,provider_identifier_value,qualification_code,qualification_display,role
0,carrier-27286904395,1,NaN,NaN,NaN,Referring
1,carrier-27286904395,2,1205841103,291U00000X,Clinical Medical Laboratory,Performing provider
2,carrier-27286904395,2,1205841103,C1,Centralized flu,Performing provider
3,carrier-27334545890,1,1063614337,207Q00000X,Family Medicine Physician,Referring
4,carrier-27334545890,2,690160,NaN,NaN,Referring
...,...,...,...,...,...,...
41536,outpatient-9212710750,1,1669882882,207RN0300X,Nephrology Physician,Attending
41537,outpatient-9519284917,1,1740857291,390200000X,Student in an Organized Health Care Education/...,Attending
41538,outpatient-9519284917,2,1740857291,390200000X,Student in an Organized Health Care Education/...,Operating
41539,outpatient-9623755765,1,1740857291,390200000X,Student in an Organized Health Care Education/...,Attending
41540,outpatient-9623755765,2,1740857291,390200000X,Student in an Organized Health Care Education/...,Operating

In [69]:
eob_careteam = json_normalize(
    eob_df.to_dict(orient= 'records'),
    record_path= 'careTeam',
    meta = 'Claim_ID'
)
eob_careteam_provider_coding = json_normalize(
    eob_careteam.to_dict(orient= 'records'),
    record_path= 'provider.identifier.type.coding',
    meta = [col for col in eob_careteam.columns if col != 'provider.identifier.type.coding']
)
eob_careteam_provider_coding_qual_0 = eob_careteam_provider_coding.explode('qualification.coding')
eob_careteam_provider_coding_qual = json_normalize(
    eob_careteam_provider_coding_qual_0.to_dict(orient='records'),
    meta=[col for col in eob_careteam_provider_coding_qual_0.columns if col !='qualification.coding']
)
eob_careteam_provider_coding_qual =eob_careteam_provider_coding_qual.drop(columns='qualification.coding')
eob_careteam_provider_coding_qual
eob_careteam_provider_coding_qual_role_0 = eob_careteam_provider_coding_qual.explode('role.coding')
eob_careteam_provider_coding_qual_role = json_normalize(
    eob_careteam_provider_coding_qual_role_0.to_dict(orient='records'),
    meta=[col for col in eob_careteam_provider_coding_qual_role_0.columns if col != 'role.coding']
)
eob_careteam_provider_coding_qual_role.columns = eob_careteam_provider_coding_qual_role.columns.str.replace('.', '_')
eob_careteam_provider_coding_qual_role = eob_careteam_provider_coding_qual_role.drop(columns = 'extension')
#eob_careteam_provider_coding_qual_role.drop(columns = ['system','code' , 'display', 'qualification_coding_system','role_coding_code','role_coding_system'], inplace = True)
eob_careteam_provider_coding_qual_role.rename(columns = {
    'sequence': 'careteam_sequence',
    'qualification_coding_code': 'qualification_code',
    'qualification_coding_display': 'qualification_display',
    'role_coding_display': 'role'
}, inplace = True)
eob_careteam_provider_coding_qual_role = eob_careteam_provider_coding_qual_role[['Claim_ID', 'careteam_sequence', 'provider_identifier_value', 'qualification_code', 'qualification_display', 'role']]
eob_careteam_provider_coding_qual_role['careteam_sequence'] = eob_careteam_provider_coding_qual_role['careteam_sequence'].apply(
    lambda x: x[0] if isinstance(x, list) else x
)
eob_careteam_provider_coding_qual_role

,Claim_ID,careteam_sequence,provider_identifier_value,qualification_code,qualification_display,role
0,carrier-27286904395,1,NaN,NaN,NaN,Referring
1,carrier-27286904395,2,1205841103,291U00000X,Clinical Medical Laboratory,Performing provider
2,carrier-27286904395,2,1205841103,C1,Centralized flu,Performing provider
3,carrier-27334545890,1,1063614337,207Q00000X,Family Medicine Physician,Referring
4,carrier-27334545890,2,690160,NaN,NaN,Referring
...,...,...,...,...,...,...
41536,outpatient-9212710750,1,1669882882,207RN0300X,Nephrology Physician,Attending
41537,outpatient-9519284917,1,1740857291,390200000X,Student in an Organized Health Care Education/...,Attending
41538,outpatient-9519284917,2,1740857291,390200000X,Student in an Organized Health Care Education/...,Operating
41539,outpatient-9623755765,1,1740857291,390200000X,Student in an Organized Health Care Education/...,Attending
41540,outpatient-9623755765,2,1740857291,390200000X,Student in an Organized Health Care Education/...,Operating

In [81]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = eob_df_item_adjudication.explode('reason.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('category.coding')
eob_df_item_adjudication = eob_df_item_adjudication.explode('extension')

eob_df_item_adjudication = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records')
)
eob_df_item_adjudication = eob_df_item_adjudication[
    ~eob_df_item_adjudication['category.coding.code'].str.contains('http', na=False)
]
eob_df_item_adjudication.rename(columns = {
    'amount.currency': 'currency_type',
    'amount.value': 'amount',
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display',
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display',
    'category.coding.display': 'display'
}, inplace = True)
eob_df_item_adjudication = eob_df_item_adjudication[['Claim_ID', 'display', 'currency_type', 'amount', 'reason_code', 'reason_display', 'LINE_PMT_80_100_CD', 'LINE_PMT_80_100_display']]
eob_df_item_adjudication

,Claim_ID,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
0,carrier-27286904395,Denial Reason,NaN,NaN,0,N/A,NaN,NaN
1,carrier-27286904395,Benefit Amount,USD,48.01,NaN,NaN,1,100%
3,carrier-27286904395,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
5,carrier-27286904395,Paid to provider,USD,48.01,NaN,NaN,NaN,NaN
7,carrier-27286904395,Deductible,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
688746,outpatient-9623755765,Prior payer paid,USD,0.00,NaN,NaN,NaN,NaN
688748,outpatient-9623755765,Paid to provider,USD,0.00,NaN,NaN,NaN,NaN
688750,outpatient-9623755765,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
688752,outpatient-9623755765,Paid by patient,USD,0.00,NaN,NaN,NaN,NaN
688754,outpatient-9623755765,Submitted Amount,USD,0.00,NaN,NaN,NaN,NaN

In [76]:
eob_df_item = json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='item',
    meta = 'Claim_ID'
)
eob_df_item_adjudication = json_normalize(
    eob_df_item.to_dict(orient='records'),
    record_path='adjudication',
    meta = 'Claim_ID'
)
eob_df_item_adjudication_reason = json_normalize(
    eob_df_item_adjudication.to_dict(orient='records'),
    record_path='category.coding',
    meta = [col for col in eob_df_item_adjudication.columns if col != 'category.coding']
)
eob_df_item_adjudication_reason_coding = eob_df_item_adjudication_reason.explode('reason.coding')
eob_df_item_adjudication_reason_coding = json_normalize(
    eob_df_item_adjudication_reason_coding.to_dict(orient='records'),
    meta = 'Claim_ID',
)
eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding.explode('extension')
eob_df_item_adjudication_reason_coding_ext = json_normalize(
    eob_df_item_adjudication_reason_coding_ext.to_dict(orient='records'),
    meta = 'Claim_ID'
)
eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding_ext[
    ~eob_df_item_adjudication_reason_coding_ext['code'].str.contains('http', na=False)
]
#eob_df_item_adjudication_reason_coding_ext.drop(columns = [ 'code', 'system', 'extension', 'reason.coding.system', 'extension.url', 'extension.valueCoding.system', 'reason.coding'], inplace = True)
eob_df_item_adjudication_reason_coding_ext.rename(columns = {
    'amount.currency': 'currency_type',
    'amount.value': 'amount',
    'reason.coding.code': 'reason_code',
    'reason.coding.display': 'reason_display',
    'extension.valueCoding.code': 'LINE_PMT_80_100_CD',
    'extension.valueCoding.display': 'LINE_PMT_80_100_display'
}, inplace = True)
eob_df_item_adjudication_reason_coding_ext = eob_df_item_adjudication_reason_coding_ext[['Claim_ID', 'display', 'currency_type', 'amount', 'reason_code', 'reason_display', 'LINE_PMT_80_100_CD', 'LINE_PMT_80_100_display']]
eob_df_item_adjudication_reason_coding_ext

,Claim_ID,display,currency_type,amount,reason_code,reason_display,LINE_PMT_80_100_CD,LINE_PMT_80_100_display
0,carrier-27286904395,Denial Reason,NaN,NaN,0,N/A,NaN,NaN
1,carrier-27286904395,Benefit Amount,USD,48.01,NaN,NaN,1,100%
3,carrier-27286904395,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
5,carrier-27286904395,Paid to provider,USD,48.01,NaN,NaN,NaN,NaN
7,carrier-27286904395,Deductible,USD,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
688746,outpatient-9623755765,Prior payer paid,USD,0.00,NaN,NaN,NaN,NaN
688748,outpatient-9623755765,Paid to provider,USD,0.00,NaN,NaN,NaN,NaN
688750,outpatient-9623755765,Paid to patient,USD,0.00,NaN,NaN,NaN,NaN
688752,outpatient-9623755765,Paid by patient,USD,0.00,NaN,NaN,NaN,NaN
688754,outpatient-9623755765,Submitted Amount,USD,0.00,NaN,NaN,NaN,NaN

In [129]:
eob_df_diag =json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='diagnosis',
    meta = 'Claim_ID'
)
eob_df_diag_diagnosis = eob_df_diag.explode('diagnosisCodeableConcept.coding')
diagnosisCodeableConcept_type = eob_df_diag_diagnosis.explode('type')
if 'extension' in diagnosisCodeableConcept_type.columns:
    diagnosisCodeableConcept_type = diagnosisCodeableConcept_type.explode('extension')
diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type.to_dict(orient='records')
)
diagnosisCodeableConcept_type_2 = diagnosisCodeableConcept_type.explode('type.coding')

diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type_2.to_dict(orient='records')
)
#diagnosisCodeableConcept_type.rename(columns = {
#    'sequence': 'diagnosis_sequence',
#    'diagnosisCodeableConcept.coding.code': 'diagnosis_code',
#    'diagnosisCodeableConcept.coding.display': 'diagnosis_display',
#    'type.coding.display': 'Diagnosis_Code_Type',
#    'extension.valueCoding.code': 'ext_code',
#    'extension.valueCoding.display':'ext_display'
#}, inplace = True)
#
#cols = ['Claim_ID', 'diagnosis_sequence', 'diagnosis_code', 'diagnosis_display', 'Diagnosis_Code_Type', 'ext_code', 'ext_display']
#diagnosisCodeableConcept_type = diagnosisCodeableConcept_type.reindex(columns= cols)
#if 'diagnosis_display' in diagnosisCodeableConcept_type.columns:
#    diagnosisCodeableConcept_type['diagnosis_display'] = diagnosisCodeableConcept_type['diagnosis_display'].astype(str).str.replace('"', '')
#diagnosisCodeableConcept_type = diagnosisCodeableConcept_type.drop_duplicates().reset_index(drop = True)
diagnosisCodeableConcept_type

,sequence,extension,Claim_ID,diagnosisCodeableConcept.coding.code,diagnosisCodeableConcept.coding.display,diagnosisCodeableConcept.coding.system,extension.url,extension.valueCoding.code,extension.valueCoding.display,extension.valueCoding.system,type.coding.code,type.coding.display,type.coding.system
0,1,NaN,carrier-27286904395,Z23,ENCOUNTER FOR IMMUNIZATION,http://hl7.org/fhir/sid/icd-10-cm,NaN,NaN,NaN,NaN,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagn...
1,1,NaN,carrier-27286904395,Z23,ENCOUNTER FOR IMMUNIZATION,http://hl7.org/fhir/sid/icd-10,NaN,NaN,NaN,NaN,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagn...
2,1,NaN,carrier-27334545890,M5416,"""RADICULOPATHY, LUMBAR REGION""",http://hl7.org/fhir/sid/icd-10-cm,NaN,NaN,NaN,NaN,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagn...
3,1,NaN,carrier-27334545890,M5416,"""RADICULOPATHY, LUMBAR REGION""",http://hl7.org/fhir/sid/icd-10,NaN,NaN,NaN,NaN,principal,principal,http://terminology.hl7.org/CodeSystem/ex-diagn...
4,2,NaN,carrier-27334545890,M47816,"""SPONDYLOSIS W/O MYELOPATHY OR RADICULOPATHY, ...",http://hl7.org/fhir/sid/icd-10-cm,NaN,NaN,NaN,NaN,secondary,Secondary,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59741,5,NaN,outpatient-9623755765,E538,DEFICIENCY OF OTHER SPECIFIED B GROUP VITAMINS,http://hl7.org/fhir/sid/icd-10,NaN,NaN,NaN,NaN,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
59742,6,NaN,outpatient-9623755765,Z794,LONG TERM (CURRENT) USE OF INSULIN,http://hl7.org/fhir/sid/icd-10-cm,NaN,NaN,NaN,NaN,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
59743,6,NaN,outpatient-9623755765,Z794,LONG TERM (CURRENT) USE OF INSULIN,http://hl7.org/fhir/sid/icd-10,NaN,NaN,NaN,NaN,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
59744,7,NaN,outpatient-9623755765,Z936,OTHER ARTIFICIAL OPENINGS OF URINARY TRACT STATUS,http://hl7.org/fhir/sid/icd-10-cm,NaN,NaN,NaN,NaN,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...
59745,7,NaN,outpatient-9623755765,Z936,OTHER ARTIFICIAL OPENINGS OF URINARY TRACT STATUS,http://hl7.org/fhir/sid/icd-10,NaN,NaN,NaN,NaN,other,Other,http://hl7.org/fhir/us/carin-bb/CodeSystem/C4B...

In [128]:
diagnosisCodeableConcept_type.dtypes

Claim_ID               object
diagnosis_sequence      int64
diagnosis_code         object
diagnosis_display      object
Diagnosis_Code_Type    object
ext_code               object
ext_display            object
dtype: object

In [111]:
eob_df_diag =json_normalize(
    eob_df.to_dict(orient='records'),
    record_path='diagnosis',
    meta = 'Claim_ID'
)
eob_df_diag_diagnosis = eob_df_diag.explode('diagnosisCodeableConcept.coding')
diagnosisCodeableConcept_type = eob_df_diag_diagnosis.explode('type')
diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type.to_dict(orient='records')
)
diagnosisCodeableConcept_type_2 = diagnosisCodeableConcept_type.explode('type.coding')

diagnosisCodeableConcept_type = json_normalize(
    diagnosisCodeableConcept_type_2.to_dict(orient='records')
)
diagnosisCodeableConcept_type.rename(columns = {
    'sequence': 'diagnosis_sequence',
    'diagnosisCodeableConcept.coding.code': 'diagnosis_code',
    'diagnosisCodeableConcept.coding.display': 'diagnosis_display',
    'type.coding.display': 'Diagnosis_Code_Type'
}, inplace = True)
diagnosisCodeableConcept_type = diagnosisCodeableConcept_type[['Claim_ID', 'diagnosis_sequence', 'diagnosis_code', 'diagnosis_display']]
diagnosisCodeableConcept_type=diagnosisCodeableConcept_type.drop_duplicates()

diagnosisCodeableConcept_type['diagnosis_sequence'] = diagnosisCodeableConcept_type['diagnosis_sequence'].apply(
    lambda x: x[0] if isinstance(x, list) else x
)
diagnosisCodeableConcept_type

,Claim_ID,diagnosis_sequence,diagnosis_code,diagnosis_display
0,carrier-27286904395,1,Z23,ENCOUNTER FOR IMMUNIZATION
2,carrier-27334545890,1,M5416,"""RADICULOPATHY, LUMBAR REGION"""
4,carrier-27334545890,2,M47816,"""SPONDYLOSIS W/O MYELOPATHY OR RADICULOPATHY, ..."
6,carrier-27334545890,3,M5136,"""OTHER INTERVERTEBRAL DISC DEGENERATION, LUMBA..."
8,carrier-27334545890,4,M48061,"""SPINAL STENOSIS, LUMBAR REGION WITHOUT NEUROG..."
...,...,...,...,...
59736,outpatient-9623755765,3,N1832,NaN
59738,outpatient-9623755765,4,E1322,OTH DIABETES MELLITUS WITH DIABETIC CHRONIC KI...
59740,outpatient-9623755765,5,E538,DEFICIENCY OF OTHER SPECIFIED B GROUP VITAMINS
59742,outpatient-9623755765,6,Z794,LONG TERM (CURRENT) USE OF INSULIN
59744,outpatient-9623755765,7,Z936,OTHER ARTIFICIAL OPENINGS OF URINARY TRACT STATUS

In [ ]:
def eob_diagnosis(eob_df, file):
    eob_df_diag =json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='diagnosis',
        meta = 'Claim_ID'
    )

    eob_df_diag_diagnosis = eob_df_diag.explode('diagnosisCodeableConcept.coding')
    diagnosisCodeableConcept_type = eob_df_diag_diagnosis.explode('type')
    diagnosisCodeableConcept_type = json_normalize(
        diagnosisCodeableConcept_type.to_dict(orient='records')
    )
    diagnosisCodeableConcept_type_2 = diagnosisCodeableConcept_type.explode('type.coding')
    
    diagnosisCodeableConcept_type = json_normalize(
        diagnosisCodeableConcept_type_2.to_dict(orient='records')
    )

    diagnosisCodeableConcept_type.rename(columns = {
        'sequence': 'diagnosis_sequence',
        'diagnosisCodeableConcept.coding.code': 'diagnosis_code',
        'diagnosisCodeableConcept.coding.display': 'diagnosis_display',
        'type.coding.display': 'Diagnosis_Code_Type'
    }, inplace = True)
    diagnosisCodeableConcept_type = diagnosisCodeableConcept_type[['Claim_ID', 'diagnosis_sequence', 'diagnosis_code', 'diagnosis_display', 'Diagnosis_Code_Type']]
    diagnosisCodeableConcept_type=diagnosisCodeableConcept_type.drop_duplicates()
    
    diagnosisCodeableConcept_type['diagnosis_sequence'] = diagnosisCodeableConcept_type['diagnosis_sequence'].apply(
        lambda x: x[0] if isinstance(x, list) else x
    )
    diagnosisCodeableConcept_type['bcda_extract_date'] = pd.Timestamp.today()
    diagnosisCodeableConcept_type['bcda_file'] = file.name
    diagnosisCodeableConcept_type['extract_from'] = extract_from
    diagnosisCodeableConcept_type['extract_to'] = extract_to
    return diagnosisCodeableConcept_type

In [ ]:
def eob_insurance(eob_df, file):  
    eob_df_insurance = json_normalize(
        eob_df.to_dict(orient='records'),
        record_path='insurance',
        meta = 'Claim_ID'
    )
    eob_df_insurance.rename(columns = {'coverage.reference': 'Coverage_ID'}, inplace = True)
    eob_df_insurance = eob_df_insurance[['Claim_ID', 'Coverage_ID', 'focal']]
    eob_df_insurance['bcda_extract_date'] = pd.Timestamp.today()
    eob_df_insurance['bcda_file'] = file.name
    eob_df_insurance['extract_from'] = extract_from
    eob_df_insurance['extract_to'] = extract_to
    return eob_df_insurance

In [ ]:
def eob_basetable(eob_df, file):
    eob_basetable = eob_df.explode('facility_extension')
    if 'billablePeriod_extension' in eob_df.columns:
        eob_basetable = eob_basetable.explode('billablePeriod_extension')
        eob_basetable = json_normalize(
            eob_basetable.to_dict(orient='records')
        )
        eob_basetable = eob_basetable.rename(columns={
            'billablePeriod_extension.valueCoding.code': 'adjustment_code',
            'billablePeriod_extension.valueCoding.display': 'adjustment_type'
        })
    eob_basetable = eob_basetable.explode('insurance')
    eob_basetable = json_normalize(
        eob_basetable.to_dict(orient='records')
    )
    eob_basetable['insurance.coverage.reference'] = eob_basetable['insurance.coverage.reference'].str.split('/').str[-1]
    eob_basetable = eob_basetable.rename(columns={
        'id': 'Claim_ID',
        'facility_extension.valueCoding.code': 'facility_Code_ext',
        'facility_extension.valueCoding.display': 'facility_Display',
        'insurance.coverage.reference' : 'insurance'
        })


    eob_basetable.columns = eob_basetable.columns.str.replace('.', '_')
    base_columns = [
        'Claim_ID', 
        'Patient_ID',
        'disposition',
        'outcome',
        'status',
        'billablePeriod_start',
        'billablePeriod_end',
        'adjustment_type',
        'adjustment_code',
        'payment_amount_currency',
        'payment_amount_value',
        'payment_date',
        'provider_identifier_value',
        'provider_display',
        'referral_display',
        'referral_identifier_value',
        'facility_identifier_value',
        'facility_Code_ext',
        'facility_Display',
        'insurance',
        'subType_text',
        'meta_lastUpdated',
        'created',
    ]
    eob_basetable = eob_basetable.reindex(columns = base_columns)
    eob_basetable['bcda_extract_date'] = pd.Timestamp.today()
    eob_basetable['bcda_file'] = file.name
    eob_basetable['extract_from'] = extract_from
    eob_basetable['extract_to'] = extract_to

    return eob_basetable