In [22]:
from sqlalchemy import create_engine
import pandas as pd

engine_DEV_Test = create_engine(
    "mssql+pyodbc://sa:Jesus&411@Dev-Test/CCLF_Lookuptables?driver=ODBC+Driver+17+for+SQL+Server", fast_executemany=True
)

df = pd.read_csv(r"C:\Users\Levi_\Downloads\clia_listing1778699859497.csv", sep=',', encoding="cp1252")
df

,CLIA ID Number,Facility Name,Lab Director,Address,City,State,Zip Code,Phone,Certificate Effective Date,Certificate Expiration Date,Certificate Type,Accrediting Organization,Facility Type
0,50D2262364,01 BRIARWOOD SENIOR FAMILY HOME LLC,KRISTINA FUREYSTER,1611 SE BRIARWOOD DR,VANCOUVER,WA,98683,360 977-0553,6/13/2022,4/4/2028,Waiver,NaN,Other - AFH
1,26D2154305,1000 LANDING CIRCLE OPCO LLC D/B/A VERO OF O'F...,JAMES AUSMUS,1000 LANDING CIRCLE,SAINT CHARLES,MO,63304,636 669-0780,9/11/2024,9/10/2026,Waiver,NaN,Assisted Living Facility
2,25D0677044,1001 HOSPITAL ROAD OPCO LLC,BEVERLY G. WYNNE,1001 HOSPITAL RD,STARKVILLE,MS,39759-2125,662 323-6360,9/1/2024,8/31/2026,Waiver,NaN,Skilled Nursing Facility/Nursing Facility
3,10D2040064,1001 SURGICAL,DR. JACOB STEIGER,1001 N FEDERAL HWY,BOCA RATON,FL,33432,561 499-9339,4/23/2026,4/22/2028,Waiver,NaN,Physician Office
4,45D2194489,1003 ABBY,SUSAN DINBALI,1003 ABBY RD,LUFKIN,TX,75904,936 639-1600,10/1/2024,9/30/2026,Waiver,NaN,Intermediate Care Facility for Mentally Retarded
...,...,...,...,...,...,...,...,...,...,...,...,...,...
301029,03D2314823,ZYNERGY SKIN + MED SPA,DEVIN GRAY,1910 S STAPLEY DR STE 124,MESA,AZ,85204,480 914-3376,11/29/2024,11/28/2026,PPMP,NaN,Physician Office
301030,21D2213979,ZYNITH HEALTH CARE & ASSOCIATES,DAGMAR NGIOWA,7301 HANOVER PARKWAY SUITE A,GREENBELT,MD,20770,301 477-1903,2/18/2025,2/17/2027,Waiver,NaN,Practitioner Other
301031,45D2337819,"ZYRIX CLINICAL RESEARCH, LLC",EDUARDO URIBE,401 SOUTH HELEN MOORE,SAN BENITO,TX,78586,956 456-4084,1/30/2026,1/29/2028,Waiver,NaN,Other - INDEPENDENT RESEARCH FACI
301032,11D2156374,"ZYWIE, INC",LATHA GANESHAN,"12000 FINDLEY ROAD, SUITE 360",JOHNS CREEK,GA,30097,678 514-3158,10/17/2024,10/16/2026,Waiver,NaN,Other - PHYSIOLOGICAL LAB CARDIAC
301033,06D2166216,"ZZAP PEDIATRICS, LLC",DR. AMANDA HARDING,"4650 SIGNAL TREE DR, SUITE 400",TIMNATH,CO,80547,970 812-9927,5/14/2025,5/13/2027,Waiver,NaN,Physician Office

In [38]:
import pandera as pa
from pandera import Column, DataFrameSchema


df['Certificate Effective Date'] = pd.to_datetime(df['Certificate Effective Date'])

schema = DataFrameSchema({
    'CLIA ID Number': Column(pa.String),
    'Certificate Effective Date': Column(pa.DateTime)
})
try:
    schema.validate(df, lazy = True)
except pa.errors.SchemaErrors as e:
    print(e.failure_cases)

In [37]:
df.dtypes

CLIA ID Number                         object
Facility Name                          object
Lab Director                           object
Address                                object
City                                   object
State                                  object
Zip Code                               object
Phone                                  object
Certificate Effective Date     datetime64[ns]
Certificate Expiration Date            object
Certificate Type                       object
Accrediting Organization               object
Facility Type                          object
dtype: object

In [39]:
df

,CLIA ID Number,Facility Name,Lab Director,Address,City,State,Zip Code,Phone,Certificate Effective Date,Certificate Expiration Date,Certificate Type,Accrediting Organization,Facility Type
0,50D2262364,01 BRIARWOOD SENIOR FAMILY HOME LLC,KRISTINA FUREYSTER,1611 SE BRIARWOOD DR,VANCOUVER,WA,98683,360 977-0553,2022-06-13,4/4/2028,Waiver,NaN,Other - AFH
1,26D2154305,1000 LANDING CIRCLE OPCO LLC D/B/A VERO OF O'F...,JAMES AUSMUS,1000 LANDING CIRCLE,SAINT CHARLES,MO,63304,636 669-0780,2024-09-11,9/10/2026,Waiver,NaN,Assisted Living Facility
2,25D0677044,1001 HOSPITAL ROAD OPCO LLC,BEVERLY G. WYNNE,1001 HOSPITAL RD,STARKVILLE,MS,39759-2125,662 323-6360,2024-09-01,8/31/2026,Waiver,NaN,Skilled Nursing Facility/Nursing Facility
3,10D2040064,1001 SURGICAL,DR. JACOB STEIGER,1001 N FEDERAL HWY,BOCA RATON,FL,33432,561 499-9339,2026-04-23,4/22/2028,Waiver,NaN,Physician Office
4,45D2194489,1003 ABBY,SUSAN DINBALI,1003 ABBY RD,LUFKIN,TX,75904,936 639-1600,2024-10-01,9/30/2026,Waiver,NaN,Intermediate Care Facility for Mentally Retarded
...,...,...,...,...,...,...,...,...,...,...,...,...,...
301029,03D2314823,ZYNERGY SKIN + MED SPA,DEVIN GRAY,1910 S STAPLEY DR STE 124,MESA,AZ,85204,480 914-3376,2024-11-29,11/28/2026,PPMP,NaN,Physician Office
301030,21D2213979,ZYNITH HEALTH CARE & ASSOCIATES,DAGMAR NGIOWA,7301 HANOVER PARKWAY SUITE A,GREENBELT,MD,20770,301 477-1903,2025-02-18,2/17/2027,Waiver,NaN,Practitioner Other
301031,45D2337819,"ZYRIX CLINICAL RESEARCH, LLC",EDUARDO URIBE,401 SOUTH HELEN MOORE,SAN BENITO,TX,78586,956 456-4084,2026-01-30,1/29/2028,Waiver,NaN,Other - INDEPENDENT RESEARCH FACI
301032,11D2156374,"ZYWIE, INC",LATHA GANESHAN,"12000 FINDLEY ROAD, SUITE 360",JOHNS CREEK,GA,30097,678 514-3158,2024-10-17,10/16/2026,Waiver,NaN,Other - PHYSIOLOGICAL LAB CARDIAC
301033,06D2166216,"ZZAP PEDIATRICS, LLC",DR. AMANDA HARDING,"4650 SIGNAL TREE DR, SUITE 400",TIMNATH,CO,80547,970 812-9927,2025-05-14,5/13/2027,Waiver,NaN,Physician Office