In [3]:
import pandas as pd
from datetime import datetime
import time

while datetime.now().strftime("%Y-%m-%d %H:%M:%S") < "2026-04-15 12:43:25":
    time.sleep(1)
    print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

print('done')

2026-04-15 12:41:41
2026-04-15 12:41:42
2026-04-15 12:41:43
2026-04-15 12:41:44
2026-04-15 12:41:45
2026-04-15 12:41:46
2026-04-15 12:41:47
2026-04-15 12:41:48
2026-04-15 12:41:49
2026-04-15 12:41:50
2026-04-15 12:41:51
2026-04-15 12:41:52
2026-04-15 12:41:53
2026-04-15 12:41:54
2026-04-15 12:41:55
2026-04-15 12:41:56

KeyboardInterrupt:

In [8]:
datetime.now().strftime("%Y-%m-%d %H:%M:%S")

'2026-04-15 13:01:19'

In [3]:
import pandas as pd
from pandas import json_normalize
from pathlib import Path
from sqlalchemy import create_engine, text
#from Credentials import engine_DEV_Test as engine
from datetime import datetime
import os
import json
from concurrent.futures import ThreadPoolExecutor

def load_ndjson(file):
    records = []
    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                print(f"Skipping bad line in {file}")
    coverage_df = pd.json_normalize(records)
    coverage_df['beneficiary.reference']=coverage_df['beneficiary.reference'].str.split('/').str[1].copy()    
    return coverage_df

coverage_df = load_ndjson(r"C:\BCDA\Data\Coverage_0455_20260503230524.ndjson")

In [4]:
coverage_df = coverage_df.explode('payor')
coverage_df = coverage_df.explode('relationship.coding')
coverage_df = coverage_df.explode('type.coding')
coverage_df = json_normalize(
coverage_df.to_dict(orient='records')
)
coverage_df = coverage_df.rename(
    columns={
        'payor.identifier.value': 'payor',
        'beneficiary.reference': 'Patient_ID',
        'relationship.coding.display':'relationship',
        'id': 'Coverage_ID',
        'period.start': 'period_start',
        'period.end': 'period_end',
        'meta.lastUpdated': 'meta_lastUpdated'
    }
)
coverage_df

,class,extension,Coverage_ID,resourceType,status,subscriberId,Patient_ID,meta_lastUpdated,meta.profile,period_start,period_end,payor,relationship.coding.code,relationship,relationship.coding.system,type.coding.code,type.coding.system
0,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,1999-02-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
1,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-b-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,1999-02-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
2,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-c-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
3,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2006-01-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
4,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-381908534,Coverage,active,8UR0CM8MD24,381908534,2026-05-01T22:06:27.359+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2017-08-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15311,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-384094156,Coverage,active,6C32CP5JP12,384094156,2026-05-01T22:19:29.021+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2017-12-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
15312,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
15313,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-b-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
15314,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-c-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode
15315,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode

In [ ]:
target_url = "https://bluebutton.cms.gov/resources/variables/rfrnc_yr"

def get_reference_year(extensions):
    if not isinstance(extensions, list):
        return None
    
    for ext in extensions:
        if ext.get("url") == "https://bluebutton.cms.gov/resources/variables/rfrnc_yr":
            return ext.get("valueDate")
    return None


coverage_df["reference_year"] = coverage_df["extension"].apply(get_reference_year)
coverage_df

,class,extension,Coverage_ID,resourceType,status,subscriberId,Patient_ID,meta_lastUpdated,meta.profile,period_start,period_end,payor,relationship.coding.code,relationship,relationship.coding.system,type.coding.code,type.coding.system,reference_year
0,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,1999-02-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
1,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-b-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,1999-02-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
2,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-c-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
3,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-39865712,Coverage,active,4D27T56YG65,39865712,2026-05-01T17:09:14.943+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2006-01-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
4,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-381908534,Coverage,active,8UR0CM8MD24,381908534,2026-05-01T22:06:27.359+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2017-08-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15311,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-384094156,Coverage,active,6C32CP5JP12,384094156,2026-05-01T22:19:29.021+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2017-12-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
15312,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-a-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
15313,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-b-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
15314,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-c-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,NaN,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026
15315,"[{'type': {'coding': [{'code': 'group', 'displ...",[{'url': 'https://bluebutton.cms.gov/resources...,part-d-342220199,Coverage,active,1FD1TA2QP92,342220199,2026-05-01T20:34:46.991+00:00,[http://hl7.org/fhir/us/carin-bb/StructureDefi...,2014-07-01,NaN,Centers for Medicare and Medicaid Services,self,Self,http://terminology.hl7.org/CodeSystem/subscrib...,SUBSIDIZ,http://terminology.hl7.org/CodeSystem/v3-ActCode,2026

In [16]:

if (coverage_df['extension'].explode().str.get('url').str.contains("https://bluebutton.cms.gov/resources/variables/rfrnc_yr")).any():
    coverage_df['reference_year'] = coverage_df['extension'].explode().str.get('valueDate')

ValueError: cannot reindex on an axis with duplicate labels

In [11]:
coverage_df_extension = coverage_df.explode('extension')

coverage_df_extension = json_normalize(coverage_df_extension.to_dict(orient='records'))
coverage_df_extension[coverage_df_extension['extension.url'] == "https://bluebutton.cms.gov/resources/variables/rfrnc_yr"].get('extension.valueDate')

5         2026
32        2026
81        2026
237       2026
255       2026
          ...
911146    2026
911164    2026
911191    2026
911240    2026
911386    2026
Name: extension.valueDate, Length: 15316, dtype: object

In [ ]:
pd.read_json("C:\\BCDA\\Data\\Patient_0002_20260609160521.ndjson", lines=True)