In [2]:
import pandas as pd

claims = [
    "claim_id=1001|patient=Alice|dx=E11.9|amount=1200.50|date=2026-01-05",
    "claim_id=1002|patient=Bob|dx=I10|amount=800|date=01/06/2026",
    "claim_id=1003|patient=Charlie|dx=E11.9|amount=950.75|date=2026/01/07",
    "claim_id=1004|patient=David|dx=J45.909|amount=|date=2026-01-08",
    "claim_id=1005|patient=Alice|dx=E11.9|amount=1500|date=2026-01-09",
    "claim_id=1006|patient=Bob|dx=I10|amount=700.25|date=bad_date",
    "claim_id=1007|patient=Eve|dx=Z00.00|amount=100|date=2026-01-10"
]

In [3]:
clm_lst = []
ptnt_lst = []
dx_lst = []
amount_lst = []
date_lst = []

for claim in claims:
    clm_lst.append(claim.split('|')[0].split('=')[1])
    ptnt_lst.append(claim.split('|')[1].split('=')[1])
    dx_lst.append(claim.split('|')[2].split('=')[1])
    amount_lst.append(claim.split('|')[3].split('=')[1])
    date_lst.append(claim.split('|')[4].split('=')[1])
    
df = pd.DataFrame({
    'claim_id': clm_lst,
    'patient' : ptnt_lst,
    'dx' : dx_lst,
    'amount' : amount_lst,
    'date' : date_lst
})

df

  claim_id  patient       dx   amount        date
0     1001    Alice    E11.9  1200.50  2026-01-05
1     1002      Bob      I10      800  01/06/2026
2     1003  Charlie    E11.9   950.75  2026/01/07
3     1004    David  J45.909           2026-01-08
4     1005    Alice    E11.9     1500  2026-01-09
5     1006      Bob      I10   700.25    bad_date
6     1007      Eve   Z00.00      100  2026-01-10

In [4]:
df['date'] = pd.to_datetime(df['date'], format = 'mixed', errors = 'coerce')
df

  claim_id  patient       dx   amount       date
0     1001    Alice    E11.9  1200.50 2026-01-05
1     1002      Bob      I10      800 2026-01-06
2     1003  Charlie    E11.9   950.75 2026-01-07
3     1004    David  J45.909          2026-01-08
4     1005    Alice    E11.9     1500 2026-01-09
5     1006      Bob      I10   700.25        NaT
6     1007      Eve   Z00.00      100 2026-01-10

In [13]:
df['amount'] = pd.to_numeric(df['amount'], errors = 'coerce')

df['amount'].groupby(df['patient']).sum()

patient
Alice      2700.50
Bob        1500.25
Charlie     950.75
David         0.00
Eve         100.00
Name: amount, dtype: float64

In [ ]:
from collections import defaultdict

patient
Alice      2
Bob        2
Charlie    1
David      0
Eve        1
Name: amount, dtype: int64

In [ ]:
from sqlalchemy import create_engine
import pandas as pd
from collections import defaultdict

engine_DEV_Final = create_engine(
    "mssql+pyodbc://sa:Jesus&411@Dev-Final/BCDA_Staging?driver=ODBC+Driver+17+for+SQL+Server", fast_executemany=True
)

df = pd.read_sql("select * from cclf_lookuptables.dbo.aco_beneficiaries where BENE_YearQuarter = '2026Q1'", engine_DEV_Final)

df

,BENE_ID,BENE_MasterID,BENE_MasterID_From,MasterID_Key,BENE_YearQuarter,BENE_AttributionYear,BENE_QuarterStart,BENE_QuarterStop,BENE_HIC_NUM_Old,BENE_HIC_NUM,...,BENE_2018Q2,BENE_Zip,BENE_PersonYears,FromFile,BENE_NPI_Classification,BENE_PhysicianAlignment,BENE_ADI,AlignmentFlag_CBA,IN_VA_MAX,SQLRunDate
0,1285784,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC1M09VY20,...,None,None,1.000,None,Physician Assistant,None,75.0,1,0,2026-05-19 12:10:58.037
1,1285785,54635.0,4. Recursion,48956.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC9P96XT24,...,None,None,1.000,None,Nurse Practitioner,None,85.0,1,0,2026-05-21 03:50:21.653
2,1285786,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD0Y39DW28,...,None,None,0.500,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
3,1285787,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD5PP7AU96,...,None,None,0.833,None,Internal Medicine,None,88.0,1,0,2026-05-19 12:10:58.037
4,1285788,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD7CE2VQ73,...,None,None,1.000,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16297,1302081,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN6H77RG64,...,None,None,1.000,None,Family Medicine,None,84.0,1,0,2026-05-19 12:10:58.037
16298,1302082,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN8RM5ET53,...,None,None,1.000,None,Physician Assistant,None,49.0,1,1,2026-05-19 12:10:58.037
16299,1302083,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN9V05CQ51,...,None,None,1.000,None,Physician Assistant,None,94.0,0,1,2026-05-19 12:10:58.037
16300,1302084,53897.0,3. RecordChange1_NotPRVS,48135.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP2NT4RF24,...,None,None,1.000,None,Nurse Practitioner,None,82.0,1,0,2026-05-21 03:50:21.653
16301,1302085,54791.0,4. Recursion,49134.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP8P19TG35,...,None,None,1.000,None,Family Medicine,None,89.0,1,0,2026-05-21 03:50:21.653

In [37]:
df[['BENE_HIC_NUM', 'BENE_NPI_Number']]

      BENE_HIC_NUM BENE_NPI_Number
0      1DC1M09VY20      1376878926
1      1DC9P96XT24      1154832681
2      1DD0Y39DW28      1649459595
3      1DD5PP7AU96      1043210149
4      1DD7CE2VQ73      1770841967
...            ...             ...
16297  9XN6H77RG64      1922492859
16298  9XN8RM5ET53      1407050008
16299  9XN9V05CQ51      1376878926
16300  9XP2NT4RF24      1629831847
16301  9XP8P19TG35      1750358792

[16302 rows x 2 columns]

In [39]:
providers = defaultdict(list)

for row in df[['BENE_HIC_NUM', 'BENE_NPI_Number']].itertuples(index=False):
    providers[row.BENE_NPI_Number].append(row.BENE_HIC_NUM)
    
    
providers

defaultdict(list,
            {'1376878926': ['1DC1M09VY20',
              '9XQ7A85UT74',
              '9XR4RH0DH80',
              '4A94JE5JR71',
              '3NK9FD3HK35',
              '2A37RW8YA52',
              '2A71RR6WU91',
              '9VE1KY8NU07',
              '9Y04M20UW66',
              '1WP8NW0RC61',
              '2XU3Y16GD16',
              '9YD3Y34QE14',
              '3KP3HM3KF14',
              '9YU2K34RA14',
              '4HD9AC8MP22',
              '4HE1F83AW10',
              '3Q22WX3QD23',
              '2KA6KM7UQ51',
              '8PM0D29DE01',
              '2VG2ND5HN24',
              '4HU4WX6WG99',
              '1GY0QY2NR01',
              '4JF6YX5AC44',
              '7NT9PN1FM32',
              '7P02W98YN89',
              '1V89FC5WW34',
              '3F49H85YW49',
              '6T78Q09YW33',
              '4QN2JG7PM90',
              '4KC4UN1YU94',
              '1MH3M14HY13',
              '1CV6X84PA45',
              '4PM4RD2YC99',
              '6D61E86DU29',
              '6D72MM5UR10',
              '1YV6WD9TQ56',
              '2RE2T68HH18',
              '1JT1RC6NA23',
              '2UV4Q87QR98',
              '4PW7RM3QQ60',
              '6UM1XA7NX26',
              '4TM9U30AJ15',
              '2RC8Y42DG55',
              '3N89J63AC18',
              '1XR6HG4FE55',
              '2N50CU1TX22',
              '1F31YA6KV28',
              '3GN9U97UW46',
              '1FG3VF0XR77',
              '2AE8CG9RU56',
              '1J34CA6YQ03',
              '4H66E73RC65',
              '1TJ7R13YK64',
              '3GV4PH8KT89',
              '3GV8GV3TY34',
              '9QU1QA6RN14',
              '1AT5YJ7QE56',
              '1T16WV8NF54',
              '4N38FM6UC63',
              '2PE2T80JG97',
              '1AY2UA4MG02',
              '3T91P34RY37',
              '6EA8JD1NM57',
              '2KJ3AY4JW12',
              '1VE3XH2NU97',
              '1EV1PM0AR18',
              '2M31MF6UN12',
              '1P19TT0MN49',
              '1P36HF5RP43',
              '3JY7N01JR31',
              '6F45A36CX61',
              '5MQ3JD6XT95',
              '5MR7PA3AV67',
              '6WE8VJ5VE35',
              '5NA6WY9XW46',
              '3JW0Y58QN26',
              '8UQ1QC3MT95',
              '9HD5F55AQ53',
              '6XN6U44QR62',
              '8DF1MU6MQ95',
              '5PG5H53UD75',
              '8VQ0K54TN01',
              '8E96KH1AM47',
              '3YN4DH3GX67',
              '6DF1M63DV38',
              '6G99FX3NE41',
              '8WD1JU7TK10',
              '7AA5EF3KR72',
              '7AC0QF4VA39',
              '9J76YD4YJ43',
              '7AK5MM4HQ99',
              '4WK9K80MC18',
              '8XH2GH6EX92',
              '9JY0DK7EN47',
              '4E90T77DQ49',
              '5UV4YV2CQ87',
              '7F16JY4RD52',
              '9KR0WV2EJ38',
              '5D33JQ9GA11',
              '6K56NU1UW61',
              '7GP2DX1RT94',
              '5E30P77GP13',
              '4CF7MH1JY62',
              '7H61HN2VT19',
              '6MN1XG9JF03',
              '7W81AQ7JM26',
              '5F19DW0TE43',
              '9DX4YC4GF61',
              '9E01D11WU14',
              '7WE8YC5AH28',
              '9MT3CD8YR16',
              '8MU7X80YD75',
              '7X48EP6EA53',
              '9X49ME1PU20',
              '9UW5NP0ER89',
              '9XN9V05CQ51'],
             '1154832681': ['1DC9P96XT24',
              '3PP3DV9FT04',
              '7MF9XK8YE26',
              '5H01UV0AE12',
              '2VA3XT2YW86',
              '2D15C67KG74',
              '7NF5JF5RM72',
              '2WE5EM8RM81',
              '3XW4MT6EK83',
              '3J73TW5UQ78',
              '2C76DE5MK44',
              '1MJ2JQ8XY15',
              '4FE2KV3EV90',
              '8QT9MN1UF37',
              '3UT7PP1YC54',
              '2F90C05DT32',
              '1GR3D30PV90',
              '1F43DV0XF77',
              '7QE3FA4UT96',
              '3MX4QF3PP88',
              '1AC0X06JP01',
              '4GT4CX4CU70',
              '4N06UN6RD41',
              '2EM0VX5KX26',
              '5KY4WE9RC89',
              '2NN0TP3JJ06',
              '4Q13DE1VX98',
              '8CE3YK4WC02',
              '3HJ3PC9VQ88',
              '6XE3T85RQ94',
              '9RJ6UK1ND30',
              '8DG9YW0VM33',
              '4AX3P75EA07',
              '5QK5JM5RM85',
              '4C13VV9KT03',
              '5RC9W63VM38',
              '3WR5FH1NW79',
              '8YE4VF1NM81',
              '9AC0YD0QU25',
              '8H91GU0YN80',
              '5TV8FW9CC36',
              '7TR8QE5MP53',
              '9M49Y75WP54',
              '5D60E95PD17',
              '3RW3E57YW92',
              '5ED5DK0HF94',
              '5XE9F36EQ14',
              '9TP1A52GM09',
              '4RG2CK9ED26',
              '7KK9E85HT11'],
             '1649459595': ['1DD0Y39DW28',
              '5G60CY4EM14',
              '1TC3KP7KY00',
              '5Y23DV2QR84',
              '9V95QK3PA88',
              '1NY8E18YC38',
              '7M36YP5HP53',
              '8NA0UX2JV15',
              '8NA3UW1PA99',
              '9XX3A97HA97',
              '5GD9KD9QJ40',
              '1UC6D48UC41',
              '2HQ6YM8YN61',
              '2HQ8UC2EG26',
              '9VJ5KF5DR89',
              '5GG8V48QF10',
              '5GH1EH3JE98',
              '5YC9KN7XN39',
              '5YD7X05EG75',
              '9Y71Y71NE20',
              '1YH7RV2VE58',
              '3EW9VU9XN36',
              '9NN8E39FM10',
              '2DT3N42KD95',
              '2V25NG7NH77',
              '9NR9TG2GP13',
              '5GW5RU7GN76',
              '2D62Y62GR80',
              '4EX2NQ2ET91',
              '8P11KN8DQ92',
              '2VA5UP6RQ51',
              '2J03T20MT73',
              '1MD5JN4GC62',
              '7N11FC4FD02',
              '2T07GG2JD61',
              '1W78TY3XP56',
              '5H53CJ4HU09',
              '2T34DT5EG97',
              '9P56YC7YT68',
              '9YQ2EQ9DD93',
              '9YU4FH5MW71',
              '1WE6RF0EM41',
              '6AA7FN5FY67',
              '9P84Q88CG01',
              '8PF8J51HE46',
              '6AF8N10XM22',
              '6P56CA4YG59',
              '3QR3QP8TF86',
              '2NQ3E25PK79',
              '2MH7G33EF49',
              '2MJ6VJ8WY84',
              '2WV2EW4ER70',
              '2WW1Q48MR38',
              '3JF0W99CD25',
              '3YK5H05EY85',
              '8Q12RM6PE92',
              '3JH9G39MX13',
              '4J42JR1WM21',
              '1R27V15GW67',
              '1YT8Y30DA53',
              '1R59CD1TQ46',
              '5HP0J45DG35',
              '9EY5AH2YX86',
              '3XV0U32MG39',
              '6Q05M30JA99',
              '9F14C92JH06',
              '1P70MC1GM25',
              '5HU9T41AF40',
              '2E94K50VJ84',
              '1QP2GA5FH16',
              '1QT4QK8EP64',
              '4JR7KC4KV40',
              '5J22KP8QT85',
              '7YA6KC2QG64',
              '4JX4T19KV02',
              '8Q33CT1YY91',
              '3NQ8TJ0AK38',
              '2RW2PU0VR99',
              '6TE8T20JY21',
              '4QE3HC0GT06',
              '1MF8A41UK51',
              '3NV5C78GK53',
              '2QF9WV9DP54',
              '3P05UV9CQ71',
              '1MF8NJ6YF56',
              '5JM5TW0MF62',
              '5JN3V53TY98',
              '2QN7UW8DG44',
              '3P74G51DH82',
              '3P80WR4DD00',
              '5JP3V88EW07',
              '6CN2YR1CW26',
              '7YW2YT5YV11',
              '3HQ2U16RG06',
              '4FD9T98YW18',
              '7PE5M09YH88',
              '1CV4UF5RR88',
              '3HT5P43WH99',
              '3CN5GC6FA59',
              '1G38AV1AM31',
              '6CY0RR3JT02',
              '6D08NG2GY10',
              '3UM2XY8JA70',
              '3K94FH2HT72',
              '7PN7XD4TF53',
              '1D80HJ5QC08',
              '8R51CR4VT28',
              '2JX5CH5WT51',
              '1PR7DV0JV47',
              '1UC3WW1JK70',
              '6D63T02GR90',
              '8R76Y30JR49',
              '2A03NU8KD81',
              '6UN4ME9PX07',
              '6UN4PM4HD61',
              '7Q11FV0VX98',
              '8RC5AU7KC81',
              '2MU9K13UT30',
              '7Q52Q62GD06',
              '2MY0YE2GP30',
              '3KG6E37XN44',
              '4G55AN8EN64',
              '4G61UV5XF19',
              '2X45K13HE86',
              '1DT0E97YE46',
              '3W71YE3ED80',
              '3W76G15FJ53',
              '3GN7PK0UX76',
              '1VG9VN8WP55',
              '2MP2NH4UD01',
              '3MY1X66GP20',
              '4GE6XF5DC73',
              '4GG7A75VF77',
              '1X59DQ7AW41',
              '2YX1RK2YT91',
              '5K75NP7VQ40',
              '6V97D64CA78',
              '2X51J29PU10',
              '4U28RM0PU46',
              '4U50WR3GJ01',
              '2AD9U52UW18',
              '3WF8K16KG47',
              '4GM8U17GY66',
              '9Q88RW2HC57',
              '2YE5PR8GG97',
              '3U56VA9EG89',
              '6VM7YV5CN78',
              '9FM3E28VK06',
              '7QY6M67AE51',
              '3G67D74FP65',
              '6VU5G47FJ81',
              '3HY5CH8EJ55',
              '3DC9M18DY38',
              '2CJ7MR4NA65',
              '9QH0MW7KT09',
              '9QH1H84CW92',
              '6RR2UA1UV88',
              '6VX9TT4GG22',
              '6VY2J54TF21',
              '7R60DE1GQ27',
              '8RU7MG7MT30',
              '6W57T85UN44',
              '8RW6JQ3XU41',
              '8RX1T54FY06',
              '4MY8RC7HU33',
              '6W89KE0PR59',
              '7RG1DJ7AG00',
              '6T11F10WD01',
              '6E59AM4CU58',
              '3T63EE6CA05',
              '4D45XN3DV99',
              '3UF7AN6WA63',
              '2PD5JY6FE54',
              '1T34EK2DF66',
              '2FV8CX8EJ42',
              '6EA8GN3FE42',
              '3VT3WP0UM72',
              '2J79R53XH12',
              '4DD0A54DW18',
              '4NA2UG7PA19',
              '6ED7E32DK39',
              '1T84E57DY76',
              '2JE0DT4EG37',
              '1C44MJ0JN92',
              '6EG0G12QG19',
              '3TF6U88KU60',
              '8C33XK0RH08',
              '3TK6UN9YJ44',
              '3A77R32WU61',
              '1RG6V98MX72',
              '5M04F35PM88',
              '3A95TD4UA78',
              '1VC9GW7DY19',
              '2JQ3R04KC11',
              '3ND7G80WT45',
              '2M38JA6FM51',
              '8TC1J86AT34',
              '1A87AU8CW54',
              '3C73JG6WD90',
              '6WA1MD4EE22',
              '8TJ7XH2TQ48',
              '6R92H35WP89',
              '6TW8HM2MJ63',
              '6UQ8GR3MT45',
              '3JX6J99KP70',
              '6RE4AV6CE04',
              '4NV1VM8FF20',
              '5MA4CQ5WH94',
              '6F00E25FF03',
              '4P49PK3DM52',
              '4P75QW4QH72',
              '6F94JY3AC09',
              '6FA5PV2PQ71',
              '8D54C97QF98',
              '6FJ4DU7EQ80',
              '8U59NX1GJ41',
              '3H98N36MT62',
              '6WH8VU6KE67',
              '6WR0CD8VD34',
              '3HK3JD6JQ99',
              '5N94F13RT72',
              '5NA5RV2TY70',
              '2WM3VD7FC00',
              '3JT8EA6JX31',
              '6X06HJ7VK86',
              '5NK2PK3JM16',
              '5NM3R30FP00',
              '6X35EM8RC53',
              '2YH7V76CJ32',
              '6X58Q83AW21',
              '2YK1XG4VC08',
              '2YP2EC5VX18',
              '5NX6XT2WM75',
              '2YT0KC6YX01',
              '9R90N94XE41',
              '9RA0U60PG44',
              '3MK8VA2WW34',
              '9RC2G60YD82',
              '9HK6CD8FN66',
              '3C10FY8PU25',
              '3C78UP7XJ43',
              '8DE3YM1DV08',
              '8DE7CH8DV68',
              '3DJ3ME2AN86',
              '6Y13HN4UV76',
              '8V49XT6HA33',
              '3DU6CQ7CF68',
              '4V01YG3XH15',
              '3DX9EK7PD48',
              '3E11HM6TQ02',
              '6YE9F78DD14',
              '8VH3G98UT00',
              '8E17EU7FK40',
              '8VM8UN3XK26',
              '8E40WK8NT17',
              '8E80WH4JK05',
              '5PT8UM2WU47',
              '5PY6XV1DN50',
              '5Q39DD9TE25',
              '8W55MT8NG59',
              '3H05WM2YD81',
              '5Q43DC9QC93',
              '6DJ9AR2VV32',
              '4AK4GQ2KT61',
              '4VK1TA0JK05',
              '6GK5M10TY65',
              '3QG4U07QP04',
              '4VM5F20WV83',
              '5QG0QW5UQ46',
              '6DP9HT5HK20',
              '6GM0XY0KC09',
              '4AV8Y62HF59',
              '3RF7PC9YK51',
              '3RM0KR9GC48',
              '4VY4H27TE71',
              '9HT1QT0GG08',
              '6HE2JX8YY81',
              '9J55QC7GG79',
              '9J82WU6XC90',
              '6HU8M76DN44',
              '5RF9KJ9WJ39',
              '7AV1AD6FE98',
              '8F03HA0FF73',
              '5RV2V47DY94',
              '5RV3KY3CY93',
              '4X92A05MC99',
              '4XA3KJ9MA19',
              '8FQ1WU5WH07',
              '3WR4PA0JT86',
              '4XK4XW7DH73',
              '7CK3JK0JG11',
              '8Y49PJ6JJ59',
              '9JX3EK5QX75',
              '7CT4AG6EU08',
              '8Y88PN6VN27',
              '8YD4FP6DF84',
              '9K55VM2HT80',
              '9K63U36HW82',
              '7D87C96DC38',
              '4Y92R29VM87',
              '4YJ8KU0EA65',
              '4YK6DU8NF41',
              '9A89J19UD38',
              '7RR3VH2TU07',
              '7RW3YY8HR19',
              '7RX2GW3QW24',
              '7RX7AJ4FP67',
              '9AM5AG9YN70',
              '4E89DF2PQ48',
              '8J21MA6YQ13',
              '5TQ1Q92YQ03',
              '4YT1D34VU08',
              '6HX4UA2YG01',
              '6J11ER7GM09',
              '9C85JD7TP78',
              '9C90RJ0PK36',
              '5AD5D50MW60',
              '9CF9XK2PF56',
              '6JH0MF8MJ42',
              '5AT8GA5VH59',
              '5AV7G79QP65',
              '5U82NJ0KJ04',
              '5UG2HC3HK21',
              '7ET8HC2MU47',
              '7EX8G09WW44',
              '5UX7MA0CP47',
              '5UY7J44MV64',
              '7F61PF8TX03',
              '7F97EA9MA68',
              '8JW0FV0PX44',
              '8K94UJ2GR71',
              '9KY8W83QC58',
              '9M29X24WR44',
              '6JJ5H18NX54',
              '7FG9YK9TN34',
              '9M59D39XP15',
              '6JP8TW2YD52',
              '7U38K52DV57',
              '5D42YR9TX81',
              '7FV0EJ1RJ12',
              '8KY5KF7JA70',
              '6K33HR6QV98',
              '7U91FW5KH34',
              '7UF3G74NE16',
              '8M85U99XM75',
              '7UJ9RY2NA36',
              '5DM0VR2UR11',
              '7GD6M28YK49',
              '7GJ0WN8EX44',
              '7UT3F14CT77',
              '5WG2MJ8FY03',
              '4CC4NG3HC81',
              '6M15GH3QM59',
              '5E80DJ0FG42',
              '5EC3R09FE12',
              '7H89QP5RX15',
              '4CR3PA5WV90',
              '4D26Q86GW70',
              '9DE8V41HV10',
              '5WK8VJ2UW64',
              '7VV4Y53VM93',
              '6MR6K11TY71',
              '6MR9WA3KD24',
              '5EV1PN6AT38',
              '5WU0F13AV29',
              '6MX8YP9GP50',
              '7W46D35NH79',
              '5X96C96VX46',
              '6NM6TQ5AN68',
              '7JP0KE2KY00',
              '4R82J96EM06',
              '5XK5P25RK84',
              '9EE9DY1PH18',
              '4R94H07DJ85',
              '7JX8CQ8XU52',
              '7K05PR9CJ96',
              '9N87FC4CD49',
              '6NX5PT7JM85',
              '7X15W82GH65',
              '8MY0TV9VU13',
              '7KT8EK1MP34'],
             '1043210149': ['1DD5PP7AU96',
              '1GJ4AD8TY75',
              '7M00P51NW36',
              '1FP3VJ4TT03',
              '1V33GN1HC73',
              '1KW4QA1AM85',
              '1ER8K70HC63',
              '5YR7XR0HV48',
              '3KK2YR1DN27',
              '6A83Y49EY06',
              '1HM8CM7VN28',
              '6AQ9QJ8UK58',
              '2VW2YM0YC97',
              '3CP7CT9DX67',
              '4JC5TW5PH85',
              '9PM2JM4FG03',
              '4JG0MG2RF47',
              '7NQ2UG1HR84',
              '7NU6UG2KE87',
              '3FX7NA9KC48',
              '3FX8PX8KN66',
              '7P01GW6DM90',
              '1FR2F82FP83',
              '2Y64RC2WR68',
              '5J83CQ5CK05',
              '7YF5T54CA53',
              '2QR6DT9WH78',
              '1V63Q05VY13',
              '3HX2YU5NC90',
              '1G57QG2WT47',
              '6D47DV2TX31',
              '6UC7PA0EK38',
              '8R78VR4YH42',
              '3FA0NJ4TA10',
              '2P46JQ4EN53',
              '4GE1MA4RD04',
              '7QP9EG7PQ32',
              '3A45UM8MY52',
              '9QH9W91PR30',
              '3GR8A09FT65',
              '6T06F95TA49',
              '1AU5TH4XJ61',
              '2H98UE3HC48',
              '6EA0WN3CN38',
              '4DV6Y97VJ62',
              '2KY6HC9QA78',
              '6F95UE5GW94',
              '3H49FQ5XX51',
              '6FJ1TY3YR38',
              '3K83G78QA77',
              '6XK1EW8FK05',
              '9RE7V67NH50',
              '4UQ6TH0JC42',
              '6DP0KK5NJ37',
              '6H68V22YR30',
              '4WQ8TY8EW50',
              '4WY3WP8NP99',
              '4X08XW5QE42',
              '8XW8C87UC56',
              '3VP4RV9KH06',
              '7D63Y47HX12',
              '8YU5ED8CY92',
              '4YH7XM1DY34',
              '7DN9CY9XH15',
              '9AN7AM1HN39',
              '8HH0NN9GQ07',
              '8J19WQ5GN39',
              '9CD6EM6TJ68',
              '7EA4AQ6XJ66',
              '9KV5WC6KM93',
              '5W08TU1DQ21',
              '9WP0VR2JV46',
              '7GK0U64XE29',
              '6KV3TN7JE60',
              '4CP6VC8NU45',
              '7VJ0C00NP07',
              '7VK5FE9WM85',
              '7VM5M17UN40',
              '7HK5KA7VP68',
              '9DG7YQ9QT58',
              '9DP0D29JR33',
              '5WT9Q48UA13',
              '7JE2D01UH28',
              '7WE2UP0RN01',
              '5G29ND4DQ13'],
             '1770841967': ['1DD7CE2VQ73',
              '1DE2EQ5JQ94',
              '2KK7M56JH53',
              '5G53EA5QN83',
              '8N13KD5RD11',
              '4A54VH2QC05',
              '9XQ4QQ2HH77',
              '8N19X01MX28',
              '1FN6TJ3EM70',
              '2MA8QF2DN58',
              '9XT5T93JG78',
              '2DE2HK3MR95',
              '2NT3U57CH09',
              '7M26X80CJ58',
              '4AA4PM1WQ61',
              '3NA6CY8KX56',
              '1NX1CX1YD38',
              '1NX2K34KM86',
              '5GA6PJ9GK76',
              '5GD1KN2KK38',
              '5Y41AQ9HT27',
              '1RF0EU8AA13',
              '2XG8GF0KT28',
              '2XM1CJ2XN18',
              '2HQ5DG9QR64',
              '9VF7X54TM62',
              '2DG3V91XP95',
              '1UX9HK0VU32',
              '1V10TW7CA39',
              '5GF3A82JG98',
              '7MA8KE0KH35',
              '2HR2MD4CP13',
              '1XA2JJ1NQ81',
              '2J50D53FR37',
              '1KX7HH9WC30',
              '1M06AX9XV74',
              '9Y79WQ2JQ28',
              '7MF5WV7HG60',
              '2XU6H32QF60',
              '1PN8EW0WY47',
              '5GR2F27QC12',
              '2HR8VN9FG37',
              '2DT8K41HG20',
              '7MP8FV9JT44',
              '3KY8RC1YH54',
              '4ET1J38AU08',
              '7MU6G59WA83',
              '3KR5N55XP73',
              '9YJ8K15CW43',
              '1MD0YF7GC42',
              '1MD8XJ9QK68',
              '4F18V74DX40',
              '5H24DE8UH67',
              '8P44RK6DG60',

In [46]:
providers = df.groupby('BENE_NPI_Number')['BENE_HIC_NUM'].apply(list).to_dict()
providers

{'1003331356': ['2JC7P10JC51',
  '2WX3N68VW04',
  '3YG0KC4CY03',
  '1V82T34FV22',
  '6CC0TA3AG15',
  '2H01EA2TJ36',
  '1MY8R02PN28',
  '1N25GM6NX59',
  '3R09D43DU24',
  '4MV8GD5JX63',
  '4C47AQ7CQ35',
  '4NT9UA8AH48',
  '4P77MV5CG31',
  '6FY7KW6MC69',
  '5Q85TN2UY76',
  '4AU7RU3TF58',
  '7AA8Y42YY50',
  '5TV4DW1EE68',
  '5AH7EX0MK33',
  '6NY2D70XK26',
  '7K21JX3VX20'],
 '1013138361': ['5KK4HA5JV92',
  '5KM6G73AM86',
  '2UH8JT7YA35',
  '8X25GT8KX79',
  '8XY9YV3VY17',
  '5A20JE8MC22',
  '5UP3K36QX08'],
 '1013456193': ['9Y74E13EM95',
  '1WJ2TP4KC17',
  '7XY3DC4PF11',
  '5HW8YG1FD57',
  '7YN6DP9AD41',
  '2JW4YV5JU61',
  '1EK1DP6JX05',
  '4U32N88EJ19',
  '7QR4X58UG97',
  '7RC3TP6NF93',
  '6E73EC1HK94',
  '4N57MA0UY63',
  '1T44AT7VX71',
  '4NC1UY2PA29',
  '6R01JT3EV05',
  '9H96H22KR61',
  '8EX1QX1CR39',
  '9JH2Q76VG29',
  '5D19GC2JE33',
  '6KG2WH7KN14',
  '6KK7A81DP67',
  '7H29AU5HY29',
  '5EH5XM2FH51',
  '7X61QR3AW31'],
 '1013918093': ['9HY1E71PG23'],
 '1013991694': ['8RR4R61RT66'],
 '1023005725': ['8NE1NX1TA21', '4HR5AY2EF86', '6U02NP7JT93', '4Q99D58AT22'],
 '1023085768': ['9FA0EV9AA19',
  '4FG0C54JQ16',
  '9FH9X48XQ37',
  '6WQ5JF6RW70',
  '7U64HE7VE70'],
 '1023425469': ['7MR2AF0VC02',
  '2RK7QR4FC67',
  '9YU4FA0RC04',
  '6A79H26KQ00',
  '2D32AG4TY91',
  '2RP3YJ9RV86',
  '3NV1R27KD17',
  '6C95JR7PK86',
  '1Q28W25NW20',
  '6U51UF9HK12',
  '8R42NP3EQ05',
  '2FA1MK9HV95',
  '2MQ8V48CX68',
  '5JR5GF1QT56',
  '5JY1QH1DW25',
  '3U62QU9EF99',
  '2G31N82UR15',
  '1J64UD4YM93',
  '4C31DU6DT36',
  '1RH4GQ0RC86',
  '2JR0U38TV18',
  '6YM9R73GA57',
  '4VM8DX2HU43',
  '4VV9TP4GJ22',
  '4W14QC6JU95',
  '8EW3WN0WX84',
  '8Y55PJ6VR57',
  '7CW5N08NY94',
  '7D09HA4XG54',
  '6J67NM4MK73',
  '5TV7G00GF79',
  '9CT7PH4FV59',
  '9CV7F55RR38',
  '5DR2JG9VH70',
  '3TU2DD1PD86',
  '6M34QV7PU87',
  '7W30Y93FP13',
  '5FA5C53DR82',
  '7JQ9XT0MC32',
  '9U16AR3MT54',
  '9XC4XR7NP61'],
 '1023706793': ['5G54P88EN64',
  '8NP2MT9CM89',
  '4F27MD5DW20',
  '5H41VF4DC34',
  '3TN9T10PJ36',
  '1TP7D56XK30',
  '1XK6ND7DU82',
  '5JA3HG4JD91',
  '3P19EQ4WW56',
  '4FE3HK0DY71',
  '1Y48CK6CN23',
  '2N65N18AT89',
  '8AC3GE2GX08',
  '3T47E96PE65',
  '8AQ7GA5GJ68',
  '3TJ0XC1RP07',
  '8T35X02TW79',
  '2M51E85NQ36',
  '6QE2PA0CA01',
  '1A41GK7FF27',
  '6RC0D74WM19',
  '5M78HR7XM35',
  '5NX0F67NE29',
  '6YD2MQ8JJ88',
  '3FQ3VC9FQ73',
  '8WA4C25MK97',
  '3X39AT9XX59',
  '9AR2VH2VK29',
  '8HQ5Q34WK99',
  '7DX3XE5NM16',
  '5AF0XG9RR26',
  '7TC2JQ5PU95',
  '9WR2G39HD94',
  '7V67U87TW42',
  '5WQ6JP9MW78',
  '7W96DE3EF82'],
 '1023732716': ['4A79UQ9FD57',
  '5Y71MH6AD90',
  '5GP5WT1HW97',
  '3Y53YD1VR97',
  '3YK6GT6DX74',
  '7YX1K74NU12',
  '1G91GQ4CF32',
  '6RP5AN5NE92',
  '4MT3A48NT77',
  '9QQ1P04ER24',
  '2EH9M07UJ12',
  '6QX4QD9GA77',
  '9RD9QH0MC42',
  '4V12FA1VE83',
  '5PN6HA5JX57',
  '8GQ3DV0CW80',
  '8HC7U34HX38',
  '4E32Q96PJ99',
  '8JH6QU6YE60',
  '5VG4EM1HP94',
  '9WF2P57TA03',
  '9D72VY2QD18',
  '5XK4Q73DP60',
  '9UQ1WT8DX38'],
 '1023752656': ['1V56F37FT70',
  '3KT3XD1HK71',
  '3XN9AU9PQ31',
  '5HR1G51JK29',
  '6PY5PA8DN70',
  '7XV6GU0GN55',
  '3G60K42PJ32',
  '2CY2TU2TP19',
  '2RA2P62GK27',
  '3V05W12HF63',
  '1KP1VC2KF14',
  '1A29QC2TJ57',
  '3C51AK0TT28',
  '5MY3CR3JV93',
  '6FN0A16MM28',
  '6H98DG6EX65',
  '7AV1YY5NK13',
  '7RQ4VY6DF74',
  '5TF1D07CQ05',
  '5TT5N44EG68',
  '7E51HA9UM13',
  '9CE0MA8FH18',
  '5U81JM9HD10',
  '7U04VD8PW06',
  '3RV5T74VT99',
  '7UT6M76YR75',
  '6KY1AN8DC38',
  '9DW6KE1MC66',
  '9E80CK3TC90',
  '4R84E79UN87',
  '5FV9UT3RE30'],
 '1033566435': ['1GH7TV7VE77',
  '5G65P20CK92',
  '4A91ND2KN90',
  '3NA1HP5FT03',
  '9XY2VY1HY17',
  '1V04NE0FY50',
  '1UD2JH3NG16',
  '1KY9K93PY17',
  '1M00GM3KU34',
  '2AV5A50MJ62',
  '9Y90RQ4NF22',
  '5GR0WF1FD04',
  '5YH7VH4AH41',
  '9NK8TW1ET31',
  '1ET0MC4PW29',
  '8P07W49QM20',
  '9NU0H59UM43',
  '9NV4XU3HN84',
  '2V86A00CC48',
  '9YK1H80DW94',
  '6A03N65GA89',
  '3KV1QR6NN95',
  '9YQ2DF5GV87',
  '1WD3XQ5QA81',
  '5HC2JQ9DT04',
  '5HC8R03NX10',
  '9P96RR6EG43',
  '3F15PQ5XJ57',
  '2D13GK8PJ97',
  '6P59F25XT57',
  '6P70AX1PG11',
  '6P77RT7TK54',
  '2Q01EX8CA10',
  '8PX7VR4DU52',
  '8Q12GE9VJ87',
  '4J11MR2XK80',
  '2P53GC3YG19',
  '2W12FX4RK90',
  '4J47R74UU78',
  '9ET2C18TV00',
  '2E00HN4JU14',
  '1H00WC0TX07',
  '7NP5PR1FK40',
  '4JG2YF9PC05',
  '1R96NJ7EM66',
  '2WK4GG8XA77',
  '9PU3CN2CW81',
  '3G25EJ6UU75',
  '6Q77JM0QW43',
  '3F36AN5FD83',
  '3F39MX2RA52',
  '9FC8NV1NY39',
  '9FE7NX3MV48',
  '1U23W50WR83',
  '3NR6GN0TN82',
  '6TD8VK7KW30',
  '1U60GU3HF00',
  '1U62HP0EF99',
  '6C90FT2VE11',
  '2CV0ND4CP26',
  '6TQ8QH5CG36',
  '2ER0V39KT16',
  '1EA3HQ6XJ86',
  '3HP5AD6PG74',
  '7PD9HJ5WJ47',
  '7PE9T79HF26',
  '1UP0JU2QX08',
  '4PG7VA3RF60',
  '1Y50KX1NK22',
  '1XH8PT5HQ66',
  '7PR1Y23UR15',
  '1PP1KK2KX08',
  '2UM9R76ED59',
  '4FP8XE2TR33',
  '6UG0D50WG10',
  '8R79X19UP27',
  '1YY2MX8EV94',
  '8R95Q39AG63',
  '1WV7P56RW52',
  '3V02P86TY90',
  '2RY9X77YN00',
  '2MR3XN2KD94',
  '4PW5QQ5VA65',
  '3KF2UN5HY21',
  '5JW8VH9UR59',
  '5JX7P01JT71',
  '6UU7U60UW61',
  '1UV0PY9RT19',
  '1UP6YM6VC51',
  '2JW1RJ9JV11',
  '3MW9PK9CQ18',
  '3W81H44PQ09',
  '1VH7WG1AR47',
  '2EF7KJ5TY72',
  '6VA8TY2AY57',
  '3CV4M04RR68',
  '1EH1C74JA95',
  '1EN7XA7FY30',
  '1EP5G17GD52',
  '7R26Q41KN51',
  '2AJ7YW9MV62',
  '2CM3GA4QY77',
  '1MC5H01JG74',
  '1MC6E54HK30',
  '1J64AK7XE80',
  '6RU9R58QA24',
  '3GR8AT2DA22',
  '7RF1JD8RE06',
  '8AN5QH2YM70',
  '8T06U19CH45',
  '8T09J67QY47',
  '1YD9HK6DE34',
  '4N27CY4VE54',
  '2P99C26EG53',
  '1T28DD4FX39',
  '2GH7CF5UC36',
  '5KN7MG8RM58',
  '6E83UD3TC80',
  '3AG0XD2AN04',
  '1T53P43JT60',
  '4N89UY2PD19',
  '4NA5WP2MX57',
  '2JF0GF9KK21',
  '1C32FP4CR15',
  '2HE2C26NP83',
  '4DG5MP0MQ75',
  '4NG4HK7KQ66',
  '4C25TH8HN81',
  '2JK1HT9CX35',
  '6EQ9DM7MV17',
  '1RJ9UJ4DY25',
  '8C90A51UQ39',
  '1DF5CX0EV79',
  '8T36Q43VY61',
  '1NP3UP0PM79',
  '3AP2D47MK90',
  '8TA7CF0PV45',
  '6NC6JC4CY49',
  '6QF8U72AM52',
  '8TK5DR2KP60',
  '6QM9UA1WP38',
  '4Q77R78GC66',
  '2NF4HN1YT87',
  '6EU8MT2WA64',
  '5MF1YT9HA23',
  '6F03NH6FG93',
  '6FK2J05TJ84',
  '3HF4YF7EQ05',
  '3HG7JV4UT67',
  '3HH2U26VR08',
  '2WM2QA1UG03',
  '3JT6MH1YY72',
  '6G53RC8KT18',
  '3K37VA7CF46',
  '2YK2W32PG82',
  '3M97QQ4HG53',
  '6XE2YA5YW19',
  '6XJ4RC6FM65',
  '9HF6K78NU70',
  '9RC9AR4PF44',
  '3C84QG0CM66',
  '3C90QY0JA90',
  '4UE8EA9VA22',
  '3DN3XW3JG14',
  '8DH1Y81VK23',
  '8DH5FG9VR80',
  '6Y78F14NH22',
  '8DR5K21YF56',
  '8VA9K41UT33',
  '3DY6T24AY57',
  '6YF8UQ8XH49',
  '5PG3VP3JE97',
  '8E13G24EQ11',
  '8ED3YQ0RC01',
  '5Q53HY5FC85',
  '4V48XN0VA33',
  '6DD7YK4QW68',
  '3Q83AQ0QV73',
  '6GF1QK5RC94',
  '4VJ5WC7PQ68',
  '6GH6AM2QJ62',
  '6YX2GE3RW04',
  '6GV3E40NW11',
  '6HK6D03TN76',
  '4WK3YD4YC98',
  '4WQ4YJ5VF94',
  '4WR8VT3QY21',
  '7C20GN6FM39',
  '8XK9E96DH53',
  '8FG2XN7TN04',
  '3VJ9F64VK14',
  '4XF2Y95GQ85',
  '3VR1DE6MG17',
  '8FT9GF5KG28',
  '8Y13D28CT93',
  '8FW1J75HA96',
  '7CT4AR7EU78',
  '4XT6ED7EN43',
  '7D01DQ7HE32',
  '8YN3PQ3EV05',
  '7DQ7XD8VP32',
  '7RV4GU1CX63',
  '9AJ9ND9YQ10',
  '7T06DP7JY50',
  '7T29PT1KC42',
  '5TA3JM1HQ91',
  '5TD9E65FW28',
  '4EG2KH4FY02',
  '4YW3UD4FY15',
  '5A18WA5FX28',
  '5AM7GF9NU73',
  '5TX3FK0QA87',
  '5AU3WV1KJ91',
  '5AX9FC9RA27',
  '5C17N60HP41',
  '5UG3CJ7AD06',
  '5C36TQ4VM61',
  '7ET5M37JC64',
  '7EW9T84YQ57',
  '5CF9FT2YC44',
  '8JJ3KV8EC87',
  '5V32YJ6TW00',
  '5V37RT0RY31',
  '9VW7A88AD48',
  '7TF4WT3WM62',
  '9W47QK6GP54',
  '8KH7R60PP36',
  '7TU8GC6YM53',
  '7TX9EW0MH33',
  '5D09HV7QA19',
  '9CU8W09KX22',
  '9D34WX4PG87',
  '7U83UK3YK75',
  '5D96MK4YX65',
  '9MK1GQ9WW34',
  '8M99VK2QP38',
  '3RU6AE1FR87',
  '3RU8GG9FR37',
  '7GE4FC9XH78',
  '3RV5J21TQ67',
  '7GJ0FY8EX14',
  '6KM1C88DM17',
  '5DW5VQ5KM94',
  '6KV6A27JJ52',
  '7GP1RV2XY19',
  '4CG1JP6JK31',
  '7VM4QK7GN60',
  '4CY0DG5JT02',
  '7VP7X95KH36',
  '7VY7WN2GF62',
  '5EV3M96TT00',
  '7HY6CR3UA58',
  '5F02PT3TF23',
  '6N41EX5AG08',
  '8MC6K56JG74',
  '8ME4G91VD03',
  '9E18TH7FQ22',
  '4R38QQ0MN52',
  '9MW2XE7WW93',
  '6NJ2QK6MP07',
  '8MK0R07VD30',
  '6NM6R50RR41',
  '7WN4JV1RD91',
  '9TM8T54AJ25',
  '5FJ6GY3JP76',
  '6NU0UQ8CG19',
  '4RC8JY4DG45',
  '5FW3DU8UK14',
  '7WY4CF8WW85',
  '7WY5T39XX66',
  '4RD7KM5FH37',
  '5G18PH4GU35',
  '9NE0KQ5WR25',
  '7KC0E60DW37',
  '9U97PE1RN48',
  '7X96CY6WY67',
  '9UP1QH8QX98',
  '9XF0UG1HR06',
  '9XM6NY6CR41'],
 '1043210149': ['1DD5PP7AU96',
  '1GJ4AD8TY75',
  '7M00P51NW36',
  '1FP3VJ4TT03',
  '1V33GN1HC73',
  '1KW4QA1AM85',
  '1ER8K70HC63',
  '5YR7XR0HV48',
  '3KK2YR1DN27',
  '6A83Y49EY06',
  '1HM8CM7VN28',
  '6AQ9QJ8UK58',
  '2VW2YM0YC97',
  '3CP7CT9DX67',
  '4JC5TW5PH85',
  '9PM2JM4FG03',
  '4JG0MG2RF47',
  '7NQ2UG1HR84',
  '7NU6UG2KE87',
  '3FX7NA9KC48',
  '3FX8PX8KN66',
  '7P01GW6DM90',
  '1FR2F82FP83',
  '2Y64RC2WR68',
  '5J83CQ5CK05',
  '7YF5T54CA53',
  '2QR6DT9WH78',
  '1V63Q05VY13',
  '3HX2YU5NC90',
  '1G57QG2WT47',
  '6D47DV2TX31',
  '6UC7PA0EK38',
  '8R78VR4YH42',
  '3FA0NJ4TA10',
  '2P46JQ4EN53',
  '4GE1MA4RD04',
  '7QP9EG7PQ32',
  '3A45UM8MY52',
  '9QH9W91PR30',
  '3GR8A09FT65',
  '6T06F95TA49',
  '1AU5TH4XJ61',
  '2H98UE3HC48',
  '6EA0WN3CN38',
  '4DV6Y97VJ62',
  '2KY6HC9QA78',
  '6F95UE5GW94',
  '3H49FQ5XX51',
  '6FJ1TY3YR38',
  '3K83G78QA77',
  '6XK1EW8FK05',
  '9RE7V67NH50',
  '4UQ6TH0JC42',
  '6DP0KK5NJ37',
  '6H68V22YR30',
  '4WQ8TY8EW50',
  '4WY3WP8NP99',
  '4X08XW5QE42',
  '8XW8C87UC56',
  '3VP4RV9KH06',
  '7D63Y47HX12',
  '8YU5ED8CY92',
  '4YH7XM1DY34',
  '7DN9CY9XH15',
  '9AN7AM1HN39',
  '8HH0NN9GQ07',
  '8J19WQ5GN39',
  '9CD6EM6TJ68',
  '7EA4AQ6XJ66',
  '9KV5WC6KM93',
  '5W08TU1DQ21',
  '9WP0VR2JV46',
  '7GK0U64XE29',
  '6KV3TN7JE60',
  '4CP6VC8NU45',
  '7VJ0C00NP07',
  '7VK5FE9WM85',
  '7VM5M17UN40',
  '7HK5KA7VP68',
  '9DG7YQ9QT58',
  '9DP0D29JR33',
  '5WT9Q48UA13',
  '7JE2D01UH28',
  '7WE2UP0RN01',
  '5G29ND4DQ13'],
 '1053311068': ['2KM2WQ2JU92',
  '2KN1RW5MH35',
  '1CK7PN9QC57',
  '9V24G11VE93',
  '3NH3TA3TM03',
  '3GW2D19JQ98',
  '9V42GQ6NF17',
  '9V65TD2EV61',
  '5Y07RA5MQ31',
  '3NA9VY9XW46',
  '9XU9N50CJ21',
  '1NY1YJ1XY37',
  '1N40F34HC04',
  '9VE0CY3UP03',
  '9XY5NF5WA68',
  '7M71NH0JK94',
  '1QV1H87DK93',
  '7M98P79UA50',
  '7MC1MA9GD32',
  '1RQ2D87EU16',
  '9Y60MW8JG39',
  '8NP0NW3FQ22',
  '5GP9YR9PC41',
  '9YC8DT9YC61',
  '9YF9DG8UF27',
  '1HT5VW1WH79',
  '1HU0U60DN34',
  '1HV8XV5WF59',
  '7MV8CP3MQ56',
  '7MW4RW2YY95',
  '2J01P96GN99',
  '7N09VG3JH35',
  '6A36Q18UW79',
  '7N43HR6HC14',
  '1WD0U28CM39',
  '4F57T19RX42',
  '4F96VN1QT72',
  '7NC1FW6CY99',
  '8PF3XN6EC13',
  '9P96G62UK65',
  '6P27T47KJ68',
  '3F27DK2HF35',
  '1WJ2EF6HY95',
  '3Y29DU2HK58',
  '1H89PU9WE29',
  '2NP4TJ1CM99',
  '6AP2XW3VM89',
  '3XC9F87FT34',
  '1HG4W66UR67',
  '4HQ3PM7AQ92',
  '2UJ9N20WD00',
  '2UK5QH3NY56',
  '3XH5Q35QK73',
  '2PH7RA9RE50',
  '6AW0NY0EC17',
  '2P83NT0NQ19',
  '1YQ7WN0HW68',
  '3CG8MY4MA64',
  '3CH5TR8MA84',
  '9ER0T33YU37',
  '2DW4T36VD80',
  '4J94FP3AJ04',
  '5HK2G27NP70',
  '6PT2VW1RA12',
  '7XR4A98QH70',
  '9PH6TU7RX53',
  '1TQ9E40KP22',
  '6PV8D51DR10',
  '6PV8P88MT49',
  '9F06KK9QY30',
  '1R70HY3AJ03',
  '1KR6NH1YE55',
  '2E63J98GM93',
  '3JM1UR0YF12',
  '3JM5P89AH83',
  '7NY2F73TA70',
  '7XX0HR9DG02',
  '2EC9TD0UK30',
  '9PY7K43RU33',
  '5J07KD2PU34',
  '7Y71JM0KR09',
  '2GP0WY2JY38',
  '3YR4D46CA82',
  '9Q26QX2CC72',
  '2Y25KR9AP72',
  '3G64KF1QK63',
  '3MT9JH8JA33',
  '2RM9D67YE31',
  '1U28T20VJ10',
  '5J88NF0CK25',
  '2YA5PN9PM60',
  '4QF2MC1VT87',
  '1DX8VY0XJ24',
  '1E11RK6PM19',
  '5JD5KV4MJ60',
  '6C98F56AK65',
  '2CG3FQ3RF98',
  '2QF4K64DP64',
  '1U90WM0XH04',
  '7YP6PT4QU74',
  '1Q56VD2WU59',
  '4QT4KF1UF67',
  '7YV7MF6RY64',
  '1E93VX1JJ15',
  '2QP3FN1UJ97',
  '1MM5YF4HA70',
  '8QR1MP1PH80',
  '2GV3UM8GA95',
  '1UM7U94VE61',
  '1MV1X64FW11',
  '3HU0D60WG19',
  '4PF0CQ2HE06',
  '4KR5M64TJ89',
  '1XC0U29MY19',
  '4FG9C77YT18',
  '8R20K08YK10',
  '3UM3D14CY97',
  '1Y14M94PT03',
  '1EM6QV8XY86',
  '1EN1RN3MX97',
  '1EN6N60TY40',
  '2TH3UD7GT09',
  '8R26FV1QT84',
  '2F57GG3CW61',
  '2R97J43MA40',
  '2RA3PT7MF12',
  '6D63D89DT89',
  '2RF9H24NA33',
  '4PU7E55MU39',
  '4G04CC4AR01',
  '8RC5NR5NK50',
  '1FY8HY6XC48',
  '4G43GP4XH09',
  '4G52J33PM22',
  '4G54YF1KT88',
  '6UU7YY4KY53',
  '7Q58JG7FC45',
  '1XR6GT1FE55',
  '4TN3V86XM60',
  '2WY5WQ5MN88',
  '6V34Y21XE65',
  '1UQ5G12KD63',
  '2X39EE1AY21',
  '4GD1C21PC92',
  '4GD7F77HJ57',
  '1KJ3XA1JK03',
  '1NA5H18FY80',
  '4U06YN7QM88',
  '5K78KW4MX64',
  '1FG2GR7NU19',
  '1GT7D01HU47',
  '7QQ2VP1JJ08',
  '3A48DQ5XU10',
  '3WF0CA2KF17',
  '2U98XJ2FP49',
  '7YY0RJ2UM27',
  '3CU5T82QR57',
  '8A17MM9KC71',
  '8RG5MF4AF50',
  '8RH0PK5RC06',
  '2AG4YP2RQ76',
  '3EJ0F28UW23',
  '1EH4HE7WA65',
  '1EQ3X70WT95',
  '8A50N81UU19',
  '8A77E38KQ50',
  '9FU1VW8XF08',
  '9FV3H95AF19',
  '8RQ8TF4UX48',
  '9QJ4X76AU61',
  '3V95TY4TT62',
  '6RW9X01XU11',
  '1TH8AW0KK53',
  '1RW6XT1RN46',
  '2GE3RF0FE15',
  '1AT8KD1CD45',
  '4N07QE4XK56',
  '1AQ4UC1DG86',
  '3A34YN1XV70',
  '5KH1AK3PP36',
  '3T50F67JU10',
  '3T72A29QA96',
  '2CY8HP0PW55',
  '3T82MN5RA07',
  '1P49T58DM32',
  '1P56G68FN64',
  '3AE6MU1AQ64',
  '2J59VH8XK42',
  '1KQ3R48FK89',
  '4NA6M86NY58',
  '3YQ6R73VW88',
  '3YR0ED9YY11',
  '2PY5UV5WM87',
  '4DV0YP7MN25',
  '2XC0HH2NP21',
  '1VC3VQ6CX08',
  '4NN3J90YK97',
  '6ER9JG8CX29',
  '2JR3VJ4XA11',
  '3AA8QX7HA59',
  '2D95RP4UT82',
  '2M34CX7JR74',
  '4PX3KM0KP88',
  '8TN0T72XR42',
  '6RC4AR4DG65',
  '4Q80U76NQ10',
  '4Q87AC3DV53',
  '2NE5HN7WT75',
  '5M92TG1JH04',
  '6F07X20WY57',
  '8CK1Q96XV33',
  '8CP1QF5XD02',
  '8CQ5UF4JA81',
  '4P83HR0EJ83',
  '5MU5CQ3YQ66',
  '5MV2F97UR70',
  '8U80K11MK25',
  '5N91VK7JW25',
  '2UG6YX5QF58',
  '2UJ0E79EE19',
  '6WY5RD5NP79',
  '2WN8XE6VV25',
  '3JV4V96GT79',
  '2YJ9WG7FA16',
  '3K60WY6CC46',
  '9H57PJ7UF57',
  '3K90K66FC09',
  '9H82AX8UA97',
  '9R38F07ER25',
  '6XD4HJ5JV77',
  '3AU4AA6YK62',
  '3ME2QP9EK29',
  '5P75GH9TM74',
  '9HE6YA7AQ83',
  '9HH9FH3AK23',
  '6XQ8RQ9XK38',
  '9HM8FX7VP58',
  '4UA4WM2UD61',
  '8DC0T67TP11',
  '6XU9U75UD26',
  '6XW2XM1UA16',
  '8UY0CK1HP10',
  '8V46N78RX41',
  '3DW3KN9UH01',
  '8DY0KK0GE41',
  '5PG9RM2DX12',
  '8E40RW1NT37',
  '5PP4CA1QC91',
  '3FR0R76QM21',
  '8W46EG0FN73',
  '8EP7NF2HE43',
  '6DD5AY1MU95',
  '6YH7QE8PJ32',
  '4AJ9NE8GR48',
  '4VG5VK6KQ85',
  '4VJ7G89QR49',
  '5QF7PQ8CU30',
  '4VQ6E14QK59',
  '6GP9DU3XY19',
  '6YW5TH4UP57',
  '6YX8FF8GN37',
  '3RH2TA1WF99',
  '6DY0E93WG23',
  '8WG2UU2KE87',
  '9HR8N70EF36',
  '5QT3J58CM72',
  '7A61T51QA15',
  '5R35D39FT56',
  '7AC9R86PT24',
  '9J60HN1WH01',
  '4WG2KU9CG99',
  '5RD4YD6YC62',
  '7AP1NV6XQ11',
  '9JH1GG5YJ02',
  '8EU1GQ2KC05',
  '4X46TQ2JF77',
  '7C78H25NM35',
  '8XP3X00TG85',
  '7C96N69WA70',
  '8XU1GR0UD96',
  '3VH7V71UR60',
  '4XC8NX1MY29',
  '7CA9X20JE12',
  '8FP9Y81TR13',
  '8FQ1DE8RK10',
  '3VM4WV0HJ74',
  '3VR8F32VP33',
  '8Y68UP6UP26',
  '4XR3AA6TE85',
  '8Y93M57XP89',
  '8Y94EX5CH83',
  '7CX5UE2YV63',
  '8YC6P99YC81',
  '8GA0P49UJ46',
  '4YD3Q19GH87',
  '4YN8AW9DU64',
  '8H27XW9AC32',
  '9A52K37YY12',
  '8H63R90DY84',
  '7RU4WV7FR87',
  '8HF5EQ7YM62',
  '9AR7HU0HJ59',
  '9AW6DD2MH62',
  '4E18KG0NM38',
  '8HV3F28NK92',
  '8HX0JV8VE39',
  '5TM2QA3KN80',
  '8J44QP3KN02',
  '4EK7CR0GC20',
  '6HW5XE6CJ63',
  '7E19ER6XU45',
  '6J24X16XJ80',
  '7E20P18EN31',
  '6J46P48XM72',
  '9CA3PF0EK97',
  '6J93VQ5HP79',
  '7EA6KV9RD41',
  '5AG9XG9RQ26',
  '5TY9TP5QM56',
  '5U85K41KK74',
  '5UF4F74NE06',
  '5UG8WD8WF30',
  '7EM6X11JX75',
  '7EY4GM5YM67',
  '7F14GJ4GG84',
  '8JK0KT2CX45',
  '7F75KY1QV52',
  '7T87WV5VT61',
  '5VF9EM5TM12',
  '9KG2TA9PQ26',
  '5VN5WC8CM98',
  '7TG5Q86QQ86',
  '7TN6X42MT63',
  '9KT1R50FH09',
  '5VU9WR8XP45',
  '8KK1XR5TQ19',
  '8KN0XU7RM08',
  '8KT4WP5MD05',
  '9CT0DP7XY22',
  '9RQ7EM6YA41',
  '9CX7K03EP68',
  '5D43J97TY11',
  '6JX7DF8RA76',
  '9ME9H89GM21',
  '9MG6FH3YE66',
  '5DA7R02NX76',
  '5DF3AU4WP74',
  '8M88ND4RQ29',
  '8M94AX4TE81',
  '9D98QG1PY27',
  '9WH6G51FX73',
  '6KF0TV6RU08',
  '7G93T03WM87',
  '5W65QG4AF79',
  '6KK5VU5XK74',
  '9WU4Q45MT88',
  '5DY7J70UE71',
  '7H01PE7AA00',
  '6M45MA0UG80',
  '6M68MP1VK53',
  '5EA9AJ2RD31',
  '7H96Y03DW84',
  '4CU2N01MY93',
  '4CY0M54WP20',
  '7VQ7AX1QK79',
  '6MM9DR7XW35',
  '7HM1V14AT92',
  '7HN0E50JN09',
  '7HN0M94RJ16',
  '6MP9EV9GC31',
  '6MV6K74YC75',
  '6MV9AJ0CT58',
  '6MX5G50CP78',
  '9DQ7KU4EK59',
  '5WY3K50TU73',
  '6NA2YC1VU84',
  '8ME1UN2VC13',
  '5X94MC7NR71',
  '5X96KG2PT72',
  '9E37YK7UP43',
  '6NJ9U03AQ18',
  '7JK2TH3YV83',
  '7WK5R25YC98',
  '5XJ5GJ0CU91',
  '9EK1GW9UC80',
  '5FW7M65UK54',
  '9UH3RK9HH81',
  '9UP7Q20MU35'],
 '1053560979': ['9Y04NC3UK67',
  '5YF5V23NY52',
  '5YT6WF2AU30',
  '5H14P04TH76',
  '6A57X66RD36',
  '2KR7XD5WN52',
  '1HC0N42DT34',
  '3XD9CG7CP12',
  '2R78M15QM25',
  '4HQ4TP4WK79',
  '6PG2UY8DY92',
  '4J57PE4UT68',
  '7Y52AC2WT98',
  '4JX1K65EY16',
  '3P30TC3VR05',
  '3P69J01QJ22',
  '5JP9RM5KX30',
  '6TV9GC6AM44',
  '6CR1NK3JA21',
  '8QQ9AU4RF45',
  '7PP9XQ3QX10',
  '3J84XJ5JF71',
  '7QH9RH2WT58',
  '2K40QC8PE46',
  '2AF0JA1MV20',
  '9QA7MW2MQ71',
  '4H07WV1DG54',
  '7R62A04ME90',
  '6T06JK9JD71',
  '2PT6RG0MV69',
  '4NK2JA9JM06',
  '2XD9YM9DW20',
  '2D89WD2ED19',
  '8CF8VK1AD55',
  '5N39UY7EV20',
  '2UF7FY8JG20',
  '3AX9GP9CJ34',
  '8VY2C53PC19',
  '4V58J66JA24',
  '3RG7MF4PA64',
  '7AD3TJ7AR04',
  '7C07P75QX76',
  '8F78HY4CU51',
  '3VG9Q32HN34',
  '8GJ5CY0FA85',
  '9AK4TD2XT61',
  '9AQ6XF3RH77',
  '9CH0E40GG29',
  '5VT8AY0VN23',
  '7FM3DJ2KM87',
  '7H27U95GJ47',
  '5EC6MD8CK88',
  '6M84YC4GH92',
  '5XJ5PH2JP87',
  '5XM1N86RH04',
  '9U43Q49EH09'],
 '1083330336': ['8QC4P81AR02', '9QN6ET4PM50', '9HW1KW6QK34'],
 '1083481139': ['4F22CR0MX09',
  '7N12KJ5UE93',
  '9YY5C94GM97',
  '2WW8E99WN46',
  '6AX9YK4EM46',
  '3P45CH0YH89',
  '4TN7NQ8YT63',
  '9QM0JM4DU13',
  '3A31GV7UW09',
  '8CE2C54UJ99',
  '6F99GK1EU43',
  '3JU5NP2YY92',
  '4XD8J96VV56',
  '8FW7RH3VM35',
  '9KF1NU0WV10',
  '7TV0D25KF20',
  '7U70J74KK24',
  '7UN7TK8NW46',
  '4RC0MX6NM00',
  '5FP8X22UG45'],
 '1083616080': ['1FN7VN9QQ41',
  '2NW0UM9JM35',
  '1RQ3J77MA71',
  '2J49V45AP24',
  '2HX9QV6UD38',
  '8P18Q15XM68',
  '9P31R98WT36',
  '1W15GE8RQ82',
  '1WK1X30VX35',
  '2JC2XJ5YM10',
  '5HJ8XG2PK44',
  '1QF7TA9PN33',
  '5HQ3F41TH17',
  '9F18J41HG25',
  '1R87EV1DK45',
  '1QJ9DD2HP27',
  '6Q42KH5RC24',
  '2Y14XF6VW87',
  '2GP9RK1TU45',
  '9FC8FC0JW66',
  '9FE3A28QP92',
  '4QC8RY3MP51',
  '5JD0CE9WA21',
  '2CF8MV2RG28',
  '3P06HX6CQ81',
  '7YV6TF0NR30',
  '2QR3D45CP92',
  '1UP1JP6AV96',
  '3UM1UW6AX36',
  '4FH8FC0NT49',
  '4KW8UJ1EE39',
  '4M00KG2UR12',
  '1JP6R76AT64',
  '4M71J48HJ33',
  '7Q45VC4GE56',
  '5JY8A68TN28',
  '7QA0CF3GW16',
  '4TU4X00GG89',
  '1N80C12KY46',
  '2EG2K06FJ91',
  '4GM1U19XD29',
  '3CX6GE1JU62',
  '1VT9D87XE46',
  '2U79KX3HH42',
  '7YY6P36WP59',
  '9FG4GV6ET70',
  '1A97R72JR61',
  '4GR9G80CV40',
  '4MJ7HV1MC56',
  '2AH2GT3YK93',
  '4GY8HQ1HY56',
  '3HY7PQ4QH34',
  '3R71TJ5ME10',
  '6VW5X30CE59',
  '9FX8A05EG42',
  '3DG9U11CR17',
  '1TJ1ET5XQ90',
  '9QT0HF3DN13',
  '4N02E01NA89',
  '3XC2P29HV06',
  '2HF0TK8AU90',
  '2JH8WF8VF39',
  '2EJ5CW8WA95',
  '1VC2C65UR83',
  '4NN0K25JJ26',
  '5M47NU2WQ74',
  '2M47DQ6NT76',
  '6R23DW7PR84',
  '6QQ4V41NN71',
  '6EW2UH1CR89',
  '5MG4GE5NE87',
  '5N34T49KF66',
  '5N43XP2WD85',
  '6FT4C19GP64',
  '2YM5UY5QV64',
  '2YR0RF8GU27',
  '9RK0JF0AV33',
  '3DJ2MJ3NN96',
  '4UV2VA3YY24',
  '4UW5TT9XW73',
  '8VJ1W49GQ80',
  '8E24KP3KT95',
  '8EK6G56WX55',
  '4AD4H02RU06',
  '5QG8KX7XU29',
  '6GW1F72PV32',
  '8WN3WR8AA99',
  '8WN7AR5FE32',
  '8WR6JM6YV58',
  '6HM0YC8WP09',
  '7AD7J03GW68',
  '5T06DR0RY78',
  '4Y81DK3XR29',
  '4YC9CR1CE43',
  '8YW0H47YU41',
  '8HD9AJ6GV27',
  '8HW8JR6UE48',
  '5TV4PE0PC86',
  '6JF4CW4PD65',
  '9CK7QW8XG52',
  '5TY6KR8QY67',
  '5AR3QC0GH88',
  '8JX8UW8QY65',
  '7TA7T89VQ31',
  '9KK1TH1YK25',
  '7U73VQ1MM85',
  '3RN3YJ7AE82',
  '5VW9P48JK44',
  '5W88QM7RC20',
  '7GM4TR2XC79',
  '3TV4XD9CC96',
  '5WG4U70EX62',
  '9X18U29TF54',
  '5WN8F13UU24',
  '9TC0PQ0UA29',
  '9TD4JY9XW70',
  '9U90N50GE21',
  '7KH3J87VV81'],
 '1093782427': ['8XC7D57VW76'],
 '1093796534': ['5G51FX2AK21',
  '3NG2JE4RW81',
  '9V25NX9HE93',
  '9V72EE3FW02',
  '1JN1WP4UA99',
  '1NW1QA7HK24',
  '1N40PQ2VC14',
  '1PK0XG2UX45',
  '1PM1Q40RF22',
  '2HR1HW8CP03',
  '3PV6VA4KR48',
  '3Q01UD3FH95',
  '2DR0UW6RJ19',
  '1ET0C52RX11',

In [59]:
df

,bene_id,bene_masterid,bene_masterid_from,masterid_key,bene_yearquarter,bene_attributionyear,bene_quarterstart,bene_quarterstop,bene_hic_num_old,bene_hic_num,...,bene_2018q2,bene_zip,bene_personyears,fromfile,bene_npi_classification,bene_physicianalignment,bene_adi,alignmentflag_cba,in_va_max,sqlrundate
0,1285784,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC1M09VY20,...,None,None,1.000,None,Physician Assistant,None,75.0,1,0,2026-05-19 12:10:58.037
1,1285785,54635.0,4. Recursion,48956.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC9P96XT24,...,None,None,1.000,None,Nurse Practitioner,None,85.0,1,0,2026-05-21 03:50:21.653
2,1285786,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD0Y39DW28,...,None,None,0.500,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
3,1285787,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD5PP7AU96,...,None,None,0.833,None,Internal Medicine,None,88.0,1,0,2026-05-19 12:10:58.037
4,1285788,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD7CE2VQ73,...,None,None,1.000,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16297,1302081,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN6H77RG64,...,None,None,1.000,None,Family Medicine,None,84.0,1,0,2026-05-19 12:10:58.037
16298,1302082,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN8RM5ET53,...,None,None,1.000,None,Physician Assistant,None,49.0,1,1,2026-05-19 12:10:58.037
16299,1302083,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN9V05CQ51,...,None,None,1.000,None,Physician Assistant,None,94.0,0,1,2026-05-19 12:10:58.037
16300,1302084,53897.0,3. RecordChange1_NotPRVS,48135.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP2NT4RF24,...,None,None,1.000,None,Nurse Practitioner,None,82.0,1,0,2026-05-21 03:50:21.653
16301,1302085,54791.0,4. Recursion,49134.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP8P19TG35,...,None,None,1.000,None,Family Medicine,None,89.0,1,0,2026-05-21 03:50:21.653

In [61]:
df.query("bene_npi_classification == 'Physician Assistant' and  bene_adi <= 80")

,bene_id,bene_masterid,bene_masterid_from,masterid_key,bene_yearquarter,bene_attributionyear,bene_quarterstart,bene_quarterstop,bene_hic_num_old,bene_hic_num,...,bene_2018q2,bene_zip,bene_personyears,fromfile,bene_npi_classification,bene_physicianalignment,bene_adi,alignmentflag_cba,in_va_max,sqlrundate
0,1285784,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC1M09VY20,...,None,None,1.0,None,Physician Assistant,None,75.0,1,0,2026-05-19 12:10:58.037
42,1285826,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,8N03Q16UG83,...,None,None,1.0,None,Physician Assistant,None,57.0,0,1,2026-05-19 12:10:58.037
81,1285865,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,2M71RC0PP27,...,None,None,1.0,None,Physician Assistant,None,46.0,1,1,2026-05-19 12:10:58.037
132,1285916,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,3CJ6RJ6QC77,...,None,None,1.0,None,Physician Assistant,None,63.0,1,0,2026-05-19 12:10:58.037
183,1285967,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,4A85E68XU72,...,None,None,1.0,None,Physician Assistant,None,46.0,1,0,2026-05-19 12:10:58.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16202,1301986,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XF8QF6RP44,...,None,None,1.0,None,Physician Assistant,None,56.0,0,1,2026-05-19 12:10:58.037
16217,1302001,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,7XH2F09VP96,...,None,None,1.0,None,Physician Assistant,None,58.0,1,1,2026-05-19 12:10:58.037
16245,1302029,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,7KQ9PC3YF45,...,None,None,1.0,None,Physician Assistant,None,66.0,0,1,2026-05-19 12:10:58.037
16249,1302033,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,7XK2VD6PT91,...,None,None,1.0,None,Physician Assistant,None,66.0,0,1,2026-05-19 12:10:58.037
16298,1302082,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN8RM5ET53,...,None,None,1.0,None,Physician Assistant,None,49.0,1,1,2026-05-19 12:10:58.037

In [48]:
df.columns = df.columns.str.lower()
df

,bene_id,bene_masterid,bene_masterid_from,masterid_key,bene_yearquarter,bene_attributionyear,bene_quarterstart,bene_quarterstop,bene_hic_num_old,bene_hic_num,...,bene_2018q2,bene_zip,bene_personyears,fromfile,bene_npi_classification,bene_physicianalignment,bene_adi,alignmentflag_cba,in_va_max,sqlrundate
0,1285784,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC1M09VY20,...,None,None,1.000,None,Physician Assistant,None,75.0,1,0,2026-05-19 12:10:58.037
1,1285785,54635.0,4. Recursion,48956.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC9P96XT24,...,None,None,1.000,None,Nurse Practitioner,None,85.0,1,0,2026-05-21 03:50:21.653
2,1285786,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD0Y39DW28,...,None,None,0.500,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
3,1285787,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD5PP7AU96,...,None,None,0.833,None,Internal Medicine,None,88.0,1,0,2026-05-19 12:10:58.037
4,1285788,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD7CE2VQ73,...,None,None,1.000,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16297,1302081,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN6H77RG64,...,None,None,1.000,None,Family Medicine,None,84.0,1,0,2026-05-19 12:10:58.037
16298,1302082,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN8RM5ET53,...,None,None,1.000,None,Physician Assistant,None,49.0,1,1,2026-05-19 12:10:58.037
16299,1302083,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN9V05CQ51,...,None,None,1.000,None,Physician Assistant,None,94.0,0,1,2026-05-19 12:10:58.037
16300,1302084,53897.0,3. RecordChange1_NotPRVS,48135.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP2NT4RF24,...,None,None,1.000,None,Nurse Practitioner,None,82.0,1,0,2026-05-21 03:50:21.653
16301,1302085,54791.0,4. Recursion,49134.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP8P19TG35,...,None,None,1.000,None,Family Medicine,None,89.0,1,0,2026-05-21 03:50:21.653

In [68]:
df['bene_adi'] = df[df['bene_adi'].notna()]['bene_adi'].apply(int)
df

,bene_id,bene_masterid,bene_masterid_from,masterid_key,bene_yearquarter,bene_attributionyear,bene_quarterstart,bene_quarterstop,bene_hic_num_old,bene_hic_num,...,bene_2018q2,bene_zip,bene_personyears,fromfile,bene_npi_classification,bene_physicianalignment,bene_adi,alignmentflag_cba,in_va_max,sqlrundate
0,1285784,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC1M09VY20,...,None,None,1.000,None,Physician Assistant,None,75.0,1,0,2026-05-19 12:10:58.037
1,1285785,54635.0,4. Recursion,48956.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DC9P96XT24,...,None,None,1.000,None,Nurse Practitioner,None,85.0,1,0,2026-05-21 03:50:21.653
2,1285786,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD0Y39DW28,...,None,None,0.500,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
3,1285787,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD5PP7AU96,...,None,None,0.833,None,Internal Medicine,None,88.0,1,0,2026-05-19 12:10:58.037
4,1285788,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,1DD7CE2VQ73,...,None,None,1.000,None,Internal Medicine,None,63.0,1,0,2026-05-19 12:10:58.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16297,1302081,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN6H77RG64,...,None,None,1.000,None,Family Medicine,None,84.0,1,0,2026-05-19 12:10:58.037
16298,1302082,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN8RM5ET53,...,None,None,1.000,None,Physician Assistant,None,49.0,1,1,2026-05-19 12:10:58.037
16299,1302083,NaN,None,NaN,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XN9V05CQ51,...,None,None,1.000,None,Physician Assistant,None,94.0,0,1,2026-05-19 12:10:58.037
16300,1302084,53897.0,3. RecordChange1_NotPRVS,48135.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP2NT4RF24,...,None,None,1.000,None,Nurse Practitioner,None,82.0,1,0,2026-05-21 03:50:21.653
16301,1302085,54791.0,4. Recursion,49134.0,2026Q1,FY2026,2026-01-01,2026-03-31,None,9XP8P19TG35,...,None,None,1.000,None,Family Medicine,None,89.0,1,0,2026-05-21 03:50:21.653

In [ ]:
df.groupby('')

np.float64(77.0)

In [65]:
from collections import Counter

Counter(df[df['bene_adi'].notna()]['bene_adi'])

Counter({90.0: 679,
         80.0: 632,
         82.0: 555,
         89.0: 555,
         87.0: 548,
         84.0: 534,
         74.0: 534,
         66.0: 522,
         91.0: 509,
         85.0: 480,
         93.0: 458,
         78.0: 427,
         77.0: 421,
         47.0: 385,
         45.0: 372,
         51.0: 370,
         88.0: 352,
         63.0: 347,
         61.0: 345,
         67.0: 326,
         92.0: 316,
         43.0: 311,
         75.0: 308,
         71.0: 262,
         98.0: 252,
         64.0: 242,
         95.0: 231,
         52.0: 225,
         46.0: 224,
         76.0: 224,
         96.0: 215,
         79.0: 208,
         44.0: 199,
         60.0: 193,
         42.0: 189,
         94.0: 187,
         72.0: 183,
         83.0: 169,
         86.0: 145,
         59.0: 139,
         69.0: 139,
         81.0: 135,
         57.0: 132,
         54.0: 132,
         33.0: 126,
         73.0: 120,
         29.0: 120,
         68.0: 111,
         99.0: 103,
         50.0: 96,
         65.0: 94,
         62.0: 93,
         97.0: 91,
         56.0: 90,
         70.0: 86,
         58.0: 65,
         35.0: 57,
         40.0: 53,
         55.0: 46,
         49.0: 44,
         38.0: 30,
         23.0: 28,
         100.0: 25,
         53.0: 24,
         32.0: 9,
         27.0: 7,
         41.0: 7,
         31.0: 7,
         10.0: 4,
         36.0: 4,
         14.0: 4,
         26.0: 4,
         9.0: 3,
         48.0: 3,
         24.0: 3,
         25.0: 3,
         39.0: 3,
         17.0: 3,
         13.0: 3,
         28.0: 3,
         34.0: 2,
         2.0: 2,
         22.0: 2,
         37.0: 2,
         18.0: 2,
         30.0: 2,
         16.0: 1,
         12.0: 1,
         21.0: 1,
         20.0: 1,
         3.0: 1,
         19.0: 1})